#!/bin/bash
#
# Compile file in batch mode using GPC Pascal.
#
# Runs a compile with the input and output coming from/going to files.
#
# Execution:
#
# Compile [--pmach|--cmach] <file>
#
# <file> is the filename without extention.
#
# The files are:
#
# <file>.pas - The Pascal source file
# <file>.p6  - The intermediate file produced
# <file>.err - The errors output from the compiler
#
# Note that the l+ option must be specified to get a full
# listing in the .err file (or just a lack of l-).
#
# The flags are one of:
#
# --pmach	Generate mach code and run the result through pmach.
# --cmach	Generate mach code and run the result through cmach.
# --pint    Generate mach code and run the result through pint (default).
# --package Generate a unified executable with mach code and interpreter.
# --pgen    Generate assembly code via pgen for the current machine.
#
pmach=0
cmach=0
package=0
pgen=0
progfile=""
options=""
objects=""

for param in "$@" 
do

    if [ "$param" = "--pmach" ]; then
	
        pmach=1
        
    elif [ "$param" = "--cmach" ]; then
    
        cmach=1
        
    elif [ "$param" = "--package" ]; then
    
        package=1

    elif [ "$param" = "--pgen" ]; then
    
        pgen=1
      
    elif [ "$param" = "--help" ]; then
    
		echo
		echo "Compile with P6 using GPC"
		echo
		echo "Execute with:"
		echo
		echo "p6 [--pmach|--cmach|--package|--pgen] [<sourcefile>]..."
		echo
		echo "where <sourcefile> is the name of the source file without"
		echo "extention. The Pascal input file\(s\) are compiled and run"
		echo "as a group. Any compiler errors are output to the screen."
		echo "Input and output to and from the running program are from"
		echo "and to the console."
		echo
		echo "The flags are one of:"
		echo
		echo "--pmach	Generate mach code and run the result through pmach."
		echo "--cmach	Generate mach code and run the result through cmach."
		echo "--pint    Generate mach code and run the result through pint (default)."
        echo "--package Generate a packaged application and run."
        echo "--pgen    Generate assembly code with pgen for the current machine."
		echo
		echo "The intermediate code is placed in <file>.p6."
		echo
		exit 0
		
    elif [ "${param:0:1}" = "-" ]; then

        # concatentate unrecognized options in option string
        options="$options $param"

	elif [ ! -z "$param.pas" ]; then

	
		if [ ! -f "$param.pas" ]; then
		
			echo "$param.pas does not exist"
			exit 1
			
		fi
		echo Compiling $param...
	    pcom $param.pas $param.p6 $options >> temp.err
        if [ "$pgen" = "1" ]; then

            # generate .s assembly files
            cp $param.p6 prd
            pgen >> temp.err
            cp prr $param.s
            # form list of objects
            objects="$objects $param.s"

        else

            # generate concatenated intermediates
	        cat $param.p6 >> temp.p6

        fi
		progfile="$param"
		
    fi
    
done

if [ -z "$progfile" ]; then

	echo "*** Error: No compile file specified"
	exit 1
	
fi

#
# Put intermediate under the program filename (if not pgen)
#
if [ "$pgen" = "0" ]; then

    mv temp.p6 $progfile.p6

fi
mv temp.err $progfile.err

#
# The status of the compile is not returned, so convert a non-zero
# error message to fail status
#
grep -q "Errors in program: 0" $progfile.err
rc=$?
if [[ $rc != 0 ]] ; then

    exit 1
        
fi

#
# Construct combined intermediate under the program filename
#
if [ "$pmach" = "1" ]; then

    echo "o e+" > temp
	cat temp $progfile.p6 > prd
    rm temp
	pint
    cp prr progfile.p6o
	
elif [ "$cmach" = "1" ]; then

    echo "o e+" > temp
	cat temp $progfile.p6 > prd
    rm temp
	pint
    cp prr $progfile.p6o
	
elif [ "$package" = "1" ]; then

    echo "o e+" > temp
	cat temp $progfile.p6 > prd
    rm temp
	pint
    cp prr $progfile.p6o
	mv $progfile.p6o prd
	genobj
	cp prr program_code.c
	gcc -DPACKAGE -DWRDSIZ64 -I. -o $progfile $PASCALP6/source/cmach/cmach.c -lm

elif [ "$pgen" = "1" ]; then

    gcc -g3 -DWRDSIZ64 $PASCALP6/source/AMD64/gcc/psystem.c $objects -o $progfile -lm

fi
