#!/bin/bash
#
# Script to test p4 compile and run
#
# Compile p4
#
echo "Compiling pcom to intermediate code"
compile --list- $1 p4/pcom
cat p4/pcom.err
#
# Run the p2 interpreter via pint to get p2 intermediate
#
# Note temp is unused (prr out), and roman.p2 is read from the command line 
# at the second level.
#
pint p4/pcom.p6 temp p4/standardp.p4 < p4/standardp.pas
#
# Compile pint
#
echo Compiling pint to intermediate code
compile --list- $1 p4/pint
#
# Add the final target program to the end of pint.
# This means that the version of pint will read and interpret
# this.
#
# Create null input file
#
echo > p4/pint.inp
#
# Now run pint(p4) on pint(p6), which runs the test program.
#
# Note that temp is unused (prr out), and standardp.p2 and temp2 are read from the
# command line at level 2. temp2 is unused (prr out, second level).
#
if [ "$1" = "--pmach" ]; then

    pint p4/pint.p6 p4/pint.p6o --machdeck
    pmach p4/pint.p6o temp p4/standardp.p4 temp1 < p4/pint.inp > p4/standardp.lst

elif [ "$1" = "--cmach" ]; then

    pint p4/pint.p6 p4/pint.p6o --machdeck
    cmach p4/pint.p6o p4/standardp.p4 temp < p4/pint.inp > p4/standardp.lst

elif [ "$1" = "--package" ]; then

    pint p4/pint.p6 p4/pint.p6o --machdeck
    genobj p4/pint.p6o program_code.c
	gcc -DPACKAGE -DWRDSIZ64 -DGPC=0 -I. -o p4/pint $PASCALP6/source/cmach/cmach.c -lm
	p4/pint p4/standardp.p4 temp $options < p4/pint.inp > p4/standardp.lst

elif [ "$1" = "--pgen" ]; then

    pgen p4/pint.p6 p4/pint.s
    gcc -g3 -DWRDSIZ64 $PASCALP6/source/AMD64/gcc/psystem.c \
        -x assembler $PASCALP6/source/AMD64/gcc/psystem_asm.asm p4/pint.s -o p4/pint -lm
	p4/pint p4/standardp.p4 temp $options < p4/pint.inp > p4/standardp.lst

else

    pint p4/pint.p6 temp p4/standardp.p4 temp4 < p4/pint.inp > p4/standardp.lst

fi
#
# Now compare with reference
#
echo Comparing PAT result to reference
strip p4/standardp.lst tmp1
if [ "$1" = "--cmach" ] || [ "$1" = "--package" ] || [ "$1" = "--pgen" ]; then

    strip p4/standardpc.cmp tmp2
	
else

    strip p4/standardp.cmp tmp2

fi
diff -B tmp1 tmp2 > p4/standardp.dif
rm -f tmp1
rm -f tmp2
ls -l p4/standardp.dif > tmp1
grep ".dif" tmp1
rm -f tmp1
## pass if diff file is empty
if test -s p4/standardp.dif
then
    echo "*** FAIL"
    exit 1
else
    echo "PASS"
fi

rm -f p4/pcom.inp
rm -f p4/pint.inp
