program gstub(output);

uses graphics;

var ii, oo: integer;
    rr:     real;
    ss:     packed array [1..100] of char;
    ee:     evtrec;
    mm:     menuptr;
    spp:    strptr;
    ff:     text;
    wms:    winmodset;
    qfn:    qfnopts;
    qfr:    qfropts;
    qfe:    qfteffects;

procedure dummyeh(var er: evtrec); begin end;

begin
   rr := points(output);
   rr := points;
   ii := baseline(output);
   ii := baseline;
   ii := chrpos(output, ss, ii);
   ii := chrpos(ss, ii);
   ii := chrsizx(output);
   ii := chrsizx;
   ii := chrsizy(output);
   ii := chrsizy;
   ii := curbnd(output);
   ii := curbnd;
   ii := curx(output);
   ii := curx;
   ii := curxg(output);
   ii := curxg;
   ii := cury(output);
   ii := cury;
   ii := curyg(output);
   ii := curyg;
   ii := dpmx(output);
   ii := dpmx;
   ii := dpmy(output);
   ii := dpmy;
   ii := fonts(output);
   ii := fonts;
   ii := funkey(output);
   ii := funkey;
   ii := getwigid(output);
   ii := getwigid;
   ii := getwinid;
   ii := joyaxis(output, ii);
   ii := joyaxis(ii);
   ii := joybutton(output, ii);
   ii := joybutton(ii);
   ii := joystick(output);
   ii := joystick;
   ii := justpos(output, ss, ii, ii);
   ii := justpos(ss, ii, ii);
   ii := maxx(output);
   ii := maxx;
   ii := maxxg(output);
   ii := maxxg;
   ii := maxy(output);
   ii := maxy;
   ii := maxyg(output);
   ii := maxyg;
   ii := mousebutton(output, ii);
   ii := mousebutton(ii);
   ii := mouse(output);
   ii := mouse;
   ii := pictsizx(output, ii);
   ii := pictsizx(ii);
   ii := pictsizy(output, ii);
   ii := pictsizy(ii);
   ii := scalex(output, ii);
   ii := scalex(ii);
   ii := scaley(output, ii);
   ii := scaley(ii);
   ii := strsiz(output, ss);
   ii := strsiz(ss);
      alert(ss, ss);
      arc(output, ii, ii, ii, ii, ii, ii);
      arc(ii, ii, ii, ii, ii, ii);
      auto(output, ii);
      auto(ii);
      autohold(ii);
      back(output);
      back;
      background(output, ii, ii, ii, ii, ii);
      background(ii, ii, ii, ii, ii);
      backgroundg(output, ii, ii, ii, ii, ii);
      backgroundg(ii, ii, ii, ii, ii);
      backwidget(output, ii);
      backwidget(ii);
      band(output);
      band;
      bcolorc(output, ii, ii, ii);
      bcolorc(ii, ii, ii);
      bcolor(output, black);
      bcolor(black);
      bcolorg(output, ii, ii, ii);
      bcolorg(ii, ii, ii);
      binvis(output);
      binvis;
      blink(output, ii);
      blink(ii);
      bold(output, ii);
      bold(ii);
      blor(output);
      blor;
      bover(output);
      bover;
      buffer(output, ii);
      buffer(ii);
      button(output, ii, ii, ii, ii, ss, ii);
      button(ii, ii, ii, ii, ss, ii);
      buttong(output, ii, ii, ii, ii, ss, ii);
      buttong(ii, ii, ii, ii, ss, ii);
      buttonsiz(output, ss, ii, ii);
      buttonsiz(ss, ii, ii);
      buttonsizg(output, ss, ii, ii);
      buttonsizg(ss, ii, ii);
      bxor(output);
      bxor;
      checkbox(output, ii, ii, ii, ii, ss, ii);
      checkbox(ii, ii, ii, ii, ss, ii);
      checkboxg(output, ii, ii, ii, ii, ss, ii);
      checkboxg(ii, ii, ii, ii, ss, ii);
      checkboxsiz(output, ss, ii, ii);
      checkboxsiz(ss, ii, ii);
      checkboxsizg(output, ss, ii, ii);
      checkboxsizg(ss, ii, ii);
      chrspcx(output, ii);
      chrspcx(ii);
      chrspcy(output, ii);
      chrspcy(ii);
      clrtab(output);
      clrtab;
      condensed(output, ii);
      condensed(ii);
      cursor(output, ii, ii);
      cursor(ii, ii);
      cursorg(output, ii, ii);
      cursorg(ii, ii);
      curvis(output, ii);
      curvis(ii);
      del(output);
      del;
      delpict(output, ii);
      delpict(ii);
      down(output);
      down;
      dropbox(output, ii, ii, ii, ii, spp, ii);
      dropbox(ii, ii, ii, ii, spp, ii);
      dropboxg(output, ii, ii, ii, ii, spp, ii);
      dropboxg(ii, ii, ii, ii, spp, ii);
      dropboxsiz(output, spp, ii, ii, ii, ii);
      dropboxsiz(spp, ii, ii, ii, ii);
      dropboxsizg(output, spp, ii, ii, ii, ii);
      dropboxsizg(spp, ii, ii, ii, ii);
      dropeditbox(output, ii, ii, ii, ii, spp, ii);
      dropeditbox(ii, ii, ii, ii, spp, ii);
      dropeditboxg(output, ii, ii, ii, ii, spp, ii);
      dropeditboxg(ii, ii, ii, ii, spp, ii);
      dropeditboxsiz(output, spp, ii, ii, ii, ii);
      dropeditboxsiz(spp, ii, ii, ii, ii);
      dropeditboxsizg(output, spp, ii, ii, ii, ii);
      dropeditboxsizg(spp, ii, ii, ii, ii);
      editbox(output, ii, ii, ii, ii, ii);
      editbox(ii, ii, ii, ii, ii);
      editboxg(output, ii, ii, ii, ii, ii);
      editboxg(ii, ii, ii, ii, ii);
      editboxsiz(output, ss, ii, ii);
      editboxsiz(ss, ii, ii);
      editboxsizg(output, ss, ii, ii);
      editboxsizg(ss, ii, ii);
      ellipse(output, ii, ii, ii, ii);
      ellipse(ii, ii, ii, ii);
      enablewidget(output, ii, ii);
      enablewidget(ii, ii);
      event(output, ee);
      event(ee);
      eventover(etframe, dummyeh, oo);
      eventsover(dummyeh, oo);
      extended(output, ii);
      extended(ii);
      fand(output);
      fand;
      farc(output, ii, ii, ii, ii, ii, ii);
      farc(ii, ii, ii, ii, ii, ii);
      fchord(output, ii, ii, ii, ii, ii, ii);
      fchord(ii, ii, ii, ii, ii, ii);
      fcolorc(output, ii, ii, ii);
      fcolorc(ii, ii, ii);
      fcolor(output, black);
      fcolor(black);
      fcolorg(output, ii, ii, ii);
      fcolorg(ii, ii, ii);
      fellipse(output, ii, ii, ii, ii);
      fellipse(ii, ii, ii, ii);
      finvis(output);
      finvis;
      focus(output);
      focus;
      focuswidget(output, ii);
      focuswidget(ii);
      font(output, ii);
      font(ii);
      fontnam(output, ii, ss);
      fontnam(ii, ss);
      fontsiz(output, ii);
      fontsiz(ii);
      flor(output);
      flor;
      fover(output);
      fover;
      frame(output, ii);
      frame(ii);
      frametimer(output, ii);
      frametimer(ii);
      frect(output, ii, ii, ii, ii);
      frect(ii, ii, ii, ii);
      front(output);
      front;
      frontwidget(output, ii);
      frontwidget(ii);
      frrect(output, ii, ii, ii, ii, ii, ii);
      frrect(ii, ii, ii, ii, ii, ii);
      ftriangle(output, ii, ii, ii, ii, ii, ii);
      ftriangle(ii, ii, ii, ii, ii, ii);
      fxor(output);
      fxor;
      getsiz(output, ii, ii);
      getsiz(ii, ii);
      getsizg(output, ii, ii);
      getsizg(ii, ii);
      getwidgettext(output, ii, ss);
      getwidgettext(ii, ss);
      group(output, ii, ii, ii, ii, ss, ii);
      group(ii, ii, ii, ii, ss, ii);
      groupg(output, ii, ii, ii, ii, ss, ii);
      groupg(ii, ii, ii, ii, ss, ii);
      groupsiz(output, ss, ii, ii, ii, ii, ii, ii);
      groupsiz(ss, ii, ii, ii, ii, ii, ii);
      groupsizg(output, ss, ii, ii, ii, ii, ii, ii);
      groupsizg(ss, ii, ii, ii, ii, ii, ii);
      hollow(output, ii);
      hollow(ii);
      home(output);
      home;
      italic(output, ii);
      italic(ii);
      killtimer(output, ii);
      killtimer(ii);
      killwidget(output, ii);
      killwidget(ii);
      left(output);
      left;
      light(output, ii);
      light(ii);
      line(output, ii, ii, ii, ii);
      line(ii, ii, ii, ii);
      linestyle(output, lssolid);
      linestyle(lssolid);
      linewidth(output, ii);
      linewidth(ii);
      listbox(output, ii, ii, ii, ii, spp, ii);
      listbox(ii, ii, ii, ii, spp, ii);
      listboxg(output, ii, ii, ii, ii, spp, ii);
      listboxg(ii, ii, ii, ii, spp, ii);
      listboxsiz(output, spp, ii, ii);
      listboxsiz(spp, ii, ii);
      listboxsizg(output, spp, ii, ii);
      listboxsizg(spp, ii, ii);
      loadpict(output, ii, ss);
      loadpict(ii, ss);
      menuena(output, ii, ii);
      menuena(ii, ii);
      menu(output, mm);
      menu(mm);
      menusel(output, ii, ii);
      menusel(ii, ii);
      numselbox(output, ii, ii, ii, ii, ii, ii, ii);
      numselbox(ii, ii, ii, ii, ii, ii, ii);
      numselboxg(output, ii, ii, ii, ii, ii, ii, ii);
      numselboxg(ii, ii, ii, ii, ii, ii, ii);
      numselboxsiz(output, ii, ii, ii, ii);
      numselboxsiz(ii, ii, ii, ii);
      numselboxsizg(output, ii, ii, ii, ii);
      numselboxsizg(ii, ii, ii, ii);
      openwin(ff, ff, ff, ii);
      path(output, ii);
      path(ii);
      picture(output, ii, ii, ii, ii, ii);
      picture(ii, ii, ii, ii, ii);
      poswidget(output, ii, ii, ii);
      poswidget(ii, ii, ii);
      poswidgetg(output, ii, ii, ii);
      poswidgetg(ii, ii, ii);
      progbar(output, ii, ii, ii, ii, ii);
      progbar(ii, ii, ii, ii, ii);
      progbarg(output, ii, ii, ii, ii, ii);
      progbarg(ii, ii, ii, ii, ii);
      progbarpos(output, ii, ii);
      progbarpos(ii, ii);
      progbarsiz(output, ii, ii);
      progbarsiz(ii, ii);
      progbarsizg(output, ii, ii);
      progbarsizg(ii, ii);
      putwidgettext(output, ii, ss);
      putwidgettext(ii, ss);
      querycolor(ii, ii, ii);
      queryfind(ss, qfn);
      queryfindrep(ss, ss, qfr);
      queryfont(output, ii, ii, ii, ii, ii, ii, ii, ii, qfe);
      queryfont(ii, ii, ii, ii, ii, ii, ii, ii, qfe);
      queryopen(ss);
      querysave(ss);
      radiobutton(output, ii, ii, ii, ii, ss, ii);
      radiobutton(ii, ii, ii, ii, ss, ii);
      radiobuttong(output, ii, ii, ii, ii, ss, ii);
      radiobuttong(ii, ii, ii, ii, ss, ii);
      radiobuttonsiz(output, ss, ii, ii);
      radiobuttonsiz(ss, ii, ii);
      radiobuttonsizg(output, ss, ii, ii);
      radiobuttonsizg(ss, ii, ii);
      raised(output, ii);
      raised(ii);
      rect(output, ii, ii, ii, ii);
      rect(ii, ii, ii, ii);
      restab(output, ii);
      restab(ii);
      restabg(output, ii);
      restabg(ii);
      reverse(output, ii);
      reverse(ii);
      right(output);
      right;
      rrect(output, ii, ii, ii, ii, ii, ii);
      rrect(ii, ii, ii, ii, ii, ii);
      scncen(output, ii, ii);
      scncen(ii, ii);
      scnceng(output, ii, ii);
      scnceng(ii, ii);
      scnsiz(output, ii, ii);
      scnsiz(ii, ii);
      scnsizg(output, ii, ii);
      scnsizg(ii, ii);
      scroll(output, ii, ii);
      scroll(ii, ii);
      scrollg(output, ii, ii);
      scrollg(ii, ii);
      scrollhoriz(output, ii, ii, ii, ii, ii);
      scrollhoriz(ii, ii, ii, ii, ii);
      scrollhorizg(output, ii, ii, ii, ii, ii);
      scrollhorizg(ii, ii, ii, ii, ii);
      scrollhorizsiz(output, ii, ii);
      scrollhorizsiz(ii, ii);
      scrollhorizsizg(output, ii, ii);
      scrollhorizsizg(ii, ii);
      scrollpos(output, ii, ii);
      scrollpos(ii, ii);
      scrollsiz(output, ii, ii);
      scrollsiz(ii, ii);
      scrollvert(output, ii, ii, ii, ii, ii);
      scrollvert(ii, ii, ii, ii, ii);
      scrollvertg(output, ii, ii, ii, ii, ii);
      scrollvertg(ii, ii, ii, ii, ii);
      scrollvertsiz(output, ii, ii);
      scrollvertsiz(ii, ii);
      scrollvertsizg(output, ii, ii);
      scrollvertsizg(ii, ii);
      select(output, ii, ii);
      select(ii, ii);
      selectwidget(output, ii, ii);
      selectwidget(ii, ii);
      sendevent(output, ee);
      sendevent(ee);
      setpixel(output, ii, ii);
      setpixel(ii, ii);
      setpoints(output, rr);
      setpoints(rr);
      setpos(output, ii, ii);
      setpos(ii, ii);
      setposg(output, ii, ii);
      setposg(ii, ii);
      setsiz(output, ii, ii);
      setsiz(ii, ii);
      setsizg(output, ii, ii);
      setsizg(ii, ii);
      settab(output, ii);
      settab(ii);
      settabg(output, ii);
      settabg(ii);
      sizable(output, ii);
      sizable(ii);
      sizbuf(output, ii, ii);
      sizbuf(ii, ii);
      sizbufg(output, ii, ii);
      sizbufg(ii, ii);
      sizwidget(output, ii, ii, ii);
      sizwidget(ii, ii, ii);
      sizwidgetg(output, ii, ii, ii);
      sizwidgetg(ii, ii, ii);
      slidehoriz(output, ii, ii, ii, ii, ii, ii);
      slidehoriz(ii, ii, ii, ii, ii, ii);
      slidehorizg(output, ii, ii, ii, ii, ii, ii);
      slidehorizg(ii, ii, ii, ii, ii, ii);
      slidehorizsiz(output, ii, ii);
      slidehorizsiz(ii, ii);
      slidehorizsizg(output, ii, ii);
      slidehorizsizg(ii, ii);
      slidevert(output, ii, ii, ii, ii, ii, ii);
      slidevert(ii, ii, ii, ii, ii, ii);
      slidevertg(output, ii, ii, ii, ii, ii, ii);
      slidevertg(ii, ii, ii, ii, ii, ii);
      slidevertsiz(output, ii, ii);
      slidevertsiz(ii, ii);
      slidevertsizg(output, ii, ii);
      slidevertsizg(ii, ii);
      standout(output, ii);
      standout(ii);
      stdmenu(ii, mm, mm);
      strikeout(output, ii);
      strikeout(ii);
      subscript(output, ii);
      subscript(ii);
      superscript(output, ii);
      superscript(ii);
      sysbar(output, ii);
      sysbar(ii);
      tabbarclient(output, totop, ii, ii, ii, ii, ii, ii);
      tabbarclient(totop, ii, ii, ii, ii, ii, ii);
      tabbarclientg(output, totop, ii, ii, ii, ii, ii, ii);
      tabbarclientg(totop, ii, ii, ii, ii, ii, ii);
      tabbar(output, ii, ii, ii, ii, spp, totop, ii);
      tabbar(ii, ii, ii, ii, spp, totop, ii);
      tabbarg(output, ii, ii, ii, ii, spp, totop, ii);
      tabbarg(ii, ii, ii, ii, spp, totop, ii);
      tabbarsiz(output, totop, ii, ii, ii, ii, ii, ii);
      tabbarsiz(totop, ii, ii, ii, ii, ii, ii);
      tabbarsizg(output, totop, ii, ii, ii, ii, ii, ii);
      tabbarsizg(totop, ii, ii, ii, ii, ii, ii);
      tabsel(output, ii, ii);
      tabsel(ii, ii);
      timer(output, ii, ii, ii);
      timer(ii, ii, ii);
      title(output, ss);
      title(ss);
      underline(output, ii);
      underline(ii);
      up(output);
      up;
      viewoffg(output, ii, ii);
      viewoffg(ii, ii);
      viewscale(output, rr, rr);
      viewscale(rr, rr);
      winclient(output, ii, ii, ii, ii, wms);
      winclient(ii, ii, ii, ii, wms);
      winclientg(output, ii, ii, ii, ii, wms);
      winclientg(ii, ii, ii, ii, wms);
      writejust(output, ss, ii);
      writejust(ss, ii);
      wrtstr(output, ss);
      wrtstr(ss);
      wrtstrn(output, ss, ii);
      wrtstrn(ss, ii);
      xbold(output, ii);
      xbold(ii);
      xlight(output, ii);
      xlight(ii);

end.
