#!/bin/bash
#
# Run a Pascal file in batch mode using GPC Pascal
#
# Runs a Pascal intermediate in batch mode.
#
# Execution:
#
# run <file> [--pmach|--cmach|--pint] [<inpfile>] <file>
#
# <file> is the filename without extention.
#
# The files are:
#
# <file>.p6  - The intermediate file.
# <file>.dat - The prd file to program.
# <file>.out - The prr file produced.
# <file>.inp - The input file to the program.
# <file>.lst - The output file from the program.
# <file>.p6o - The object deck for mach, if selected.
#
# The flags are one of:
#
# --pmach Generate mach code and run the result through pmach.
# --cmach Generate mach code and run the result through cmach.
# --pint  Generate mach code and run the result through pint (default).
#

pint=0
pmach=0
cmach=0
package=0
pgen=1
progfile=""
options=""
nolist="0"

#echo "run: command line: $@"

for param in "$@" 
do

    if [ "$param" = "--pint" ]; then
	
        pint=1
        pmach=0
        cmach=0
        package=0
        pgen=0

    elif [ "$param" = "--pmach" ]; then
	
        pmach=1
        pint=0
        cmach=0
        package=0
        pgen=0
        
    elif [ "$param" = "--cmach" ]; then
    
        cmach=1
        pint=0
        pmach=0
        package=0
        pgen=0

    elif [ "$param" = "--package" ]; then
    
        package=1
        pint=0
        pmach=0
        cmach=0
        pgen=0

    elif [ "$param" = "--pgen" ]; then
    
        pgen=1
        pint=0
        pmach=0
        cmach=0
        package=0

    elif [ "$param" = "--nolist" ]; then
    
        nolist=1
      
    elif [ "$param" = "--help" ]; then

		echo ""  
		echo "Run a Pascal file in batch mode using GPC Pascal"
		echo ""
		echo "Runs a Pascal intermediate in batch mode."
		echo ""
		echo "Execution:"
		echo ""
		echo "run <file> [--pmach|--cmach|--pint] <file>"
		echo ""
		echo "<file> is the filename without extention."
		echo ""
		echo "The files are:"
		echo ""
		echo "<file>.p6  - The intermediate file"
		echo "<file>.out - The prr file produced"
		echo "<file>.inp - The input file to the program"
		echo "<file>.lst - The output file from the program"
		echo "<file>.p6o - The object deck for mach, if selected"
		echo ""
		echo "The flags are one of:"
		echo ""
		echo "--pmach  Generate mach code and run the result through pmach."
		echo "--cmach  Generate mach code and run the result through cmach."
		echo "--pint   Generate mach code and run the result through pint."
        echo "--pgen   Run binary code {default)."
		echo "--nolist Do not output listing."

		echo ""
		goto stop
		
    elif [ "${param:0:1}" = "-" ]; then

        # concatentate unrecognized options in option string
        options="$options $param"

	else
	
		progfile="$param"
		
    fi
    
done

if [ -z "$progfile" ]; then

	echo "*** Error: No run file specified"
	exit 1

fi

#
# Intermediates, the executable, products and temp files go to REGRESS_OUT when
# it is set, so several models can run in parallel into their own
# test_results/<model> directories. When unset they go next to the source as
# before. Input files (.inp, .dat) are always read from the source path.
#
if [ -n "$REGRESS_OUT" ]; then
    obase="$REGRESS_OUT/$(basename $progfile)"
    tmpd="$REGRESS_OUT/"
else
    obase="$progfile"
    tmpd=""
fi

if [ ! -f "$obase.p6" ]; then

	echo "$obase.p6 does not exist"
	exit 1

fi
if [ ! -f "$progfile.inp" ]; then

	echo "$progfile.inp does not exist"
	exit 1

fi

# The run result is the exit status of the selected backend, captured before the
# trailing cleanup and listing can clobber $? -- otherwise a stray rm/cat failure
# is misreported as a compile/run failure (issue #252).
rc=0
if [ "$pmach" = "1" ]; then

	echo Running with pmach
    echo "o e+" > ${tmpd}temp
    cat ${tmpd}temp $obase.p6 > ${tmpd}temp2.p6
    pint ${tmpd}temp2.p6 $obase.p6o > ${tmpd}temp
    cat $obase.p6o $progfile.dat > ${tmpd}temp.p6o
    pmach ${tmpd}temp.p6o $obase.out $options < $progfile.inp &> $obase.lst
    rc=$? # capture the run result before cleanup clobbers it
    rm ${tmpd}temp ${tmpd}temp2.p6

elif [ "$cmach" = "1" ]; then

	echo Running with cmach
    pint $obase.p6 $obase.p6o --machdeck > ${tmpd}temp
    cmach $obase.p6o $options $progfile.dat $obase.out < $progfile.inp &> $obase.lst
    rc=$? # capture the run result before cleanup clobbers it
    rm ${tmpd}temp

elif [ "$package" = "1" ]; then

    echo Running with package
    ./$obase $options $progfile.dat $obase.out < $progfile.inp &> $obase.lst
    rc=$?

elif [ "$pgen" = "1" ]; then

    echo Running with pgen
    ./$obase $progfile.dat $obase.out $options < $progfile.inp &> $obase.lst
    rc=$?

else

	echo Running with pint
    cat $obase.p6 $progfile.dat > ${tmpd}temp.p6
    pint ${tmpd}temp.p6 $obase.out $options < $progfile.inp &> $obase.lst
    rc=$? # capture the run result before cleanup clobbers it
    rm ${tmpd}temp.p6

fi

#
# Output listing if enabled
#
if [ "$nolist" = "0" ]; then

    cat $obase.lst

fi

exit $rc