#!/bin/bash
#
# Script to test p5 compile and run
#
# Compile p5/pcom to p6 intermediate
#
echo "Compiling pcom to intermediate code"
cpp -DWRDSIZ64 -P -nostdinc -traditional-cpp p5/source/pcom.pas p5/source/pcom.mpp.pas
compile --list- $1 p5/source/pcom.mpp
cat p5/source/pcom.mpp.err
#
# Run P5/pcom on P6/pint to compile iso7185pat to P5/intermediate
#
pint p5/source/pcom.mpp.p6 temp standard_tests/iso7185pat.pas p5/source/iso7185pat.p5
#
# Compile pint to p6/intermediate
#
echo "Compiling pint to intermediate code"
cpp -DSMALL_MODEL -DWRDSIZ64 -P -nostdinc -traditional-cpp p5/source/pint.pas p5/source/pint.mpp.pas
compile --list- $1 p5/source/pint.mpp
cat p5/source/pint.mpp.err
#
# Create null input file
#
echo > p5/source/pint.inp
#
# Now run pint(p4) on pint(p6), which runs the test program.
#
# Note that temp is unused (prr out), and standardp.p5 and temp2 are read from the
# command line at level 2. temp2 is unused (prr out, second level).
#
if [ "$1" = "--pmach" ]; then

    echo "Running pmach test..."
    pint p5/source/pint.mpp.p6 p5/source/pint.p6o --machdeck
    pmach p5/source/pint.p6o temp p5/source/iso7185pat.p5 temp1 < p5/source/pint.inp > p5/source/iso7185pat.lst

elif [ "$1" = "--cmach" ]; then

    echo "Running cmach test..."
    pint p5/source/pint.mpp.p6 p5/source/pint.p6o --machdeck
    cmach p5/source/pint.p6o p5/source/iso7185pat.p5 temp < p5/source/pint.inp > p5/source/iso7185pat.lst

elif [ "$1" = "--package" ]; then

    echo "Running package test..."
    pint p5/source/pint.mpp.p6 p5/source/pint.p6o --machdeck
    genobj p5/source/pint.p6o program_code.c
	gcc -DPACKAGE -DWRDSIZ64 -DGPC=0 -I. -o p5/source/pint $PASCALP6/source/cmach/cmach.c -lm
	p5/pint p5/source/iso7185pat.p5 temp $options < p5/source/pint.inp > p5/source/iso7185pat.lst

elif [ "$1" = "--pgen" ]; then

    echo "Running pgen test..."
    pgen p5/source/pint.mpp.p6 p5/source/pint.s
    gcc -g3 -DWRDSIZ64 $PASCALP6/source/AMD64/gcc/psystem.c \
        -x assembler $PASCALP6/source/AMD64/gcc/psystem_asm.asm 
        $PASCALP6/source/AMD64/gcc/main.asm p5/source/pint.s -o p5/source/pint -lm
	p5/pint p5/source/iso7185pat.p5 temp $options < p5/source/pint.inp > p5/source/iso7185pat.lst

else

    echo "Running pint test..."
    pint p5/source/pint.mpp.p6 temp p5/source/iso7185pat.p5 temp2 \
        < p5/source/pint.inp > p5/source/iso7185pat.lst

fi
#
# Now compare with reference
#
echo "Comparing PAT result to reference"
strip standard_tests/iso7185pat.lst tmp1
strip standard_tests/iso7185patp5c.cmp tmp2
diff -B tmp1 tmp2 > standard_tests/iso7185pat.dif
rm -f tmp1 tmp2
ls -l standard_tests/iso7185pat.dif > tmp1
grep ".dif" tmp1
rm -f tmp1
## pass if diff file is empty
if test -s standard_tests/iso7185pat.dif
then
    echo "*** FAIL"
    exit 1
else
    echo "PASS"
fi
