#!/bin/bash
#
# Script to test p2 compile and run
#
# Compile P2
#
echo "Compiling pcomp to intermediate code"
compile --list- $1 p2/pcomp
cat p2/pcomp.err
#
# Run the p2 interpreter via pint to get p2 intermediate
#
# Note temp is unused (prr out), and roman.p2 is read from the command line 
# at the second level.
#
pint p2/pcomp.p6 temp p2/roman.p2 < p2/roman.pas
#
# Compile pasint to intermediate code
#
echo Compiling pasint to intermediate
compile --list- --reference- $1 p2/pasint
cat p2/pasint.err
#
# Create null input file
#
echo > p2/pasint.inp
#
# Now run pasint on pint, which runs the test program.
#
# Note that temp is unused (prr out), and roman.p2 and temp2 are read from the
# command line at level 2. temp2 is unused (prr out, second level).
#
if [ "$1" = "--pmach" ]; then

    pint p2/pasint.p6 p2/pasint.p6o --machdeck
    pmach p2/pasint.p6o temp p2/roman.p2 temp2 < p2/pasint.inp > p2/roman.lst

elif [ "$1" = "--cmach" ]; then

    pint p2/pasint.p6 p2/pasint.p6o --machdeck
    cmach p2/pasint.p6o p2/roman.p2 temp < p2/pasint.inp > p2/roman.lst

elif [ "$1" = "--package" ]; then

    pint p2/pasint.p6 p2/pasint.p6o --machdeck
    genobj p2/pasint.p6o program_code.c
	gcc -DPACKAGE -DWRDSIZ64 -DGPC=0 -I. -o p2/pasint $PASCALP6/source/cmach/cmach.c -lm
	p2/pasint p2/roman.p2 temp $options < p2/pasint.inp > p2/roman.lst

elif [ "$1" = "--pgen" ]; then

    pgen p2/pasint.p6 p2/pasint.s
    gcc -g3 -DWRDSIZ64 $PASCALP6/source/pgen/psystem.c \
        -x assembler $PASCALP6/source/pgen/psystem.asm \
        $PASCALP6/source/pgen/main.asm p2/pasint.s -o p2/pasint -lm
	p2/pasint p2/roman.p2 temp $options < p2/pasint.inp > p2/roman.lst

else

    pint p2/pasint.p6 temp p2/roman.p2 temp2 < p2/pasint.inp > p2/roman.lst

fi
#
# Now compare with reference
#
echo Comparing PAT result to reference
strip p2/roman.lst tmp1
strip p2/roman.cmp tmp2
diff -B tmp1 tmp2 > p2/roman.dif
rm -f tmp1
rm -f tmp2
ls -l p2/roman.dif > tmp1
grep ".dif" tmp1
rm -f tmp1
## pass if diff file is empty
if test -s p2/roman.dif
then
    echo "*** FAIL"
    exit 1
else
    echo "PASS"
fi