!
! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
!
p       /home/samiam/projects/pascal/pascal-p6/source/pgen/amd64/registers.pas
o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
! {*******************************************************************************
:1
!
! Contains the declaration of registers in the AMD64 CPU target
!
! This includes the register type, and fixed tables classifying registers by type.
!
! *******************************************************************************}
!
! module registers;
:2
:3
:4
:5
:6
:7
:8
:9
!
! Module registers
!
b       m       registers
        sfr     l registers.6           ! Set function result
l registers.6=0
        cup     l registers.3 0          ! Call user procedure
        cal     l registers.5           ! Call initializer code strip
        sfr     l registers.6           ! Set function result
        cup     l registers.4 0          ! Call user procedure
        ret                             ! Return code strip
!
! const
:10
:11
!
! maxintreg = 14; { maximum number of assignable integer reg }
:12
:13
! maxfltreg = 16; { maximum number of assignable float reg }
:14
! maxintparreg = 6; { maximum number of integer/pointer parameter regs }
:15
! maxfltparreg = 8; { maximum number of floating parameter regs }
:16
! maxfltregw = 6; { maximum number of assignable float regs (Windows) }
:17
! maxintparregw = 4; { maximum number of parameter register slots (Windows) }
:18
! maxfltparregw = 4; { maximum number of float parameter register slots (Windows) }
:19
! regprefix = true; { % register prefix required }
:20
!
! type 
:21
:22
!
! { registers in AMD64 target }
! reg = (rgnull, rgrax, rgrbx, rgrcx, rgrdx, rgrsi, rgrdi, rgrbp, rgrsp, 
:23
:24
:25
!        rgr8, rgr9, rgr10, rgr11, rgr12, rgr13, rgr14, rgr15, 
:26
!        rgxmm0, rgxmm1, rgxmm2, rgxmm3, rgxmm4, rgxmm5, rgxmm6, rgxmm7,
:27
!        rgxmm8, rgxmm9, rgxmm10, rgxmm11, rgxmm12, rgxmm13, rgxmm14, rgxmm15);
:28
! regset = set of reg;
:29
!
! { set assignment preference registers }
! fixed
:30
:31
:32
!
! { integer register assignment order }
! intassord: array [1..maxintreg] of reg = array
:33
:34
:35
t       l registers.7 1 14
s       intassord f 0 ax(1,14)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.intassord 14
!     rgrbx, rgr12, rgr13, rgr14, rgr15, rgrcx, rgr8, rgr9, rgr10, rgr11, rgrsi, 
r
c x 2
:36
r
c x 13
r
c x 14
r
c x 15
r
c x 16
r
c x 3
r
c x 9
r
c x 10
r
c x 11
r
c x 12
r
c x 5
!     rgrdi, rgrdx, rgrax
r
c x 6
:37
r
c x 4
r
c x 1
! end;
:38
x
!
! { floating point register assignment order }
! fltassord: array [1..maxfltreg] of reg = array
:39
:40
:41
t       l registers.8 1 16
s       fltassord f 0 ax(1,16)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.fltassord 16
!     rgxmm8, rgxmm9, rgxmm10, rgxmm11, rgxmm12, rgxmm13, rgxmm14, rgxmm15, 
r
c x 25
:42
r
c x 26
r
c x 27
r
c x 28
r
c x 29
r
c x 30
r
c x 31
r
c x 32
!     rgxmm0, rgxmm1, rgxmm2, rgxmm3, rgxmm4, rgxmm5, rgxmm6, rgxmm7
r
c x 17
:43
r
c x 18
r
c x 19
r
c x 20
r
c x 21
r
c x 22
r
c x 23
r
c x 24
! end;
:44
x
!
! { parameter registers }
! parreg: array [1..7] of reg = array
:45
:46
:47
t       l registers.9 1 7
s       parreg f 0 ax(1,7)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.parreg 7
!     rgrdi, rgrsi, rgrdx, rgrcx, rgr8, rgr9, rgnull
r
c x 6
:48
r
c x 5
r
c x 4
r
c x 3
r
c x 9
r
c x 10
r
c x 0
! end;
:49
x
!
! { floating point parameter registers }
! parregf: array [1..8] of reg = array
:50
:51
:52
t       l registers.10 1 8
s       parregf f 0 ax(1,8)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.parregf 8
!     rgxmm0, rgxmm1, rgxmm2, rgxmm3, rgxmm4, rgxmm5, rgxmm6, rgxmm7
r
c x 17
:53
r
c x 18
r
c x 19
r
c x 20
r
c x 21
r
c x 22
r
c x 23
r
c x 24
! end;
:54
x
!
! { integer register assignment order (Windows x64): callee saved first, then
!   the volatile non-parameter registers, then the parameter registers }
! intassordw: array [1..maxintreg] of reg = array
:55
:56
:57
:58
t       l registers.11 1 14
s       intassordw f 0 ax(1,14)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.intassordw 14
!     rgrbx, rgr12, rgr13, rgr14, rgr15, rgr10, rgr11, rgrcx, rgr8, rgr9, rgrsi,
r
c x 2
:59
r
c x 13
r
c x 14
r
c x 15
r
c x 16
r
c x 11
r
c x 12
r
c x 3
r
c x 9
r
c x 10
r
c x 5
!     rgrdi, rgrdx, rgrax
r
c x 6
:60
r
c x 4
r
c x 1
! end;
:61
x
!
! { floating point register assignment order (Windows x64): xmm6-xmm15 are
!   callee saved and are never assigned, only the volatile xmm0-xmm5 are used,
!   with the non-parameter registers preferred }
! fltassordw: array [1..maxfltregw] of reg = array
:62
:63
:64
:65
:66
t       l registers.12 1 6
s       fltassordw f 0 ax(1,6)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.fltassordw 6
!     rgxmm4, rgxmm5, rgxmm0, rgxmm1, rgxmm2, rgxmm3
r
c x 21
:67
r
c x 22
r
c x 17
r
c x 18
r
c x 19
r
c x 20
! end;
:68
x
!
! { parameter registers (Windows x64) }
! parregw: array [1..5] of reg = array
:69
:70
:71
t       l registers.13 1 5
s       parregw f 0 ax(1,5)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.parregw 5
!     rgrcx, rgrdx, rgr8, rgr9, rgnull
r
c x 3
:72
r
c x 4
r
c x 9
r
c x 10
r
c x 0
! end;
:73
x
!
! { floating point parameter registers (Windows x64) }
! parregfw: array [1..4] of reg = array
:74
:75
:76
t       l registers.14 1 4
s       parregfw f 0 ax(1,4)ix(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.parregfw 4
!     rgxmm0, rgxmm1, rgxmm2, rgxmm3
r
c x 17
:77
r
c x 18
r
c x 19
r
c x 20
! end;
:78
x
!
! { all possible registers }
! allreg: regset = [rgrax, rgrbx, rgrcx, rgrdx, rgrsi, rgrdi,
:79
:80
:81
s       allreg f 0 sx(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
n l registers.allreg 32
!                   rgr8, rgr9, rgr10, rgr11, rgr12, rgr13, rgr14, rgr15,
:82
!                   rgxmm0, rgxmm1, rgxmm2, rgxmm3, rgxmm4, rgxmm5, rgxmm6,
:83
!                   rgxmm7, rgxmm8, rgxmm9, rgxmm10, rgxmm11, rgxmm12, rgxmm13,
:84
!                   rgxmm14, rgxmm15];
:85
c p ( 1 2 3 4 5 6 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32)
x
!
! procedure wrtreg(var f: text; r: reg);
:86
:87
! begin
b r wrtreg@p_fc_x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
s       f p -64 fc
s       r p -56 x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
l registers.15
:88
:88
        mst     1 l registers.16 l registers.17 ! Mark(frame) stack
!   case r of
:89
        lodx    2 -56                   ! Load local value(t)
        ordx                            ! Ordinal(t)
        stri    2 -128                  ! Store local(t)
        ujp     l registers.19          ! Unconditional jump
!     rgnull:  write(f, '<null>');
:90
l registers.21:90
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.22 1 1
        lca     6 '<null>'              ! Load constant string address
        ldci    6                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrax:   write(f, 'rax');
:91
l registers.23:91
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.24 1 1
        lca     3 'rax'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrbx:   write(f, 'rbx');
:92
l registers.25:92
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.26 1 1
        lca     3 'rbx'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrcx:   write(f, 'rcx');
:93
l registers.27:93
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.28 1 1
        lca     3 'rcx'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrdx:   write(f, 'rdx');
:94
l registers.29:94
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.30 1 1
        lca     3 'rdx'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrsi:   write(f, 'rsi');
:95
l registers.31:95
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.32 1 1
        lca     3 'rsi'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrdi:   write(f, 'rdi');
:96
l registers.33:96
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.34 1 1
        lca     3 'rdi'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrbp:   write(f, 'rbp');
:97
l registers.35:97
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.36 1 1
        lca     3 'rbp'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgrsp:   write(f, 'rsp');
:98
l registers.37:98
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.38 1 1
        lca     3 'rsp'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr8:    write(f, 'r8');
:99
l registers.39:99
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.40 1 1
        lca     2 'r8'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr9:    write(f, 'r9');
:100
l registers.41:100
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.42 1 1
        lca     2 'r9'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr10:   write(f, 'r10');
:101
l registers.43:101
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.44 1 1
        lca     3 'r10'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr11:   write(f, 'r11');
:102
l registers.45:102
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.46 1 1
        lca     3 'r11'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr12:   write(f, 'r12');
:103
l registers.47:103
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.48 1 1
        lca     3 'r12'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr13:   write(f, 'r13');
:104
l registers.49:104
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.50 1 1
        lca     3 'r13'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr14:   write(f, 'r14');
:105
l registers.51:105
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.52 1 1
        lca     3 'r14'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgr15:   write(f, 'r15');
:106
l registers.53:106
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.54 1 1
        lca     3 'r15'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm0:  write(f, 'xmm0'); 
:107
l registers.55:107
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.56 1 1
        lca     4 'xmm0'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm1:  write(f, 'xmm1'); 
:108
l registers.57:108
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.58 1 1
        lca     4 'xmm1'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm2:  write(f, 'xmm2'); 
:109
l registers.59:109
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.60 1 1
        lca     4 'xmm2'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm3:  write(f, 'xmm3'); 
:110
l registers.61:110
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.62 1 1
        lca     4 'xmm3'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm4:  write(f, 'xmm4'); 
:111
l registers.63:111
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.64 1 1
        lca     4 'xmm4'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm5:  write(f, 'xmm5'); 
:112
l registers.65:112
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.66 1 1
        lca     4 'xmm5'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm6:  write(f, 'xmm6'); 
:113
l registers.67:113
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.68 1 1
        lca     4 'xmm6'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm7:  write(f, 'xmm7');
:114
l registers.69:114
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.70 1 1
        lca     4 'xmm7'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm8:  write(f, 'xmm8');
:115
l registers.71:115
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.72 1 1
        lca     4 'xmm8'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm9:  write(f, 'xmm9'); 
:116
l registers.73:116
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.74 1 1
        lca     4 'xmm9'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm10: write(f, 'xmm10'); 
:117
l registers.75:117
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.76 1 1
        lca     5 'xmm10'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm11: write(f, 'xmm11'); 
:118
l registers.77:118
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.78 1 1
        lca     5 'xmm11'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm12: write(f, 'xmm12'); 
:119
l registers.79:119
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.80 1 1
        lca     5 'xmm12'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm13: write(f, 'xmm13'); 
:120
l registers.81:120
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.82 1 1
        lca     5 'xmm13'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm14: write(f, 'xmm14'); 
:121
l registers.83:121
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.84 1 1
        lca     5 'xmm14'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!     rgxmm15: write(f, 'xmm15');
:122
l registers.85:122
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.86 1 1
        lca     5 'xmm15'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.20          ! Unconditional jump
!   end
l registers.19
:123
:123
        lodi    2 -128                  ! Load local value(t)
        chki    0 32                    ! Bounds check(t)
        ldci    0                       ! Load constant(t)
        sbi                             ! Subtract integer
        xjp     l registers.88          ! Table(case) jump
l registers.88
        ujp     l registers.21          ! Unconditional jump
        ujp     l registers.23          ! Unconditional jump
        ujp     l registers.25          ! Unconditional jump
        ujp     l registers.27          ! Unconditional jump
        ujp     l registers.29          ! Unconditional jump
        ujp     l registers.31          ! Unconditional jump
        ujp     l registers.33          ! Unconditional jump
        ujp     l registers.35          ! Unconditional jump
        ujp     l registers.37          ! Unconditional jump
        ujp     l registers.39          ! Unconditional jump
        ujp     l registers.41          ! Unconditional jump
        ujp     l registers.43          ! Unconditional jump
        ujp     l registers.45          ! Unconditional jump
        ujp     l registers.47          ! Unconditional jump
        ujp     l registers.49          ! Unconditional jump
        ujp     l registers.51          ! Unconditional jump
        ujp     l registers.53          ! Unconditional jump
        ujp     l registers.55          ! Unconditional jump
        ujp     l registers.57          ! Unconditional jump
        ujp     l registers.59          ! Unconditional jump
        ujp     l registers.61          ! Unconditional jump
        ujp     l registers.63          ! Unconditional jump
        ujp     l registers.65          ! Unconditional jump
        ujp     l registers.67          ! Unconditional jump
        ujp     l registers.69          ! Unconditional jump
        ujp     l registers.71          ! Unconditional jump
        ujp     l registers.73          ! Unconditional jump
        ujp     l registers.75          ! Unconditional jump
        ujp     l registers.77          ! Unconditional jump
        ujp     l registers.79          ! Unconditional jump
        ujp     l registers.81          ! Unconditional jump
        ujp     l registers.83          ! Unconditional jump
        ujp     l registers.85          ! Unconditional jump
l registers.20
:123
! end;
:124
        retp    0                       ! Return from procedure/function(t)
l registers.16=128
l registers.17=32
!
! procedure wrtbreg(var f: text; r: reg);
e r
:125
:126
! begin
b r wrtbreg@p_fc_x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
s       f p -64 fc
s       r p -56 x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
l registers.89
:127
:127
        mst     1 l registers.90 l registers.91 ! Mark(frame) stack
!   case r of
:128
        lodx    2 -56                   ! Load local value(t)
        ordx                            ! Ordinal(t)
        stri    2 -128                  ! Store local(t)
        ujp     l registers.93          ! Unconditional jump
!     rgnull:  write(f, '<null>');
:129
l registers.95:129
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.96 1 1
        lca     6 '<null>'              ! Load constant string address
        ldci    6                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrax:   write(f, 'al');
:130
l registers.97:130
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.98 1 1
        lca     2 'al'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrbx:   write(f, 'bl');
:131
l registers.99:131
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.100 1 1
        lca     2 'bl'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrcx:   write(f, 'cl');
:132
l registers.101:132
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.102 1 1
        lca     2 'cl'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrdx:   write(f, 'dl');
:133
l registers.103:133
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.104 1 1
        lca     2 'dl'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrsi:   write(f, 'sil');
:134
l registers.105:134
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.106 1 1
        lca     3 'sil'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrdi:   write(f, 'dil');
:135
l registers.107:135
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.108 1 1
        lca     3 'dil'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrbp:   write(f, 'bpl');
:136
l registers.109:136
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.110 1 1
        lca     3 'bpl'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgrsp:   write(f, 'spl');
:137
l registers.111:137
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.112 1 1
        lca     3 'spl'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr8:    write(f, 'r8b');
:138
l registers.113:138
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.114 1 1
        lca     3 'r8b'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr9:    write(f, 'r9b');
:139
l registers.115:139
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.116 1 1
        lca     3 'r9b'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr10:   write(f, 'r10b');
:140
l registers.117:140
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.118 1 1
        lca     4 'r10b'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr11:   write(f, 'r11b');
:141
l registers.119:141
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.120 1 1
        lca     4 'r11b'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr12:   write(f, 'r12b');
:142
l registers.121:142
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.122 1 1
        lca     4 'r12b'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr13:   write(f, 'r13b');
:143
l registers.123:143
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.124 1 1
        lca     4 'r13b'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr14:   write(f, 'r14b');
:144
l registers.125:144
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.126 1 1
        lca     4 'r14b'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgr15:   write(f, 'r15b');
:145
l registers.127:145
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.128 1 1
        lca     4 'r15b'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm0:  write(f, 'xmm0'); 
:146
l registers.129:146
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.130 1 1
        lca     4 'xmm0'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm1:  write(f, 'xmm1'); 
:147
l registers.131:147
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.132 1 1
        lca     4 'xmm1'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm2:  write(f, 'xmm2'); 
:148
l registers.133:148
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.134 1 1
        lca     4 'xmm2'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm3:  write(f, 'xmm3'); 
:149
l registers.135:149
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.136 1 1
        lca     4 'xmm3'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm4:  write(f, 'xmm4'); 
:150
l registers.137:150
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.138 1 1
        lca     4 'xmm4'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm5:  write(f, 'xmm5'); 
:151
l registers.139:151
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.140 1 1
        lca     4 'xmm5'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm6:  write(f, 'xmm6'); 
:152
l registers.141:152
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.142 1 1
        lca     4 'xmm6'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm7:  write(f, 'xmm7');
:153
l registers.143:153
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.144 1 1
        lca     4 'xmm7'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm8:  write(f, 'xmm8');
:154
l registers.145:154
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.146 1 1
        lca     4 'xmm8'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm9:  write(f, 'xmm9'); 
:155
l registers.147:155
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.148 1 1
        lca     4 'xmm9'                ! Load constant string address
        ldci    4                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm10: write(f, 'xmm10'); 
:156
l registers.149:156
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.150 1 1
        lca     5 'xmm10'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm11: write(f, 'xmm11'); 
:157
l registers.151:157
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.152 1 1
        lca     5 'xmm11'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm12: write(f, 'xmm12'); 
:158
l registers.153:158
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.154 1 1
        lca     5 'xmm12'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm13: write(f, 'xmm13'); 
:159
l registers.155:159
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.156 1 1
        lca     5 'xmm13'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm14: write(f, 'xmm14'); 
:160
l registers.157:160
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.158 1 1
        lca     5 'xmm14'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!     rgxmm15: write(f, 'xmm15');
:161
l registers.159:161
        loda    2 -64                   ! Load local value(t)
        stra    2 -136                  ! Store local(t)
t       l registers.160 1 1
        lca     5 'xmm15'               ! Load constant string address
        ldci    5                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        ujp     l registers.94          ! Unconditional jump
!   end
l registers.93
:162
:162
        lodi    2 -128                  ! Load local value(t)
        chki    0 32                    ! Bounds check(t)
        ldci    0                       ! Load constant(t)
        sbi                             ! Subtract integer
        xjp     l registers.162         ! Table(case) jump
l registers.162
        ujp     l registers.95          ! Unconditional jump
        ujp     l registers.97          ! Unconditional jump
        ujp     l registers.99          ! Unconditional jump
        ujp     l registers.101         ! Unconditional jump
        ujp     l registers.103         ! Unconditional jump
        ujp     l registers.105         ! Unconditional jump
        ujp     l registers.107         ! Unconditional jump
        ujp     l registers.109         ! Unconditional jump
        ujp     l registers.111         ! Unconditional jump
        ujp     l registers.113         ! Unconditional jump
        ujp     l registers.115         ! Unconditional jump
        ujp     l registers.117         ! Unconditional jump
        ujp     l registers.119         ! Unconditional jump
        ujp     l registers.121         ! Unconditional jump
        ujp     l registers.123         ! Unconditional jump
        ujp     l registers.125         ! Unconditional jump
        ujp     l registers.127         ! Unconditional jump
        ujp     l registers.129         ! Unconditional jump
        ujp     l registers.131         ! Unconditional jump
        ujp     l registers.133         ! Unconditional jump
        ujp     l registers.135         ! Unconditional jump
        ujp     l registers.137         ! Unconditional jump
        ujp     l registers.139         ! Unconditional jump
        ujp     l registers.141         ! Unconditional jump
        ujp     l registers.143         ! Unconditional jump
        ujp     l registers.145         ! Unconditional jump
        ujp     l registers.147         ! Unconditional jump
        ujp     l registers.149         ! Unconditional jump
        ujp     l registers.151         ! Unconditional jump
        ujp     l registers.153         ! Unconditional jump
        ujp     l registers.155         ! Unconditional jump
        ujp     l registers.157         ! Unconditional jump
        ujp     l registers.159         ! Unconditional jump
l registers.94
:162
! end;
:163
        retp    0                       ! Return from procedure/function(t)
l registers.90=128
l registers.91=32
!
! function regl(r: reg): integer;
e r
:164
:165
! begin
b f regl@f_x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
s       r p -64 x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
l registers.163
:166
:166
        mst     1 l registers.164 l registers.165 ! Mark(frame) stack
!  if r = rgnull then regl := 6
:167
        lodx    2 -64                   ! Load local value(t)
        ldci    0                       ! Load constant(t)
        equi                            ! Equal(t)
         fjp l registers.167
!  else if r in [rgrax, rgrbx, rgrcx, rgrdx, rgrsi, rgrdi, rgrbp, rgrsp,
        ldci    6                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.168         ! Unconditional jump
l registers.167
:168
:168
        lodx    2 -64                   ! Load local value(t)
        ordx                            ! Ordinal(t)
!                rgr10, rgr11, rgr12, rgr13, rgr14, rgr15] then regl := 3
:169
        ldcs    (   1   2   3   4   5   6   7   8  11  12  13  14  15  16) ! Load constant(t)
        inn                             ! Set inclusion
         fjp l registers.169
!  else if r in [rgr8, rgr9] then regl := 2
        ldci    3                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.170         ! Unconditional jump
l registers.169
:170
:170
        lodx    2 -64                   ! Load local value(t)
        ordx                            ! Ordinal(t)
        ldcs    (   9  10)              ! Load constant(t)
        inn                             ! Set inclusion
         fjp l registers.171
!  else if r in [rgxmm0..rgxmm9] then regl := 4
        ldci    2                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.172         ! Unconditional jump
l registers.171
:171
:171
        lodx    2 -64                   ! Load local value(t)
        ordx                            ! Ordinal(t)
        ldcs    (  17  18  19  20  21  22  23  24  25  26) ! Load constant(t)
        inn                             ! Set inclusion
         fjp l registers.173
!  else regl := 5
        ldci    4                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.174         ! Unconditional jump
l registers.173
:172
:172
! end;
        ldci    5                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
l registers.174
:173
:173
l registers.172
:173
l registers.170
:173
l registers.168
:173
        reti    0                       ! Return from procedure/function(t)
l registers.164=112
l registers.165=16
!
! function bregl(r: reg): integer;
e f
:174
:175
! begin
b f bregl@f_x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
s       r p -64 x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
l registers.175
:176
:176
        mst     1 l registers.176 l registers.177 ! Mark(frame) stack
!  if r = rgnull then bregl := 6
:177
        lodx    2 -64                   ! Load local value(t)
        ldci    0                       ! Load constant(t)
        equi                            ! Equal(t)
         fjp l registers.179
!  else if r in [rgrax, rgrbx, rgrcx, rgrdx] then bregl := 2
        ldci    6                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.180         ! Unconditional jump
l registers.179
:178
:178
        lodx    2 -64                   ! Load local value(t)
        ordx                            ! Ordinal(t)
        ldcs    (   1   2   3   4)      ! Load constant(t)
        inn                             ! Set inclusion
         fjp l registers.181
!  else if r in [rgrsi, rgrdi, rgrbp, rgrsp, rgr8, rgr9] then bregl := 3
        ldci    2                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.182         ! Unconditional jump
l registers.181
:179
:179
        lodx    2 -64                   ! Load local value(t)
        ordx                            ! Ordinal(t)
        ldcs    (   5   6   7   8   9  10) ! Load constant(t)
        inn                             ! Set inclusion
         fjp l registers.183
!  else if r in [rgr10..rgr15, rgxmm0..rgxmm9] then bregl := 4
        ldci    3                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.184         ! Unconditional jump
l registers.183
:180
:180
        lodx    2 -64                   ! Load local value(t)
        ordx                            ! Ordinal(t)
        ldcs    (  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26) ! Load constant(t)
        inn                             ! Set inclusion
         fjp l registers.185
!  else bregl := 5
        ldci    4                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
        ujp     l registers.186         ! Unconditional jump
l registers.185
:181
:181
! end;
        ldci    5                       ! Load constant(t)
        stri    2 -72                   ! Store local(t)
l registers.186
:182
:182
l registers.184
:182
l registers.182
:182
l registers.180
:182
        reti    0                       ! Return from procedure/function(t)
l registers.176=112
l registers.177=16
!
! procedure wrtregs(var f: text; rs: regset; n: boolean);
e f
:183
:184
! var first: boolean; r: reg;
b r wrtregs@p_fc_sx(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)_b
s       f p -64 fc
s       rs p -152 sx(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
s       n p -48 b
:185
s       first l -153 b
s       r l -154 x(rgnull,rgrax,rgrbx,rgrcx,rgrdx,rgrsi,rgrdi,rgrbp,rgrsp,rgr8,rgr9,rgr10,rgr11,rgr12,rgr13,rgr14,rgr15,rgxmm0,rgxmm1,rgxmm2,rgxmm3,rgxmm4,rgxmm5,rgxmm6,rgxmm7,rgxmm8,rgxmm9,rgxmm10,rgxmm11,rgxmm12,rgxmm13,rgxmm14,rgxmm15)
! begin
l registers.187
:186
:186
        mst     1 l registers.188 l registers.189 ! Mark(frame) stack
        lda     2 -152                  ! Load local address
        loda    2 -56                   ! Load local value(t)
        mov     32                      ! Move(copy)
!  first := true; write(f, '['); 
:187
        ldcb    1                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
        strb    2 -153                  ! Store local(t)
        loda    2 -64                   ! Load local value(t)
        stra    2 -162                  ! Store local(t)
        ldcc    '['                     ! Load constant(t)
        loda    2 -162                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldci    1                       ! Load constant(t)
        csp     wrc                     ! Call system procedure/function: Write character to text file
!  for r := rgrax to rgxmm15 do 
:188
        ldci    1                       ! Load constant(t)
        stri    2 -162                  ! Store local(t)
        ldci    32                      ! Load constant(t)
        ordx                            ! Ordinal(t)
        stri    2 -170                  ! Store local(t)
        lodi    2 -162                  ! Load local value(t)
        chkx    0 32                    ! Bounds check(t)
        strx    2 -154                  ! Store local(t)
l registers.191
:188
        lodx    2 -154                  ! Load local value(t)
        ordx                            ! Ordinal(t)
        lodi    2 -170                  ! Load local value(t)
        leqi                            ! Less than or equal(t)
        fjp     l registers.192         ! False jump
!    if ((r in rs) = n) and not (r in [rgrbp, rgrsp]) then begin 
:189
        lodx    2 -154                  ! Load local value(t)
        ordx                            ! Ordinal(t)
        lda     2 -152                  ! Load local address
        inn                             ! Set inclusion
        lodb    2 -48                   ! Load local value(t)
        equb                            ! Equal(t)
        lodx    2 -154                  ! Load local value(t)
        ordx                            ! Ordinal(t)
        ldcs    (   7   8)              ! Load constant(t)
        inn                             ! Set inclusion
        notb                            ! Not(t)
        and                             ! And booleans
         fjp l registers.193
!    if not first then write(f, ', ');
:190
        lodb    2 -153                  ! Load local value(t)
        notb                            ! Not(t)
         fjp l registers.194
        loda    2 -64                   ! Load local value(t)
        stra    2 -180                  ! Store local(t)
t       l registers.195 1 1
        lca     2 ','                   ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -180                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
l registers.194
:190
!    wrtreg(f, r); first := false
:191
        sfr     l registers.196         ! Set function result
        loda    2 -64                   ! Load local value(t)
        lodx    2 -154                  ! Load local value(t)
        chkx    0 32                    ! Bounds check(t)
l registers.196=0
        cup     l registers.15 2        ! Call user procedure
:191
!  end;
        ldcb    0                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
        strb    2 -153                  ! Store local(t)
:192
l registers.193
:192
        lodx    2 -154                  ! Load local value(t)
        ordx                            ! Ordinal(t)
        lodi    2 -170                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l registers.192         ! True jump
        lodx    2 -154                  ! Load local value(t)
        incx    1                       ! Increment(t)
        chkx    0 32                    ! Bounds check(t)
        strx    2 -154                  ! Store local(t)
        ujp     l registers.191         ! Unconditional jump
l registers.192
:192
        lda     2 -154                  ! Load local address
        inv                             ! Invalidate address
!  write(f, ']')
:193
        loda    2 -64                   ! Load local value(t)
        stra    2 -162                  ! Store local(t)
        ldcc    ']'                     ! Load constant(t)
        loda    2 -162                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldci    1                       ! Load constant(t)
        csp     wrc                     ! Call system procedure/function: Write character to text file
! end;
:194
        retp    0                       ! Return from procedure/function(t)
l registers.188=176
l registers.189=32
!
! begin
e r
l registers.3
:195
:196
:196
        mst     0 l registers.197 l registers.198 ! Mark(frame) stack
! end.
:197
        retp    0                       ! Return from procedure/function(t)
l registers.197=0
l registers.198=0
l registers.4
        mst     0 l registers.200 l registers.201 ! Mark(frame) stack
        retp    0                       ! Return from procedure/function(t)
l registers.200=0
l registers.201=0
l registers.5
g 89
e m
f       0
