!
! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
!
p       /home/samiam/projects/pascal/pascal-p6/source/plain/extexec.pas
o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
! {*******************************************************************************
:1
! *                                                                              *
! *                       External model execution                               *
! *                                                                              *
! * The plain flavor of the external execution module: the plain interpreter    *
! * hosts no terminal or graphics model, so those executors error. Sound and    *
! * network come from execcommon, standard in every flavor. The pintt and pintg  *
! * interpreters add the terminal and graphics executors by module path.        *
! *                                                                              *
! * Generated by tools/extgen/genpexec.py; do not edit by hand.                  *
! *                                                                              *
! *******************************************************************************}
!
! module extexec;
:2
:3
:4
:5
:6
:7
:8
:9
:10
:11
:12
:13
:14
!
! Module extexec
!
b       m       extexec
        sfr     l extexec.6             ! Set function result
l extexec.6=0
        cup     l extexec.3 0            ! Call user procedure
        cal     l extexec.5             ! Call initializer code strip
        sfr     l extexec.6             ! Set function result
        cup     l extexec.4 0            ! Call user procedure
        ret                             ! Return code strip
!
! uses pint_mem;
:15
:16
t       l pint_mem.20 1 100
t       l pint_mem.21 1 100
t       l pint_mem.26 1 1
t       l pint_mem.31 1 1
t       l pint_mem.36 1 1
t       l pint_mem.41 1 1
t       l pint_mem.46 1 1
t       l pint_mem.51 1 1
t       l pint_mem.56 1 1
t       l pint_mem.61 1 1
t       l pint_mem.66 1 1
t       l pint_mem.71 1 1
t       l pint_mem.76 1 1
t       l pint_mem.81 1 1
t       l pint_mem.86 1 1
t       l pint_mem.91 1 1
t       l pint_mem.96 1 1
t       l pint_mem.101 1 1
t       l pint_mem.106 1 1
t       l pint_mem.111 1 1
t       l pint_mem.116 1 1
t       l pint_mem.121 1 1
t       l pint_mem.126 1 1
t       l pint_mem.135 1 1
!
! procedure execterminal(routine: integer; var params: integer); forward;
:17
:18
! procedure execgraph(routine: integer; var params: integer); forward;
:19
!
! private
:20
:21
!
! const FunctionNotImplemented = 90; { external function not implemented }
:22
:23
!
! procedure execterminal(routine: integer; var params: integer);
:24
:25
!
! begin
b r execterminal@p_i_i
s       routine p -64 i
s       params p -56 i
l extexec.141
:26
:27
:27
        mst     1 l extexec.144 l extexec.145 ! Mark(frame) stack
!
!    refer(routine);
:28
:29
!    refer(params);
:30
!
!    errore(FunctionNotImplemented)
:31
:32
        sfr     l extexec.147           ! Set function result
        ldci    90                      ! Load constant(t)
!
! end;
l extexec.147=0
        cuv     l pint_mem.errore__virtvec 1 ! Call virtual procedure
:33
:34
:34
        retp    0                       ! Return from procedure/function(t)
l extexec.144=112
l extexec.145=8
!
! procedure execgraph(routine: integer; var params: integer);
e r
:35
:36
!
! begin
b r execgraph@p_i_i
s       routine p -64 i
s       params p -56 i
l extexec.142
:37
:38
:38
        mst     1 l extexec.149 l extexec.150 ! Mark(frame) stack
!
!    refer(routine);
:39
:40
!    refer(params);
:41
!
!    errore(FunctionNotImplemented)
:42
:43
        sfr     l extexec.152           ! Set function result
        ldci    90                      ! Load constant(t)
!
! end;
l extexec.152=0
        cuv     l pint_mem.errore__virtvec 1 ! Call virtual procedure
:44
:45
:45
        retp    0                       ! Return from procedure/function(t)
l extexec.149=112
l extexec.150=8
!
! begin
e r
l extexec.3
:46
:47
:47
        mst     0 l extexec.153 l extexec.154 ! Mark(frame) stack
! end.
:48
        retp    0                       ! Return from procedure/function(t)
l extexec.153=0
l extexec.154=0
l extexec.4
        mst     0 l extexec.156 l extexec.157 ! Mark(frame) stack
        retp    0                       ! Return from procedure/function(t)
l extexec.156=0
l extexec.157=0
l extexec.5
g 89
e m
f       0
