{*******************************************************************************
*                                                                              *
*                       Terminal external execution                            *
*                                                                              *
* The plain flavor of the external execution module: the plain interpreter    *
* hosts no I/O model, so executing a terminal or graphics external is an      *
* error. The pintt and pintg interpreters select the real flavors by module   *
* path.                                                                        *
*                                                                              *
* Generated by tools/extgen/genexec.py; do not edit by hand.                  *
*                                                                              *
*******************************************************************************}

module extterm;

uses pint_mem; { low level vm access for pint }

procedure execterminal(routine: integer; var params: integer); forward;
procedure execgraph(routine: integer; var params: integer); forward;

private

const FunctionNotImplemented = 90;

procedure execterminal(routine: integer; var params: integer);

begin

   refer(routine);
   refer(params);

   errore(FunctionNotImplemented)

end;

procedure execgraph(routine: integer; var params: integer);

begin

   refer(routine);
   refer(params);

   errore(FunctionNotImplemented)

end;

begin
end.
