#!/usr/bin/env python3
# Generate the Pascaline sound and network bindings from the Ami headers.
# Self-contained: reads amitk/include/{sound,network}.h and writes
#   libs/source/<mod>.pas           module interface (consts, types, decls)
#   libs/source/<mod>_wrapper.c     generated C wrappers (plain glibc stdio)
#   tools/sndnetgen/<mod>stub.pas   stub program for trampoline mangling
# The FILE*-carrying network functions are hand-written in
# libs/source/network_support.c; they are declared in network.pas here but
# excluded from wrapper/stub generation (SPECIALS).
import re, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
INC  = os.path.join(ROOT, 'amitk', 'include')
SRC  = os.path.join(ROOT, 'libs', 'source')

# functions not bound at all (plugin registration, raw sequencer access)
SKIP = {'wrsynth', 'rdsynth', 'excseq'}
# header-vs-source name corrections (sound.h declares ami_getparamswaveout,
# sound.c defines ami_getparamwaveout)
FIXNAME = {'getparamswaveout': 'getparamwaveout'}
# bound, but the wrapper is hand-written in network_support.c
SPECIALS = {'opennet', 'opennetv6', 'waitnet', 'certnet',
            'certlistnet', 'certlistmsg', 'certlistfree'}

def protos(hdr):
    """Read prototypes, joining continuation lines."""
    out=[]; cur=''
    for line in open(os.path.join(INC, hdr)):
        line=line.rstrip()
        if cur:
            cur += ' '+line.strip()
        elif re.match(r'^(void|int|FILE\*)\s+ami_', line):
            cur = line.strip()
        else:
            continue
        if cur.endswith(';'):
            out.append(re.sub(r'\s+', ' ', cur[:-1]))
            cur=''
    return out

def parse(p):
    m=re.match(r'^(void|int|FILE\*)\s+ami_([a-z0-9]+)\s*\((.*)\)$', p)
    if not m: return None
    ret,name,args=m.group(1),m.group(2),m.group(3).strip()
    name=FIXNAME.get(name, name)
    params=[] if args in('','void') else [a.strip() for a in args.split(',')]
    pl=[]
    for a in params:
        a=a.replace('const ','')
        mm=re.match(r'^(.*?)\s*\*?\s*([A-Za-z_]\w*)$', a)
        ct=mm.group(1).strip()+('*' if '*' in a.replace(mm.group(1),'',1) else '')
        ct=a[:a.rfind(mm.group(2))].strip()
        pl.append((ct, mm.group(2)))
    return ret,name,pl

def consts(hdr, strip):
    """#define AMI_X V -> (x, v) lowercased."""
    out=[]
    for line in open(os.path.join(INC, hdr)):
        m=re.match(r'^#define\s+AMI_([A-Z0-9_]+)\s+(\d+)\s*(/\*.*)?$', line)
        if m: out.append((m.group(1).lower(), m.group(2)))
    return out

# ---------- per-parameter classification ----------
# returns list of groups: ('scalar', pasdecl, cdecl, callarg)
#                         ('instr',  ...) input string (2 slots)
#                         ('outstr', ...) output string pair, eats next len param
#                         ('buf',    ...) byte/void buffer, eats next len param
def classify(name, pl):
    groups=[]; i=0
    ptypes={'ami_channel':'chan','ami_note':'note','ami_instrument':'instrument'}
    while i < len(pl):
        ct,pn = pl[i]; cn=ct.replace(' ','')
        nxt = pl[i+1] if i+1 < len(pl) else (None,None)
        if cn=='string' and nxt[0] is not None and nxt[0].replace(' ','')=='int' \
           and nxt[1] in ('len','sl') and i+1 == len(pl)-1:
            groups.append(('outstr', pn)); i+=2; continue
        if cn=='string':
            groups.append(('instr', pn)); i+=1; continue
        if cn in ('byte*','void*'):
            groups.append(('buf', pn, pl[i+1][1])); i+=2; continue
        if cn in ('unsignedlong*','unsignedlonglong*'):
            groups.append(('outcard', pn,
                           'unsigned long long*' if 'longlong' in cn
                           else 'unsigned long*')); i+=1; continue
        if cn in ('unsignedlong','unsignedlonglong'):
            groups.append(('card', pn)); i+=1; continue
        if cn in ptypes:
            groups.append(('typed', pn, ptypes[cn])); i+=1; continue
        groups.append(('scalar', pn)); i+=1; continue
    return groups

def gen_module(mod, hdr, title, types, specials_decls):
    ps=[parse(p) for p in protos(hdr)]
    ps=[p for p in ps if p and p[1] not in SKIP]
    gen=[p for p in ps if p[1] not in SPECIALS]

    # ----- module .pas -----
    pas=[]
    pas.append('{'+'*'*78)
    pas.append('')
    pas.append('%s' % title)
    pas.append('')
    pas.append('Pascaline binding to the Ami %s library. Generated by' % mod)
    pas.append('tools/sndnetgen/gen.py from amitk/include/%s; do not edit by hand.' % hdr)
    pas.append('')
    pas.append('*'*78+'}')
    pas.append('')
    pas.append('module %s;' % mod)
    pas.append('')
    cl=consts(hdr, mod)
    if cl:
        pas.append('const')
        for n,v in cl: pas.append('   %s = %s;' % (n, v))
        pas.append('')
    if types:
        pas.append('type')
        pas += ['   '+t for t in types]
        pas.append('')
    for ret,name,pl in ps:
        if name in SPECIALS: continue
        args=[]
        for g in classify(name, pl):
            k=g[0]
            if k=='scalar':  args.append('%s: integer' % g[1])
            elif k=='typed': args.append('%s: %s' % (g[1], g[2]))
            elif k=='card':  args.append('%s: lcardinal' % g[1])
            elif k=='outcard': args.append('var %s: lcardinal' % g[1])
            elif k=='instr': args.append('view %s: string' % g[1])
            elif k=='outstr':args.append('var %s: string' % g[1])
            elif k=='buf':
                args.append(('var' if name.startswith('rd') else 'view')
                            +' %s: bytarr' % g[1])
        sig='(%s)' % '; '.join(args) if args else ''
        if ret=='int':
            pas.append('function %s%s: integer; external;' % (name, sig))
        else:
            pas.append('procedure %s%s; external;' % (name, sig))
    if specials_decls:
        pas.append('')
        pas += specials_decls
    pas.append('')
    pas.append('begin')
    pas.append('end.')
    open(os.path.join(SRC, mod+'.pas'),'w').write('\n'.join(pas)+'\n')

    # ----- wrapper .c -----
    c=[]
    c.append('/* Generated %s wrappers. Do not edit by hand.' % mod)
    c.append(' *')
    c.append(' * Compiled against plain glibc stdio (no STDIO_BYPASS): the %s' % mod)
    c.append(' * library lives in the glibc world. Only the string conversion')
    c.append(' * helpers are shared with the bypass world; they touch no FILE.')
    c.append(' */')
    c.append('')
    c.append('#include <%s>' % hdr)
    c.append('')
    c.append('extern char* cstrz(char* s, int l); /* support.o: trim pad + terminate */')
    if mod=='sound':
        c.append('/* sound.h declares this one with a stray s (getparamswaveout) */')
        c.append('void ami_getparamwaveout(int p, string name, string value, int len);')
    c.append('')
    for ret,name,pl in gen:
        cret = 'int' if ret=='int' else 'void'
        cargs=[]; call=[]; post=[]
        for g in classify(name, pl):
            k=g[0]
            if k in ('scalar','typed'):
                cargs.append('int %s' % g[1]); call.append(g[1])
            elif k=='card':
                cargs.append('long %s' % g[1]); call.append(g[1])
            elif k=='outcard':
                cargs.append('long* %s' % g[1])
                call.append('(%s)%s' % (g[2], g[1]))
            elif k=='instr':
                cargs.append('char* %s' % g[1]); cargs.append('int %sl' % g[1])
                call.append('cstrz(%s, %sl)' % (g[1], g[1]))
            elif k=='outstr':
                cargs.append('char* %s' % g[1]); cargs.append('int %sl' % g[1])
                call.append(g[1]); call.append('%sl' % g[1])
                post.append('    { int _p = 0; while (_p < %sl && %s[_p]) _p++;'
                            % (g[1], g[1]))
                post.append("      while (_p < %sl) %s[_p++] = ' '; }"
                            % (g[1], g[1]))
            elif k=='buf':
                cargs.append('char* %s' % g[1]); cargs.append('int %sl' % g[1])
                call.append('(void*)%s' % g[1]); call.append('%sl' % g[1])
        sig=', '.join(cargs) if cargs else 'void'
        body='    %sami_%s(%s);' % ('return ' if cret=='int' else '',
                                    name, ', '.join(call))
        c.append('%s wrapper_%s(%s)' % (cret, name, sig))
        c.append('{')
        c.append(body)
        c += post
        c.append('}')
        c.append('')
    open(os.path.join(SRC, mod+'_wrapper.c'),'w').write('\n'.join(c)+'\n')

    # ----- stub .pas -----
    s=[]
    s.append('{ Stub program: references every %s binding form so the mangled' % mod)
    s.append('  names appear in the object for trampoline generation. Compile with')
    s.append('  pc (the link fails; only the .o is needed). }')
    s.append('program %sstub(output);' % mod)
    s.append('')
    s.append('uses %s;' % mod)
    s.append('')
    s.append('var ii: integer;')
    s.append('    lc: lcardinal;')
    s.append('    ss: packed array [1..100] of char;')
    s.append('    bb: packed array [1..100] of byte;')
    s.append('    tf, tg: text;')
    s.append('    cp: certptr;' if mod=='network' else
             '    ch: chan; nt: note; it: instrument;')
    s.append('')
    s.append('begin')
    for ret,name,pl in ps:
        if name in SPECIALS:
            continue
        args=[]
        for g in classify(name, pl):
            k=g[0]
            if k=='scalar': args.append('1')
            elif k=='typed': args.append({'chan':'ch','note':'nt',
                                          'instrument':'it'}[g[2]])
            elif k=='card': args.append('lc')
            elif k=='outcard': args.append('lc')
            elif k=='instr': args.append("ss")
            elif k=='outstr': args.append('ss')
            elif k=='buf': args.append('bb')
        a='(%s)' % ', '.join(args) if args else ''
        if ret=='int': s.append('   ii := %s%s;' % (name, a))
        else:          s.append('   %s%s;' % (name, a))
    # specials referenced too (their trampolines are needed)
    if mod=='network':
        s.append('   opennet(tf, tg, lc, 1, 0);')
        s.append('   opennetv6(tf, tg, lc, lc, 1, 0);')
        s.append('   waitnet(tf, tg, 1, 0);')
        s.append('   ii := certnet(tf, 1, ss);')
        s.append('   certlistnet(tf, 1, cp);')
        s.append('   certlistmsg(1, 1, cp);')
        s.append('   certlistfree(cp)')
    else:
        s[-1]=s[-1].rstrip(';')
    s.append('end.')
    open(os.path.join(HERE, mod+'stub.pas'),'w').write('\n'.join(s)+'\n')
    print('%s: %d functions generated, %d specials, %d consts'
          % (mod, len(gen), len([p for p in ps if p[1] in SPECIALS]), len(cl)))

gen_module('sound', 'sound.h',
    'Sound Library Interface',
    ['chan = 1..16; { midi channel; "channel" is a reserved word }',
     'note = 1..128;',
     'instrument = 1..128;',
     'byte = 0..255;',
     'bytarr = packed array of byte;'],
    None)

gen_module('network', 'network.h',
    'Networking Library Interface',
    ['byte = 0..255;',
     'bytarr = packed array of byte;',
     'certptr = ^certfield;',
     'certfield = record',
     '',
     '   name:     pstring;  { name of field }',
     '   data:     pstring;  { content of field }',
     '   critical: boolean;  { is a critical X509 field }',
     '   fork:     certptr;  { sublist }',
     '   next:     certptr   { next entry in list }',
     '',
     'end;'],
    ['{ Window-file and certificate forms; wrappers hand-written in',
     '  network_support.c. opennet/waitnet bind the connection to the file',
     '  pair: reads from the far side on infile, writes to it on outfile. }',
     'procedure opennet(var infile: text; var outfile: text; addr: lcardinal; port: integer; secure: integer); external;',
     'procedure opennetv6(var infile: text; var outfile: text; addrh: lcardinal; addrl: lcardinal; port: integer; secure: integer); external;',
     'procedure waitnet(var infile: text; var outfile: text; port: integer; secure: integer); external;',
     'function certnet(var f: text; which: integer; var cert: string): integer; external;',
     'procedure certlistnet(var f: text; which: integer; var list: certptr); external;',
     'procedure certlistmsg(fn: integer; which: integer; var list: certptr); external;',
     'procedure certlistfree(var list: certptr); external;'])
