#!/usr/bin/env python3
# Generate source/exttables.pas, the external symbol tables for the
# interpreter's extlink module.
#
# The tables map a module's external symbols to routine numbers: the table
# index IS the routine number within the module (the services numbering is
# frozen by the execservices case bodies, so its order is read from the
# canonical list below; other modules are in module declaration order, the
# order their symbols appear in a compiled .p6).
#
# Symbols can be very long (an event record digest exceeds 1400 characters),
# far past a source line, and no two symbols share even a 40-character
# prefix, so the tables store an 80-character prefix and the lookup matches
# on the prefix.
#
# Usage: python3 tools/extgen/gen.py
# Reads:  tools/extgen/services.syms (frozen order, full symbols)
#         tools/extgen/terminal.syms (full symbols, declaration order)
# Writes: source/exttables.pas
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT  = os.path.join(ROOT, 'source', 'exttables.pas')

WIDTH = 80  # prefix width; collision-checked below

MODULES = ['services', 'terminal']

tables = {}
for m in MODULES:
    syms = [l.rstrip('\n') for l in open(os.path.join(HERE, m + '.syms'))
            if l.strip()]
    pre = [s[:WIDTH] for s in syms]
    dups = {p for p in pre if pre.count(p) > 1}
    if dups:
        raise SystemExit('%s: prefix collisions at width %d: %s'
                         % (m, WIDTH, sorted(dups)[:3]))
    tables[m] = pre

pas = []
pas.append('{'+'*'*78)
pas.append('')
pas.append('External symbol tables')
pas.append('')
pas.append('Maps the external symbols of each bound module to routine numbers')
pas.append('for the interpreter: the table index is the routine number within')
pas.append('the module. Symbols can far exceed a source line (an event record')
pas.append('digest passes 1400 characters), and no two symbols share even a')
pas.append('40 character prefix, so the entries hold an %d character prefix'
           % WIDTH)
pas.append('and the lookup matches on the prefix.')
pas.append('')
pas.append('Generated by tools/extgen/gen.py; do not edit by hand. The')
pas.append('services order is frozen (the execservices routine numbers');
pas.append('depend on it); other modules are in declaration order.')
pas.append('')
pas.append('*'*78+'}')
pas.append('')
pas.append('module exttables;')
pas.append('')
pas.append('const')
pas.append('')
pas.append('   symprefix = %d; { width of symbol prefix entries }' % WIDTH)
for m in MODULES:
    pas.append('   n%s = %d; { number of %s externals }'
               % (m, len(tables[m]), m))
pas.append('')
pas.append('type')
pas.append('')
pas.append('   syment = packed array [1..symprefix] of char;')
pas.append('')
pas.append('fixed')
pas.append('')
for m in MODULES:
    pas.append('   %stab: array [1..n%s] of syment = array' % (m, m))
    rows = []
    for s in tables[m]:
        rows.append("      '%s'" % (s.ljust(WIDTH).replace("'", "''")))
    pas.append(',\n'.join(rows))
    pas.append('   end;')
    pas.append('')
pas.append('begin')
pas.append('end.')
open(OUT, 'w').write('\n'.join(pas)+'\n')
print('exttables.pas: ' + ', '.join('%s=%d' % (m, len(tables[m]))
                                    for m in MODULES))
