{******************************************************************************

Networking Library Interface

Pascaline binding to the Ami network library. Generated by
tools/sndnetgen/gen.py from amitk/include/network.h; do not edit by hand.

******************************************************************************}

module network;

type
   byte = 0..255;
   bytarr = packed array of byte;
   certptr = ^certfield;
   certfield = record
   
      name:     pstring;  { name of field }
      data:     pstring;  { content of field }
      critical: boolean;  { is a critical X509 field }
      fork:     certptr;  { sublist }
      next:     certptr   { next entry in list }
   
   end;

procedure addrnet(view name: string; var addr: lcardinal); external;
procedure addrnetv6(view name: string; var addrh: lcardinal; var addrl: lcardinal); external;
function maxmsg(addr: lcardinal): integer; external;
function maxmsgv6(addrh: lcardinal; addrl: lcardinal): integer; external;
function relymsg(addr: lcardinal): integer; external;
function relymsgv6(addrh: lcardinal; addrl: lcardinal): integer; external;
function openmsg(addr: lcardinal; port: integer; secure: integer): integer; external;
function openmsgv6(addrh: lcardinal; addrl: lcardinal; port: integer; secure: integer): integer; external;
procedure wrmsg(fn: integer; view msg: bytarr); external;
function rdmsg(fn: integer; var msg: bytarr): integer; external;
procedure clsmsg(f: integer); external;
function waitmsg(port: integer; secure: integer): integer; external;
function certmsg(fn: integer; which: integer; var cert: string): integer; external;

{ Window-file and certificate forms; wrappers hand-written in
  network_support.c. opennet/waitnet bind the connection to the file
  pair: reads from the far side on infile, writes to it on outfile. }
procedure opennet(var infile: text; var outfile: text; addr: lcardinal; port: integer; secure: integer); external;
procedure opennetv6(var infile: text; var outfile: text; addrh: lcardinal; addrl: lcardinal; port: integer; secure: integer); external;
procedure waitnet(var infile: text; var outfile: text; port: integer; secure: integer); external;
function certnet(var f: text; which: integer; var cert: string): integer; external;
procedure certlistnet(var f: text; which: integer; var list: certptr); external;
procedure certlistmsg(fn: integer; which: integer; var list: certptr); external;
procedure certlistfree(var list: certptr); external;

begin
end.
