#
# File generated by P6 Pascal AMD64/gcc 64 bit code generator vs. 0.5.x
#

# Header file locations
inputoff = 0
outputoff = 2
prdoff = 4
prroff = 6
erroroff = 8
listoff = 10
commandoff = 12

# Logical file numbers for header files
inputfn = 1
outputfn = 2
prdfn = 3
prrfn = 4
errorfn = 5
listfn = 6
commandfn = 7

# Error codes
ValueOutOfRange                    = 0
ArrayLengthMatch                   = 1
CaseValueNotFound                  = 2
ZeroDivide                         = 3
InvalidOperand                     = 4
NilPointerDereference              = 5
RealOverflow                       = 6
RealUnderflow                      = 7
RealProcessingFault                = 8
TagValueNotActive                  = 9
TooManyFiles                       = 10
FileIsOpen                         = 11
FileAlreadyNamed                   = 12
FileNotOpen                        = 13
FileModeIncorrect                  = 14
InvalidFieldSpecification          = 15
InvalidRealNumber                  = 16
InvalidFractionSpecification       = 17
InvalidIntegerFormat               = 18
IntegerValueOverflow               = 19
InvalidRealFormat                  = 20
EndOfFile                          = 21
InvalidFilePosition                = 22
FilenameTooLong                    = 23
FileOpenFail                       = 24
FileSIzeFail                       = 25
FileCloseFail                      = 26
FileReadFail                       = 27
FileWriteFail                      = 28
FilePositionFail                   = 29
FileDeleteFail                     = 30
FileNameChangeFail                 = 31
SpaceAllocateFail                  = 32
SpaceReleaseFail                   = 33
SpaceAllocateNegative              = 34
CannotPerformSpecial               = 35
CommandLineTooLong                 = 36
ReadPastEOF                        = 37
FileTransferLengthZero             = 38
FileSizeTooLarge                   = 39
FilenameEmpty                      = 40
CannotOpenStandard                 = 41
TooManyTemporaryFiles              = 42
InputBufferOverflow                = 43
TooManyThreads                     = 44
CannotStartThread                  = 45
InvalidThreadHandle                = 46
CannotStopThread                   = 47
TooManyIntertaskLocks              = 48
InvalidLockHandle                  = 49
LockSequenceFail                   = 50
TooManySignals                     = 51
CannotCreateSignal                 = 52
InvalidSignalHandle                = 53
CannotDeleteSignal                 = 54
CannotSendSignal                   = 55
WaitForSignalFail                  = 56
FieldNotBlank                      = 57
ReadOnWriteOnlyFile                = 58
WriteOnReadOnlyFile                = 59
FileBufferVariableUndefined        = 60
NondecimalRadixOfNegative          = 61
InvalidArgumentToLn                = 62
InvalidArgumentToSqrt              = 63
CannotResetOrRewriteStandardFile   = 64
CannotResetWriteOnlyFile           = 65
CannotRewriteReadOnlyFile          = 66
SetElementOutOfRange               = 67
RealArgumentTooLarge               = 68
BooleanOperatorOfNegative          = 69
InvalidDivisorToMod                = 70
PackElementsOutOfBounds            = 71
UnpackElementsOutOfBounds          = 72
CannotResetClosedTempFile          = 73
ReadCharacterMismatch              = 74
UndefinedLocationAccess            = 75
FunctionNotImplemented             = 76
InvalidInISO7185Mode               = 77
HeapFormatInvalid                  = 78
DisposeOfUninitalizedPointer       = 79
DisposeOfNilPointer                = 80
BadPointerValue                    = 81
BlockAlreadyFreed                  = 82
InvalidStandardProcedureOrFunction = 83
InvalidInstruction                 = 84
NewDisposeTagsMismatch             = 85
PCOutOfRange                       = 86
StoreOverflow                      = 87
StackBalance                       = 88
SetInclusion                       = 89
UninitializedPointer               = 90
DereferenceOfNilPointer            = 91
PointerUsedAfterDispose            = 92
VariantNotActive                   = 93
InvalidCase                        = 94
SystemError                        = 95
ChangeToAllocatedTagfield          = 96
UnhandledException                 = 97
ProgramCodeAssertion               = 98
VarListEmpty                       = 99
ChangeToVarReferencedVariant       = 100
DisposeOfVarReferencedBlock        = 101
VarReferencedFileBufferModified    = 102
ContainerMismatch                  = 103
InvalidContainerLevel              = 104
DisposeOfWithReferencedBlock       = 105
WithBaseListEmpty                  = 106
ExternalsNotEnabled                = 107
MasterException                    = 108


# machine parameters
lendian     =       true /* endian mode */
intsize     =          8 /* size of integer */
intal       =          4 /* alignment of integer */
intdig      =         20 /* number of decimal digits in integer */
inthex      =         16 /* number of hex digits of integer */
realsize    =          8 /* size of real */
realal      =          4 /* alignment of real */
charsize    =          1 /* size of char */
charal      =          1 /* alignment of char */
boolsize    =          1 /* size of boolean */
boolal      =          1 /* alignment of boolean */
ptrsize     =          8 /* size of pointer */
adrsize     =          8 /* size of address */
adral       =          4 /* alignment of address */
setsize     =         32 /* size of set */
setal       =          1 /* alignment of set */
filesize    =          1 /* required runtime space for file (lfn) */
fileidsize  =          1 /* size of the lfn only */
exceptsize  =          1 /* size of exception variable */
exceptal    =          1 /* alignment of exception */
stackal     =          8 /* alignment of stack */
stackelsize =          8 /* stack element size */
maxsize     =         32 /* this is the largest type that can be on the stack */
heapal      =          4 /* alignment for each heap arena */
gbsal       =          4 /* globals area alignment */
sethigh     =        255 /* set highest value */
setlow      =          0 /* set lowest value */
ordmaxchar  =        255 /* character highest value */
ordminchar  =          0 /* character lowest value */
marksize    =         24 /* size of mark */
maxexp      =        308 /* maximum exponent of real */
nilval      =          1 /* value of nil */
maxint      = 9223372036854775807 /* value of maxint on target machine */
markep      =          8 /* (old) maximum frame size */
marksb      =         16 /* stack bottom */
market      =         24 /* current ep */

        .text
#
# Code section
#
#      0:      1: !
#      0:      2: ! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
#      0:      3: !
#      0:      4: p       /home/samiam/projects/pascal/pascal-p6/libs/source/services.pas
        .section .debug_line,"",@progbits
.Ldw_line_start:
        .text
        .file   "services.pas"
        .file   1 "/home/samiam/projects/pascal/pascal-p6/libs/source/services.pas"
#      0:      5: o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
#      0:      6: ! {******************************************************************************
#      0:      7: :1
        .loc 1 1 1
#      1:      8: ! *                                                                             *
#      1:      9: ! *                         EXTENDED FUNCTION LIBRARY                           *
#      1:     10: ! *                                                                             *
#      1:     11: ! *                           Copyright (C) 1996                                *
#      1:     12: ! *                                                                             *
#      1:     13: ! *                               S. A. MOORE                                   *
#      1:     14: ! *                                                                             *
#      1:     15: ! * Contains various system oriented library functions, including files,        *
#      1:     16: ! * directories, time, program execution, evironment, and random numbers.       *
#      1:     17: ! * Most or all of these procedures are implemented in a manner specific to     *
#      1:     18: ! * Windows 95/Windows NT 4.0 or later versions.                                *
#      1:     19: ! *                                                                             *
#      1:     20: ! ******************************************************************************}
#      1:     21: ! 
#      1:     22: ! module services;
#      1:     23: :2
        .loc 1 2 1
#      2:     24: :3
        .loc 1 3 1
#      3:     25: :4
        .loc 1 4 1
#      4:     26: :5
        .loc 1 5 1
#      5:     27: :6
        .loc 1 6 1
#      6:     28: :7
        .loc 1 7 1
#      7:     29: :8
        .loc 1 8 1
#      8:     30: :9
        .loc 1 9 1
#      9:     31: :10
        .loc 1 10 1
#     10:     32: :11
        .loc 1 11 1
#     11:     33: :12
        .loc 1 12 1
#     12:     34: :13
        .loc 1 13 1
#     13:     35: :14
        .loc 1 14 1
#     14:     36: :15
        .loc 1 15 1
#     15:     37: :16
        .loc 1 16 1
#     16:     38: !
#     16:     39: ! Module services
#     16:     40: !
#     16:     41: b       m       services
        .globl  services
        .type   services, @function
services:
        .cfi_startproc
# Align stack
        pushq   %rax
        .cfi_adjust_cfa_offset 8
# Set up default files
        movb    $inputfn,globals_start+inputoff(%rip)
        movb    $outputfn,globals_start+outputoff(%rip)
        movb    $prdfn,globals_start+prdoff(%rip)
        movb    $prrfn,globals_start+prroff(%rip)
        movb    $errorfn,globals_start+erroroff(%rip)
        movb    $listfn,globals_start+listoff(%rip)
        movb    $commandfn,globals_start+commandoff(%rip)
# Call startup code
        call    1f
        popq    %rax
        .cfi_adjust_cfa_offset -8
        sub     %rax,%rax
        ret
        .cfi_endproc
1:
#     16:     42:         sfr     l services.6            ! Set function result
#     16:     43: l services.6=0
services.6 = 0
#     16:     44:         cup     l services.3 0           ! Call user procedure
# assigning:      16:     44:  12: cup  0 rs: [] ~rf: []
# assigning~:     16:     44:  12: cup  0 rs: [] ~rf: []
#    expr:
#      16:     44:  12: cup  0 rs: []
#  call start:
#      16:     42: 245: sfr  0 rs: []
# generating:      16:     44:  12: cup  0 rs: []
# generating:      16:     42: 245: sfr  0 rs: []
        movq    %rsp,%rax               # copy stack pointer
        subq    $services.6,%rax        # set new stack depth
1:              
        cmpq    %rax,%rsp               # check done
        jbe     2f                      # skip if below stack
        pushq   $0                      # clear stack
        jmp     1b                      # loop
2:              
# generating~:     16:     42: 245: sfr  0 rs: []
        call    services.3              # call user procedure
# generating~:     16:     44:  12: cup  0 rs: []
#     16:     45:         cal     l services.5            ! Call initializer code strip
# generating:  21: cal       
        call    services.5              # call routine/initializer
#     16:     46:         sfr     l services.6            ! Set function result
#     16:     47:         cup     l services.4 0           ! Call user procedure
# assigning:      16:     47:  12: cup  0 rs: [] ~rf: []
# assigning~:     16:     47:  12: cup  0 rs: [] ~rf: []
#    expr:
#      16:     47:  12: cup  0 rs: []
#  call start:
#      16:     46: 245: sfr  0 rs: []
# generating:      16:     47:  12: cup  0 rs: []
# generating:      16:     46: 245: sfr  0 rs: []
# generating~:     16:     46: 245: sfr  0 rs: []
        call    services.4              # call user procedure
# generating~:     16:     47:  12: cup  0 rs: []
#     16:     48:         ret                             ! Return code strip
        ret      
#     16:     49: ! 
#     16:     50: ! type 
#     16:     51: :17
        .loc 1 17 1
#     17:     52: :18
        .loc 1 18 1
#     18:     53: ! 
#     18:     54: !    { attributes }
#     18:     55: !    attribute = (atexec,  { is an executable file type }
#     18:     56: :19
        .loc 1 19 1
#     19:     57: :20
        .loc 1 20 1
#     20:     58: :21
        .loc 1 21 1
#     21:     59: !                 atarc,   { has been archived since last modification }
#     21:     60: :22
        .loc 1 22 1
#     22:     61: !                 atsys,   { is a system special file }
#     22:     62: :23
        .loc 1 23 1
#     23:     63: !                 atdir,   { is a directory special file }
#     23:     64: :24
        .loc 1 24 1
#     24:     65: !                 atloop); { contains heriarchy loop }
#     24:     66: :25
        .loc 1 25 1
#     25:     67: !    attrset = set of attribute; { attributes in a set }
#     25:     68: :26
        .loc 1 26 1
#     26:     69: !    { permissions }
#     26:     70: !    permission = (pmread,  { may be read }
#     26:     71: :27
        .loc 1 27 1
#     27:     72: :28
        .loc 1 28 1
#     28:     73: !                  pmwrite, { may be written }
#     28:     74: :29
        .loc 1 29 1
#     29:     75: !                  pmexec,  { may be executed }
#     29:     76: :30
        .loc 1 30 1
#     30:     77: !                  pmdel,   { may be deleted }
#     30:     78: :31
        .loc 1 31 1
#     31:     79: !                  pmvis,   { may be seen in directory listings }
#     31:     80: :32
        .loc 1 32 1
#     32:     81: !                  pmcopy,  { may be copied }
#     32:     82: :33
        .loc 1 33 1
#     33:     83: !                  pmren);  { may be renamed/moved }
#     33:     84: :34
        .loc 1 34 1
#     34:     85: !    permset = set of permission; { permissions in a set }
#     34:     86: :35
        .loc 1 35 1
#     35:     87: !    { standard directory format }
#     35:     88: !    filptr = ^filrec; { pointer to file records }
#     35:     89: :36
        .loc 1 36 1
#     36:     90: :37
        .loc 1 37 1
#     37:     91: !    filrec = record
#     37:     92: :38
        .loc 1 38 1
#     38:     93: ! 
#     38:     94: !       name:   pstring; { name of file }
#     38:     95: :39
        .loc 1 39 1
#     39:     96: :40
        .loc 1 40 1
#     40:     97: !       size:   integer; { size of file }
#     40:     98: :41
        .loc 1 41 1
#     41:     99: !       alloc:  integer; { allocation of file }
#     41:    100: :42
        .loc 1 42 1
#     42:    101: !       attr:   attrset; { attributes }
#     42:    102: :43
        .loc 1 43 1
#     43:    103: !       create: integer; { time of creation }
#     43:    104: :44
        .loc 1 44 1
#     44:    105: !       modify: integer; { time of last modification }
#     44:    106: :45
        .loc 1 45 1
#     45:    107: !       access: integer; { time of last access }
#     45:    108: :46
        .loc 1 46 1
#     46:    109: !       backup: integer; { time of last backup }
#     46:    110: :47
        .loc 1 47 1
#     47:    111: !       user:   permset; { user permissions }
#     47:    112: :48
        .loc 1 48 1
#     48:    113: !       group:  permset; { group permissions }
#     48:    114: :49
        .loc 1 49 1
#     49:    115: !       other:  permset; { other permissions }
#     49:    116: :50
        .loc 1 50 1
#     50:    117: !       next:   filptr   { next entry in list }
#     50:    118: :51
        .loc 1 51 1
#     51:    119: ! 
#     51:    120: !    end;
#     51:    121: :52
        .loc 1 52 1
#     52:    122: :53
        .loc 1 53 1
#     53:    123: !    { environment strings }
#     53:    124: !    envptr = ^envrec; { pointer to environment record }
#     53:    125: :54
        .loc 1 54 1
#     54:    126: :55
        .loc 1 55 1
#     55:    127: !    envrec = packed record
#     55:    128: :56
        .loc 1 56 1
#     56:    129: ! 
#     56:    130: !       name: pstring; { name of string }
#     56:    131: :57
        .loc 1 57 1
#     57:    132: :58
        .loc 1 58 1
#     58:    133: !       data: pstring; { data in string }
#     58:    134: :59
        .loc 1 59 1
#     59:    135: !       next: envptr { next entry in list }
#     59:    136: :60
        .loc 1 60 1
#     60:    137: ! 
#     60:    138: !    end;
#     60:    139: :61
        .loc 1 61 1
#     61:    140: :62
        .loc 1 62 1
#     62:    141: ! 
#     62:    142: ! procedure list(view f: string; var l: filptr); external;
#     62:    143: :63
        .loc 1 63 1
#     63:    144: :64
        .loc 1 64 1
#     64:    145: ! overload procedure list(view f: pstring; var  l: filptr); external;
#     64:    146: z 0 0 services.list@p_vc_pr(name:0:pvc,size:8:i,alloc:16:i,attr:24:sx(atexec,atarc,atsys,atdir,atloop),create:56:i,modify:64:i,access:72:i,backup:80:i,user:88:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),group:120:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),other:152:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),next:184:p2)
#     64:    147: :65
        .loc 1 65 1
#     65:    148: ! procedure times(out s: string; t: integer); external;
#     65:    149: z 0 0 services.list@p_pvc_pr(name:0:pvc,size:8:i,alloc:16:i,attr:24:sx(atexec,atarc,atsys,atdir,atloop),create:56:i,modify:64:i,access:72:i,backup:80:i,user:88:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),group:120:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),other:152:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),next:184:p2)
#     65:    150: :66
        .loc 1 66 1
#     66:    151: ! overload function times(t: integer): pstring; external;
#     66:    152: z 0 0 services.times@p_vc_i
#     66:    153: :67
        .loc 1 67 1
#     67:    154: ! procedure dates(out s: string; t: integer); external;
#     67:    155: z 0 0 services.times@f_i
#     67:    156: :68
        .loc 1 68 1
#     68:    157: ! overload function dates(t: integer): pstring; external;
#     68:    158: z 0 0 services.dates@p_vc_i
#     68:    159: :69
        .loc 1 69 1
#     69:    160: ! procedure writetime(var f: text; t: integer); external;
#     69:    161: z 0 0 services.dates@f_i
#     69:    162: :70
        .loc 1 70 1
#     70:    163: ! overload procedure writetime(t: integer); external;
#     70:    164: z 0 0 services.writetime@p_fc_i
#     70:    165: :71
        .loc 1 71 1
#     71:    166: ! procedure writedate(var f: text; t: integer); external;
#     71:    167: z 0 0 services.writetime@p_i
#     71:    168: :72
        .loc 1 72 1
#     72:    169: ! overload procedure writedate(t: integer); external;
#     72:    170: z 0 0 services.writedate@p_fc_i
#     72:    171: :73
        .loc 1 73 1
#     73:    172: ! function time: integer; external;
#     73:    173: z 0 0 services.writedate@p_i
#     73:    174: :74
        .loc 1 74 1
#     74:    175: ! function local(t: integer): integer; external;
#     74:    176: z 0 0 services.time@f
#     74:    177: :75
        .loc 1 75 1
#     75:    178: ! function clock: integer; external;
#     75:    179: z 0 0 services.local@f_i
#     75:    180: :76
        .loc 1 76 1
#     76:    181: ! function elapsed(r: integer): integer; external;
#     76:    182: z 0 0 services.clock@f
#     76:    183: :77
        .loc 1 77 1
#     77:    184: ! function validfile(view s: string): boolean; external;
#     77:    185: z 0 0 services.elapsed@f_i
#     77:    186: :78
        .loc 1 78 1
#     78:    187: ! overload function validfile(view s: pstring): boolean; external;
#     78:    188: z 0 0 services.validfile@f_vc
#     78:    189: :79
        .loc 1 79 1
#     79:    190: ! function validpath(view s: string): boolean; external;
#     79:    191: z 0 0 services.validfile@f_pvc
#     79:    192: :80
        .loc 1 80 1
#     80:    193: ! overload function validpath(view s: pstring): boolean; external;
#     80:    194: z 0 0 services.validpath@f_vc
#     80:    195: :81
        .loc 1 81 1
#     81:    196: ! function wild(view s: string): boolean; external;
#     81:    197: z 0 0 services.validpath@f_pvc
#     81:    198: :82
        .loc 1 82 1
#     82:    199: ! overload function wild(view s: pstring): boolean; external;
#     82:    200: z 0 0 services.wild@f_vc
#     82:    201: :83
        .loc 1 83 1
#     83:    202: ! procedure getenv(view ls: string; out ds: string); external;
#     83:    203: z 0 0 services.wild@f_pvc
#     83:    204: :84
        .loc 1 84 1
#     84:    205: ! overload function getenv(view ls: string): pstring; external;
#     84:    206: z 0 0 services.getenv@p_vc_vc
#     84:    207: :85
        .loc 1 85 1
#     85:    208: ! procedure setenv(view sn, sd: string); external;
#     85:    209: z 0 0 services.getenv@f_vc
#     85:    210: :86
        .loc 1 86 1
#     86:    211: ! overload procedure setenv(sn: pstring; view sd: string); external;
#     86:    212: z 0 0 services.setenv@p_vc_vc
#     86:    213: :87
        .loc 1 87 1
#     87:    214: ! overload procedure setenv(view sn: string; sd: pstring); external;
#     87:    215: z 0 0 services.setenv@p_pvc_vc
#     87:    216: :88
        .loc 1 88 1
#     88:    217: ! overload procedure setenv(sn, sd: pstring); external;
#     88:    218: z 0 0 services.setenv@p_vc_pvc
#     88:    219: :89
        .loc 1 89 1
#     89:    220: ! procedure allenv(var el: envptr); external;
#     89:    221: z 0 0 services.setenv@p_pvc_pvc
#     89:    222: :90
        .loc 1 90 1
#     90:    223: ! procedure remenv(view sn: string); external;
#     90:    224: z 0 0 services.allenv@p_pr(name:0:pvc,data:8:p12,next:16:p2)
#     90:    225: :91
        .loc 1 91 1
#     91:    226: ! overload procedure remenv(view sn: pstring); external;
#     91:    227: z 0 0 services.remenv@p_vc
#     91:    228: :92
        .loc 1 92 1
#     92:    229: ! procedure exec(view cmd: string); external;
#     92:    230: z 0 0 services.remenv@p_pvc
#     92:    231: :93
        .loc 1 93 1
#     93:    232: ! overload procedure exec(cmd: pstring); external;
#     93:    233: z 0 0 services.exec@p_vc
#     93:    234: :94
        .loc 1 94 1
#     94:    235: ! procedure exece(view cmd: string; el: envptr); external;
#     94:    236: z 0 0 services.exec@p_pvc
#     94:    237: :95
        .loc 1 95 1
#     95:    238: ! overload procedure exece(cmd: pstring; el: envptr); external;
#     95:    239: z 0 0 services.exece@p_vc_pr(name:0:pvc,data:8:p12,next:16:p2)
#     95:    240: :96
        .loc 1 96 1
#     96:    241: ! procedure execw(view cmd: string; out e: integer); external;
#     96:    242: z 0 0 services.exece@p_pvc_pr(name:0:pvc,data:8:p12,next:16:p2)
#     96:    243: :97
        .loc 1 97 1
#     97:    244: ! overload procedure execw(cmd: pstring; out e: integer); external;
#     97:    245: z 0 0 services.execw@p_vc_i
#     97:    246: :98
        .loc 1 98 1
#     98:    247: ! procedure execew(view cmd: string; el: envptr; out e: integer); external;
#     98:    248: z 0 0 services.execw@p_pvc_i
#     98:    249: :99
        .loc 1 99 1
#     99:    250: ! overload procedure execew(cmd: pstring; el: envptr; out e: integer); external;
#     99:    251: z 0 0 services.execew@p_vc_pr(name:0:pvc,data:8:p12,next:16:p2)_i
#     99:    252: :100
        .loc 1 100 1
#    100:    253: ! procedure getcur(out fn: string); external;
#    100:    254: z 0 0 services.execew@p_pvc_pr(name:0:pvc,data:8:p12,next:16:p2)_i
#    100:    255: :101
        .loc 1 101 1
#    101:    256: ! overload function getcur: pstring; external;
#    101:    257: z 0 0 services.getcur@p_vc
#    101:    258: :102
        .loc 1 102 1
#    102:    259: ! procedure setcur(view fn: string); external;
#    102:    260: z 0 0 services.getcur@f
#    102:    261: :103
        .loc 1 103 1
#    103:    262: ! overload procedure setcur(fn: pstring); external;
#    103:    263: z 0 0 services.setcur@p_vc
#    103:    264: :104
        .loc 1 104 1
#    104:    265: ! procedure brknam(view fn: string; out p, n, e: string); external;
#    104:    266: z 0 0 services.setcur@p_pvc
#    104:    267: :105
        .loc 1 105 1
#    105:    268: ! overload procedure brknam(view fn: string; out p, n, e: pstring); external;
#    105:    269: z 0 0 services.brknam@p_vc_vc_vc_vc
#    105:    270: :106
        .loc 1 106 1
#    106:    271: ! overload procedure brknam(fn: pstring; out p, n, e: pstring); external;
#    106:    272: z 0 0 services.brknam@p_vc_pvc_pvc_pvc
#    106:    273: :107
        .loc 1 107 1
#    107:    274: ! procedure maknam(out fn: string; view p, n, e: string); external;
#    107:    275: z 0 0 services.brknam@p_pvc_pvc_pvc_pvc
#    107:    276: :108
        .loc 1 108 1
#    108:    277: ! overload function maknam(view p, n, e: string): pstring; external;
#    108:    278: z 0 0 services.maknam@p_vc_vc_vc_vc
#    108:    279: :109
        .loc 1 109 1
#    109:    280: ! overload function maknam(view p: string; view n: string; e: pstring): pstring; external;
#    109:    281: z 0 0 services.maknam@f_vc_vc_vc
#    109:    282: :110
        .loc 1 110 1
#    110:    283: ! overload function maknam(view p: string; n: pstring; view e: string): pstring; external;
#    110:    284: z 0 0 services.maknam@f_vc_vc_pvc
#    110:    285: :111
        .loc 1 111 1
#    111:    286: ! overload function maknam(view p: string; n: pstring; e: pstring): pstring; external;
#    111:    287: z 0 0 services.maknam@f_vc_pvc_vc
#    111:    288: :112
        .loc 1 112 1
#    112:    289: ! overload function maknam(p: pstring; view n: string; view e: string): pstring; external;
#    112:    290: z 0 0 services.maknam@f_vc_pvc_pvc
#    112:    291: :113
        .loc 1 113 1
#    113:    292: ! overload function maknam(p: pstring; view n: string; e: pstring): pstring; external;
#    113:    293: z 0 0 services.maknam@f_pvc_vc_vc
#    113:    294: :114
        .loc 1 114 1
#    114:    295: ! overload function maknam(p: pstring; n: pstring; view e: string): pstring; external;
#    114:    296: z 0 0 services.maknam@f_pvc_vc_pvc
#    114:    297: :115
        .loc 1 115 1
#    115:    298: ! overload function maknam(p: pstring; n: pstring; e: pstring): pstring; external;
#    115:    299: z 0 0 services.maknam@f_pvc_pvc_vc
#    115:    300: :116
        .loc 1 116 1
#    116:    301: ! procedure fulnam(var fn: string); external;
#    116:    302: z 0 0 services.maknam@f_pvc_pvc_pvc
#    116:    303: :117
        .loc 1 117 1
#    117:    304: ! overload function fulnam(view fn: string): pstring; external;
#    117:    305: z 0 0 services.fulnam@p_vc
#    117:    306: :118
        .loc 1 118 1
#    118:    307: ! procedure getpgm(out p: string); external;
#    118:    308: z 0 0 services.fulnam@f_vc
#    118:    309: :119
        .loc 1 119 1
#    119:    310: ! overload function getpgm: pstring; external;
#    119:    311: z 0 0 services.getpgm@p_vc
#    119:    312: :120
        .loc 1 120 1
#    120:    313: ! procedure getusr(out fn: string); external;
#    120:    314: z 0 0 services.getpgm@f
#    120:    315: :121
        .loc 1 121 1
#    121:    316: ! overload function getusr: pstring; external;
#    121:    317: z 0 0 services.getusr@p_vc
#    121:    318: :122
        .loc 1 122 1
#    122:    319: ! procedure setatr(view fn: string; a: attrset); external;
#    122:    320: z 0 0 services.getusr@f
#    122:    321: :123
        .loc 1 123 1
#    123:    322: ! overload procedure setatr(fn: pstring; a: attrset); external;
#    123:    323: z 0 0 services.setatr@p_vc_sx(atexec,atarc,atsys,atdir,atloop)
#    123:    324: :124
        .loc 1 124 1
#    124:    325: ! procedure resatr(view fn: string; a: attrset); external;
#    124:    326: z 0 0 services.setatr@p_pvc_sx(atexec,atarc,atsys,atdir,atloop)
#    124:    327: :125
        .loc 1 125 1
#    125:    328: ! overload procedure resatr(fn: pstring; a: attrset); external;
#    125:    329: z 0 0 services.resatr@p_vc_sx(atexec,atarc,atsys,atdir,atloop)
#    125:    330: :126
        .loc 1 126 1
#    126:    331: ! procedure bakupd(view fn: string); external;
#    126:    332: z 0 0 services.resatr@p_pvc_sx(atexec,atarc,atsys,atdir,atloop)
#    126:    333: :127
        .loc 1 127 1
#    127:    334: ! overload procedure bakupd(fn: pstring); external;
#    127:    335: z 0 0 services.bakupd@p_vc
#    127:    336: :128
        .loc 1 128 1
#    128:    337: ! procedure setuper(view fn: string; p: permset); external;
#    128:    338: z 0 0 services.bakupd@p_pvc
#    128:    339: :129
        .loc 1 129 1
#    129:    340: ! overload procedure setuper(fn: pstring; p: permset); external;
#    129:    341: z 0 0 services.setuper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    129:    342: :130
        .loc 1 130 1
#    130:    343: ! procedure resuper(view fn: string; p: permset); external;
#    130:    344: z 0 0 services.setuper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    130:    345: :131
        .loc 1 131 1
#    131:    346: ! overload procedure resuper(fn: pstring; p: permset); external;
#    131:    347: z 0 0 services.resuper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    131:    348: :132
        .loc 1 132 1
#    132:    349: ! procedure setgper(view fn: string; p: permset); external;
#    132:    350: z 0 0 services.resuper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    132:    351: :133
        .loc 1 133 1
#    133:    352: ! overload procedure setgper(fn: pstring; p: permset); external;
#    133:    353: z 0 0 services.setgper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    133:    354: :134
        .loc 1 134 1
#    134:    355: ! procedure resgper(view fn: string; p: permset); external;
#    134:    356: z 0 0 services.setgper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    134:    357: :135
        .loc 1 135 1
#    135:    358: ! overload procedure resgper(fn: pstring; p: permset); external;
#    135:    359: z 0 0 services.resgper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    135:    360: :136
        .loc 1 136 1
#    136:    361: ! procedure setoper(view fn: string; p: permset); external;
#    136:    362: z 0 0 services.resgper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    136:    363: :137
        .loc 1 137 1
#    137:    364: ! overload procedure setoper(fn: pstring; p: permset); external;
#    137:    365: z 0 0 services.setoper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    137:    366: :138
        .loc 1 138 1
#    138:    367: ! procedure resoper(view fn: string; p: permset); external;
#    138:    368: z 0 0 services.setoper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    138:    369: :139
        .loc 1 139 1
#    139:    370: ! overload procedure resoper(fn: pstring; p: permset); external;
#    139:    371: z 0 0 services.resoper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    139:    372: :140
        .loc 1 140 1
#    140:    373: ! procedure seterr(e: integer); external;
#    140:    374: z 0 0 services.resoper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#    140:    375: :141
        .loc 1 141 1
#    141:    376: ! procedure makpth(view fn: string); external;
#    141:    377: z 0 0 services.seterr@p_i
#    141:    378: :142
        .loc 1 142 1
#    142:    379: ! overload procedure makpth(fn: pstring); external;
#    142:    380: z 0 0 services.makpth@p_vc
#    142:    381: :143
        .loc 1 143 1
#    143:    382: ! procedure rempth(view fn: string); external;
#    143:    383: z 0 0 services.makpth@p_pvc
#    143:    384: :144
        .loc 1 144 1
#    144:    385: ! overload procedure rempth(fn: pstring); external;
#    144:    386: z 0 0 services.rempth@p_vc
#    144:    387: :145
        .loc 1 145 1
#    145:    388: ! procedure filchr(out fc: schar); external;
#    145:    389: z 0 0 services.rempth@p_pvc
#    145:    390: :146
        .loc 1 146 1
#    146:    391: ! function optchr: char; external;
#    146:    392: z 0 0 services.filchr@p_sc
#    146:    393: :147
        .loc 1 147 1
#    147:    394: ! function pthchr: char; external;
#    147:    395: z 0 0 services.optchr@f
#    147:    396: :148
        .loc 1 148 1
#    148:    397: ! function latitude: integer; external;
#    148:    398: z 0 0 services.pthchr@f
#    148:    399: :149
        .loc 1 149 1
#    149:    400: ! function longitude: integer; external;
#    149:    401: z 0 0 services.latitude@f
#    149:    402: :150
        .loc 1 150 1
#    150:    403: ! function altitude: integer; external;
#    150:    404: z 0 0 services.longitude@f
#    150:    405: :151
        .loc 1 151 1
#    151:    406: ! function country: integer; external;
#    151:    407: z 0 0 services.altitude@f
#    151:    408: :152
        .loc 1 152 1
#    152:    409: ! procedure countrys(out s: string; c: integer); external;
#    152:    410: z 0 0 services.country@f
#    152:    411: :153
        .loc 1 153 1
#    153:    412: ! function timezone: integer; external;
#    153:    413: z 0 0 services.countrys@p_vc_i
#    153:    414: :154
        .loc 1 154 1
#    154:    415: ! function daysave: boolean; external;
#    154:    416: z 0 0 services.timezone@f
#    154:    417: :155
        .loc 1 155 1
#    155:    418: ! function time24hour: boolean; external;
#    155:    419: z 0 0 services.daysave@f
#    155:    420: :156
        .loc 1 156 1
#    156:    421: ! function language: integer; external;
#    156:    422: z 0 0 services.time24hour@f
#    156:    423: :157
        .loc 1 157 1
#    157:    424: ! procedure languages(out s: string; l: integer);  external;
#    157:    425: z 0 0 services.language@f
#    157:    426: :158
        .loc 1 158 1
#    158:    427: ! function decimal: char; external;
#    158:    428: z 0 0 services.languages@p_vc_i
#    158:    429: :159
        .loc 1 159 1
#    159:    430: ! function numbersep: char; external;
#    159:    431: z 0 0 services.decimal@f
#    159:    432: :160
        .loc 1 160 1
#    160:    433: ! function timeorder: integer; external;
#    160:    434: z 0 0 services.numbersep@f
#    160:    435: :161
        .loc 1 161 1
#    161:    436: ! function dateorder: integer; external;
#    161:    437: z 0 0 services.timeorder@f
#    161:    438: :162
        .loc 1 162 1
#    162:    439: ! function datesep: char; external;
#    162:    440: z 0 0 services.dateorder@f
#    162:    441: :163
        .loc 1 163 1
#    163:    442: ! function timesep: char; external;
#    163:    443: z 0 0 services.datesep@f
#    163:    444: :164
        .loc 1 164 1
#    164:    445: ! function currchr: char; external;
#    164:    446: z 0 0 services.timesep@f
#    164:    447: :165
        .loc 1 165 1
#    165:    448: ! 
#    165:    449: ! begin
#    165:    450: z 0 0 services.currchr@f
#    165:    451: l services.3
services.3:
#    165:    452: :166
        .loc 1 166 1
#    166:    453: :167
        .loc 1 167 1
#    167:    454: :167
        .loc 1 167 1
#    167:    455:         mst     0 l services.109 l services.110 ! Mark(frame) stack
        .cfi_startproc
# generating:  11: mst       
        pushq   $0                      # place current ep
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place bottom of stack
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place previous ep
        .cfi_adjust_cfa_offset 8
        enterq  $0,$1                   # enter frame
        .cfi_def_cfa rbp, 40
        .cfi_offset rbp, -40
        pushq   %r9                     # save int param reg 6
        pushq   %r8                     # save int param reg 5
        pushq   %rcx                    # save int param reg 4
        pushq   %rdx                    # save int param reg 3
        pushq   %rsi                    # save int param reg 2
        pushq   %rdi                    # save int param reg 1
        pushq   %rax                    # save function result
        subq    $48,%rsp                # allocate float param save area
        movsd   %xmm0,40(%rsp)          # save float param reg 1
        movsd   %xmm1,32(%rsp)          # save float param reg 2
        movsd   %xmm2,24(%rsp)          # save float param reg 3
        movsd   %xmm3,16(%rsp)          # save float param reg 4
        movsd   %xmm4,8(%rsp)           # save float param reg 5
        movsd   %xmm5,0(%rsp)           # save float param reg 6
        movq    %rsp,%rax               # copy sp
        subq    $services.109+services$_tmpspc,%rax # find sp-locals
1:              
        cmpq    %rax,%rsp               # check have reached stack
        je      2f                      # skip if so
        pushq   $0                      # push 0 word for locals
        jmp     1b                      # loop
2:              
        movq    %rsp,16(%rbp)           # set bottom of stack
        andq    $0xfffffffffffffff0,%rsp # align stack
        pushq   %rbx                    # save protected registers and keep aligned
        pushq   %r12
        pushq   %r13
        pushq   %r14
        pushq   %r15
        pushq   %r15                    # second push aligns
#    167:    456: ! end.
#    167:    457: :168
        .loc 1 168 1 prologue_end
#    168:    458:         retp    0                       ! Return from procedure/function(t)
# generating:  14: retp      
        popq    %r15                    # undo alignment push
        popq    %r15                    # restore protected registers
        popq    %r14
        popq    %r13
        popq    %r12
        popq    %rbx
        leave                           # undo frame
        .cfi_restore rbp
        .cfi_def_cfa rsp, 32
        addq    $24,%rsp                # remove frame data
        .cfi_def_cfa rsp, 8
        popq    %rcx                    # get return address
        addq    $0,%rsp                 # remove caller parameters
        pushq   %rcx                    # replace return address
        ret                             # return to caller
        .cfi_endproc
.Lfnend_1:
services$_tmpspc = 0
#    168:    459: l services.109=0
services.109 = 0
#    168:    460: l services.110=0
services.110 = 0
#    168:    461: l services.4
services.4:
#    168:    462:         mst     0 l services.112 l services.113 ! Mark(frame) stack
        .cfi_startproc
# generating:  11: mst       
        pushq   $0                      # place current ep
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place bottom of stack
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place previous ep
        .cfi_adjust_cfa_offset 8
        enterq  $0,$1                   # enter frame
        .cfi_def_cfa rbp, 40
        .cfi_offset rbp, -40
        pushq   %r9                     # save int param reg 6
        pushq   %r8                     # save int param reg 5
        pushq   %rcx                    # save int param reg 4
        pushq   %rdx                    # save int param reg 3
        pushq   %rsi                    # save int param reg 2
        pushq   %rdi                    # save int param reg 1
        pushq   %rax                    # save function result
        subq    $48,%rsp                # allocate float param save area
        movsd   %xmm0,40(%rsp)          # save float param reg 1
        movsd   %xmm1,32(%rsp)          # save float param reg 2
        movsd   %xmm2,24(%rsp)          # save float param reg 3
        movsd   %xmm3,16(%rsp)          # save float param reg 4
        movsd   %xmm4,8(%rsp)           # save float param reg 5
        movsd   %xmm5,0(%rsp)           # save float param reg 6
        movq    %rsp,%rax               # copy sp
        subq    $services.112+services$_tmpspc,%rax # find sp-locals
1:              
        cmpq    %rax,%rsp               # check have reached stack
        je      2f                      # skip if so
        pushq   $0                      # push 0 word for locals
        jmp     1b                      # loop
2:              
        movq    %rsp,16(%rbp)           # set bottom of stack
        andq    $0xfffffffffffffff0,%rsp # align stack
        pushq   %rbx                    # save protected registers and keep aligned
        pushq   %r12
        pushq   %r13
        pushq   %r14
        pushq   %r15
        pushq   %r15                    # second push aligns
#    168:    463:         retp    0                       ! Return from procedure/function(t)
# generating:  14: retp      
        popq    %r15                    # undo alignment push
        popq    %r15                    # restore protected registers
        popq    %r14
        popq    %r13
        popq    %r12
        popq    %rbx
        leave                           # undo frame
        .cfi_restore rbp
        .cfi_def_cfa rsp, 32
        addq    $24,%rsp                # remove frame data
        .cfi_def_cfa rsp, 8
        popq    %rcx                    # get return address
        addq    $0,%rsp                 # remove caller parameters
        pushq   %rcx                    # replace return address
        ret                             # return to caller
        .cfi_endproc
.Lfnend_2:
services$_tmpspc = 0
#    168:    464: l services.112=0
services.112 = 0
#    168:    465: l services.113=0
services.113 = 0
#    168:    466: l services.5
services.5:
#    168:    467: g 89
#    168:    468: e m
#    168:    469: f       0
#
# Constants section
#
        jmp     1f
modnam:
        .string  "services"
real_zero:
        .double  0.0
real_int_max:
        .double  9223372036854775807
real_int_min:
        .double  -9223372036854775807
1:
        .bss
#
# Globals section
#
globals_start:
        .zero 89

#
# DWARF debug info
#
        .section .debug_info,"",@progbits
.Ldw_info_start:
        .long   .Ldw_info_end - .Ldw_info_hdr /* unit length */
.Ldw_info_hdr:
        .short  4 /* DWARF version */
        .long   .Ldw_abbrev_start /* debug_abbrev offset */
        .byte   8 /* address size */
        .uleb128 1 /* DW_TAG_compile_unit */
        .long   .Ldw5
        .short  2 /* language */
        .long   .Ldw6
        .quad   services /* DW_AT_low_pc */
        .quad   .Lfnend_2 /* DW_AT_high_pc */
        .long   .Ldw_line_start /* DW_AT_stmt_list */
.Ldw1:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw7
        .byte   5 /* DW_ATE_signed */
        .byte   8 /* byte_size */
.Ldw2:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw8
        .byte   2 /* DW_ATE_boolean */
        .byte   1 /* byte_size */
.Ldw3:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw9
        .byte   8 /* DW_ATE_unsigned_char */
        .byte   1 /* byte_size */
.Ldw4:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw10
        .byte   4 /* DW_ATE_float */
        .byte   8 /* byte_size */
        .uleb128 18 /* DW_TAG_subprogram */
        .long   .Ldw6
        .uleb128 1 /* frame_base length */
        .byte   86 /* DW_OP_reg 6 */
        .quad   services /* DW_AT_low_pc */
        .quad   .Lfnend_2 /* DW_AT_high_pc */
        .byte   0 /* end compile unit children */
.Ldw_info_end:

#
# DWARF abbreviation table
#
        .section .debug_abbrev,"",@progbits
.Ldw_abbrev_start:
        .uleb128 1 /* abbreviation code */
        .uleb128 17 /* tag */
        .byte   1 /* children */
        .uleb128 37
        .uleb128 14
        .uleb128 19
        .uleb128 5
        .uleb128 3
        .uleb128 14
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .uleb128 16
        .uleb128 23
        .byte   0
        .byte   0
        .uleb128 2 /* abbreviation code */
        .uleb128 36 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 62
        .uleb128 11
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 3 /* abbreviation code */
        .uleb128 46 /* tag */
        .byte   1 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 64
        .uleb128 24
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .byte   0
        .byte   0
        .uleb128 4 /* abbreviation code */
        .uleb128 52 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 5 /* abbreviation code */
        .uleb128 52 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 6 /* abbreviation code */
        .uleb128 5 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 7 /* abbreviation code */
        .uleb128 15 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 8 /* abbreviation code */
        .uleb128 1 /* tag */
        .byte   1 /* children */
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 9 /* abbreviation code */
        .uleb128 33 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 34
        .uleb128 13
        .uleb128 47
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 10 /* abbreviation code */
        .uleb128 19 /* tag */
        .byte   1 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 11
        .uleb128 15
        .byte   0
        .byte   0
        .uleb128 11 /* abbreviation code */
        .uleb128 13 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 56
        .uleb128 15
        .byte   0
        .byte   0
        .uleb128 12 /* abbreviation code */
        .uleb128 4 /* tag */
        .byte   1 /* children */
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 13 /* abbreviation code */
        .uleb128 40 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 28
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 14 /* abbreviation code */
        .uleb128 32 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 15 /* abbreviation code */
        .uleb128 41 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 16 /* abbreviation code */
        .uleb128 51 /* tag */
        .byte   1 /* children */
        .uleb128 21
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 17 /* abbreviation code */
        .uleb128 25 /* tag */
        .byte   1 /* children */
        .uleb128 22
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 18 /* abbreviation code */
        .uleb128 46 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 64
        .uleb128 24
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .byte   0
        .byte   0
        .uleb128 19 /* abbreviation code */
        .uleb128 59 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .byte   0
        .byte   0
        .uleb128 20 /* abbreviation code */
        .uleb128 33 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 34
        .uleb128 7
        .uleb128 47
        .uleb128 7
        .byte   0
        .byte   0
        .uleb128 21 /* abbreviation code */
        .uleb128 15 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .byte   0 /* end abbreviation table */

#
# DWARF string table
#
        .section .debug_str,"MS",@progbits,1
.Ldw_str_start:
.Ldw10:
        .asciz  "real"
.Ldw9:
        .asciz  "char"
.Ldw8:
        .asciz  "boolean"
.Ldw7:
        .asciz  "integer"
.Ldw6:
        .asciz  "services"
.Ldw5:
        .asciz  "Pascal-P6 pgen"
