!
! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
!
p       /home/samiam/projects/pascal/pascal-p6/libs/source/sound.pas
o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv- 
! {******************************************************************************
:1
!
! Sound Library Interface
!
! Pascaline binding to the Ami sound library. Generated by
! tools/sndnetgen/gen.py from amitk/include/sound.h; do not edit by hand.
!
! ******************************************************************************}
!
! module sound;
:2
:3
:4
:5
:6
:7
:8
:9
:10
!
! Module sound
!
b       m       sound
        sfr     l sound.6               ! Set function result
l sound.6=0
        cup     l sound.3 0              ! Call user procedure
        cal     l sound.5               ! Call initializer code strip
        sfr     l sound.6               ! Set function result
        cup     l sound.4 0              ! Call user procedure
        ret                             ! Return code strip
!
! const
:11
:12
!    chan_drum = 10;
:13
!    synth_out = 1;
:14
!    synth_in = 1;
:15
!    wave_in = 1;
:16
!    wave_out = 1;
:17
!    note_c = 1;
:18
!    note_c_sharp = 2;
:19
!    note_d_flat = 2;
:20
!    note_d = 3;
:21
!    note_d_sharp = 4;
:22
!    note_e_flat = 4;
:23
!    note_e = 5;
:24
!    note_f = 6;
:25
!    note_f_sharp = 7;
:26
!    note_g_flat = 7;
:27
!    note_g = 8;
:28
!    note_g_sharp = 9;
:29
!    note_a_flat = 9;
:30
!    note_a = 10;
:31
!    note_a_sharp = 11;
:32
!    note_b_flat = 11;
:33
!    note_b = 12;
:34
!    octave_1 = 0;
:35
!    octave_2 = 12;
:36
!    octave_3 = 24;
:37
!    octave_4 = 36;
:38
!    octave_5 = 48;
:39
!    octave_6 = 60;
:40
!    octave_7 = 72;
:41
!    octave_8 = 84;
:42
!    octave_9 = 96;
:43
!    octave_10 = 108;
:44
!    octave_11 = 120;
:45
!    inst_acoustic_grand = 1;
:46
!    inst_bright_acoustic = 2;
:47
!    inst_electric_grand = 3;
:48
!    inst_honky_tonk = 4;
:49
!    inst_electric_piano_1 = 5;
:50
!    inst_electric_piano_2 = 6;
:51
!    inst_harpsichord = 7;
:52
!    inst_clavinet = 8;
:53
!    inst_celesta = 9;
:54
!    inst_glockenspiel = 10;
:55
!    inst_music_box = 11;
:56
!    inst_vibraphone = 12;
:57
!    inst_marimba = 13;
:58
!    inst_xylophone = 14;
:59
!    inst_tubular_bells = 15;
:60
!    inst_dulcimer = 16;
:61
!    inst_drawbar_organ = 17;
:62
!    inst_percussive_organ = 18;
:63
!    inst_rock_organ = 19;
:64
!    inst_church_organ = 20;
:65
!    inst_reed_organ = 21;
:66
!    inst_accoridan = 22;
:67
!    inst_harmonica = 23;
:68
!    inst_tango_accordian = 24;
:69
!    inst_nylon_string_guitar = 25;
:70
!    inst_steel_string_guitar = 26;
:71
!    inst_electric_jazz_guitar = 27;
:72
!    inst_electric_clean_guitar = 28;
:73
!    inst_electric_muted_guitar = 29;
:74
!    inst_overdriven_guitar = 30;
:75
!    inst_distortion_guitar = 31;
:76
!    inst_guitar_harmonics = 32;
:77
!    inst_acoustic_bass = 33;
:78
!    inst_electric_bass_finger = 34;
:79
!    inst_electric_bass_pick = 35;
:80
!    inst_fretless_bass = 36;
:81
!    inst_slap_bass_1 = 37;
:82
!    inst_slap_bass_2 = 38;
:83
!    inst_synth_bass_1 = 39;
:84
!    inst_synth_bass_2 = 40;
:85
!    inst_violin = 41;
:86
!    inst_viola = 42;
:87
!    inst_cello = 43;
:88
!    inst_contrabass = 44;
:89
!    inst_tremolo_strings = 45;
:90
!    inst_pizzicato_strings = 46;
:91
!    inst_orchestral_strings = 47;
:92
!    inst_timpani = 48;
:93
!    inst_string_ensemble_1 = 49;
:94
!    inst_string_ensemble_2 = 50;
:95
!    inst_synthstrings_1 = 51;
:96
!    inst_synthstrings_2 = 52;
:97
!    inst_choir_aahs = 53;
:98
!    inst_voice_oohs = 54;
:99
!    inst_synth_voice = 55;
:100
!    inst_orchestra_hit = 56;
:101
!    inst_trumpet = 57;
:102
!    inst_trombone = 58;
:103
!    inst_tuba = 59;
:104
!    inst_muted_trumpet = 60;
:105
!    inst_french_horn = 61;
:106
!    inst_brass_section = 62;
:107
!    inst_synthbrass_1 = 63;
:108
!    inst_synthbrass_2 = 64;
:109
!    inst_soprano_sax = 65;
:110
!    inst_alto_sax = 66;
:111
!    inst_tenor_sax = 67;
:112
!    inst_baritone_sax = 68;
:113
!    inst_oboe = 69;
:114
!    inst_english_horn = 70;
:115
!    inst_bassoon = 71;
:116
!    inst_clarinet = 72;
:117
!    inst_piccolo = 73;
:118
!    inst_flute = 74;
:119
!    inst_recorder = 75;
:120
!    inst_pan_flute = 76;
:121
!    inst_blown_bottle = 77;
:122
!    inst_skakuhachi = 78;
:123
!    inst_whistle = 79;
:124
!    inst_ocarina = 80;
:125
!    inst_lead_1_square = 81;
:126
!    inst_lead_2_sawtooth = 82;
:127
!    inst_lead_3_calliope = 83;
:128
!    inst_lead_4_chiff = 84;
:129
!    inst_lead_5_charang = 85;
:130
!    inst_lead_6_voice = 86;
:131
!    inst_lead_7_fifths = 87;
:132
!    inst_lead_8_bass_lead = 88;
:133
!    inst_pad_1_new_age = 89;
:134
!    inst_pad_2_warm = 90;
:135
!    inst_pad_3_polysynth = 91;
:136
!    inst_pad_4_choir = 92;
:137
!    inst_pad_5_bowed = 93;
:138
!    inst_pad_6_metallic = 94;
:139
!    inst_pad_7_halo = 95;
:140
!    inst_pad_8_sweep = 96;
:141
!    inst_fx_1_rain = 97;
:142
!    inst_fx_2_soundtrack = 98;
:143
!    inst_fx_3_crystal = 99;
:144
!    inst_fx_4_atmosphere = 100;
:145
!    inst_fx_5_brightness = 101;
:146
!    inst_fx_6_goblins = 102;
:147
!    inst_fx_7_echoes = 103;
:148
!    inst_fx_8_sci_fi = 104;
:149
!    inst_sitar = 105;
:150
!    inst_banjo = 106;
:151
!    inst_shamisen = 107;
:152
!    inst_koto = 108;
:153
!    inst_kalimba = 109;
:154
!    inst_bagpipe = 110;
:155
!    inst_fiddle = 111;
:156
!    inst_shanai = 112;
:157
!    inst_tinkle_bell = 113;
:158
!    inst_agogo = 114;
:159
!    inst_steel_drums = 115;
:160
!    inst_woodblock = 116;
:161
!    inst_taiko_drum = 117;
:162
!    inst_melodic_tom = 118;
:163
!    inst_synth_drum = 119;
:164
!    inst_reverse_cymbal = 120;
:165
!    inst_guitar_fret_noise = 121;
:166
!    inst_breath_noise = 122;
:167
!    inst_seashore = 123;
:168
!    inst_bird_tweet = 124;
:169
!    inst_telephone_ring = 125;
:170
!    inst_helicopter = 126;
:171
!    inst_applause = 127;
:172
!    inst_gunshot = 128;
:173
!    note_acoustic_bass_drum = 35;
:174
!    note_bass_drum_1 = 36;
:175
!    note_side_stick = 37;
:176
!    note_acoustic_snare = 38;
:177
!    note_hand_clap = 39;
:178
!    note_electric_snare = 40;
:179
!    note_low_floor_tom = 41;
:180
!    note_closed_hi_hat = 42;
:181
!    note_high_floor_tom = 43;
:182
!    note_pedal_hi_hat = 44;
:183
!    note_low_tom = 45;
:184
!    note_open_hi_hat = 46;
:185
!    note_low_mid_tom = 47;
:186
!    note_hi_mid_tom = 48;
:187
!    note_crash_cymbal_1 = 49;
:188
!    note_high_tom = 50;
:189
!    note_ride_cymbal_1 = 51;
:190
!    note_chinese_cymbal = 52;
:191
!    note_ride_bell = 53;
:192
!    note_tambourine = 54;
:193
!    note_splash_cymbal = 55;
:194
!    note_cowbell = 56;
:195
!    note_crash_cymbal_2 = 57;
:196
!    note_vibraslap = 58;
:197
!    note_ride_cymbal_2 = 59;
:198
!    note_hi_bongo = 60;
:199
!    note_low_bongo = 61;
:200
!    note_mute_hi_conga = 62;
:201
!    note_open_hi_conga = 63;
:202
!    note_low_conga = 64;
:203
!    note_high_timbale = 65;
:204
!    note_low_timbale = 66;
:205
!    note_high_agogo = 67;
:206
!    note_low_agogo = 68;
:207
!    note_cabasa = 69;
:208
!    note_maracas = 70;
:209
!    note_short_whistle = 71;
:210
!    note_long_whistle = 72;
:211
!    note_short_guiro = 73;
:212
!    note_long_guiro = 74;
:213
!    note_claves = 75;
:214
!    note_hi_wood_block = 76;
:215
!    note_low_wood_block = 77;
:216
!    note_mute_cuica = 78;
:217
!    note_open_cuica = 79;
:218
!    note_mute_triangle = 80;
:219
!    note_open_triangle = 81;
:220
!
! type
:221
:222
!    chan = 1..16; { midi channel; "channel" is a reserved word }
:223
!    note = 1..128;
:224
!    instrument = 1..128;
:225
!    byte = 0..255;
:226
!    bytarr = packed array of byte;
:227
!
! procedure starttimeout; external;
:228
:229
! procedure stoptimeout; external;
z 0 0 sound.starttimeout@p
:230
! function curtimeout: integer; external;
z 0 0 sound.stoptimeout@p
:231
! procedure starttimein; external;
z 0 0 sound.curtimeout@f
:232
! procedure stoptimein; external;
z 0 0 sound.starttimein@p
:233
! function curtimein: integer; external;
z 0 0 sound.stoptimein@p
:234
! function synthout: integer; external;
z 0 0 sound.curtimein@f
:235
! function synthin: integer; external;
z 0 0 sound.synthout@f
:236
! procedure opensynthout(p: integer); external;
z 0 0 sound.synthin@f
:237
! procedure closesynthout(p: integer); external;
z 0 0 sound.opensynthout@p_i
:238
! procedure opensynthin(p: integer); external;
z 0 0 sound.closesynthout@p_i
:239
! procedure closesynthin(p: integer); external;
z 0 0 sound.opensynthin@p_i
:240
! procedure noteon(p: integer; t: integer; c: chan; n: note; v: integer); external;
z 0 0 sound.closesynthin@p_i
:241
! procedure noteoff(p: integer; t: integer; c: chan; n: note; v: integer); external;
z 0 0 sound.noteon@p_i_i_x(1,16)i_x(1,128)i_i
:242
! procedure instchange(p: integer; t: integer; c: chan; i: instrument); external;
z 0 0 sound.noteoff@p_i_i_x(1,16)i_x(1,128)i_i
:243
! procedure attack(p: integer; t: integer; c: chan; at: integer); external;
z 0 0 sound.instchange@p_i_i_x(1,16)i_x(1,128)i
:244
! procedure release(p: integer; t: integer; c: chan; rt: integer); external;
z 0 0 sound.attack@p_i_i_x(1,16)i_i
:245
! procedure legato(p: integer; t: integer; c: chan; b: integer); external;
z 0 0 sound.release@p_i_i_x(1,16)i_i
:246
! procedure portamento(p: integer; t: integer; c: chan; b: integer); external;
z 0 0 sound.legato@p_i_i_x(1,16)i_i
:247
! procedure vibrato(p: integer; t: integer; c: chan; v: integer); external;
z 0 0 sound.portamento@p_i_i_x(1,16)i_i
:248
! procedure volsynthchan(p: integer; t: integer; c: chan; v: integer); external;
z 0 0 sound.vibrato@p_i_i_x(1,16)i_i
:249
! procedure porttime(p: integer; t: integer; c: chan; v: integer); external;
z 0 0 sound.volsynthchan@p_i_i_x(1,16)i_i
:250
! procedure balance(p: integer; t: integer; c: chan; b: integer); external;
z 0 0 sound.porttime@p_i_i_x(1,16)i_i
:251
! procedure pan(p: integer; t: integer; c: chan; b: integer); external;
z 0 0 sound.balance@p_i_i_x(1,16)i_i
:252
! procedure timbre(p: integer; t: integer; c: chan; tb: integer); external;
z 0 0 sound.pan@p_i_i_x(1,16)i_i
:253
! procedure brightness(p: integer; t: integer; c: chan; b: integer); external;
z 0 0 sound.timbre@p_i_i_x(1,16)i_i
:254
! procedure reverb(p: integer; t: integer; c: chan; r: integer); external;
z 0 0 sound.brightness@p_i_i_x(1,16)i_i
:255
! procedure tremulo(p: integer; t: integer; c: chan; tr: integer); external;
z 0 0 sound.reverb@p_i_i_x(1,16)i_i
:256
! procedure chorus(p: integer; t: integer; c: chan; cr: integer); external;
z 0 0 sound.tremulo@p_i_i_x(1,16)i_i
:257
! procedure celeste(p: integer; t: integer; c: chan; ce: integer); external;
z 0 0 sound.chorus@p_i_i_x(1,16)i_i
:258
! procedure phaser(p: integer; t: integer; c: chan; ph: integer); external;
z 0 0 sound.celeste@p_i_i_x(1,16)i_i
:259
! procedure aftertouch(p: integer; t: integer; c: chan; n: note; at: integer); external;
z 0 0 sound.phaser@p_i_i_x(1,16)i_i
:260
! procedure pressure(p: integer; t: integer; c: chan; pr: integer); external;
z 0 0 sound.aftertouch@p_i_i_x(1,16)i_x(1,128)i_i
:261
! procedure pitch(p: integer; t: integer; c: chan; pt: integer); external;
z 0 0 sound.pressure@p_i_i_x(1,16)i_i
:262
! procedure pitchrange(p: integer; t: integer; c: chan; v: integer); external;
z 0 0 sound.pitch@p_i_i_x(1,16)i_i
:263
! procedure mono(p: integer; t: integer; c: chan; ch: integer); external;
z 0 0 sound.pitchrange@p_i_i_x(1,16)i_i
:264
! procedure poly(p: integer; t: integer; c: chan); external;
z 0 0 sound.mono@p_i_i_x(1,16)i_i
:265
! procedure loadsynth(s: integer; view sf: string); external;
z 0 0 sound.poly@p_i_i_x(1,16)i
:266
! procedure playsynth(p: integer; t: integer; s: integer); external;
z 0 0 sound.loadsynth@p_i_vc
:267
! procedure delsynth(s: integer); external;
z 0 0 sound.playsynth@p_i_i_i
:268
! procedure waitsynth(p: integer); external;
z 0 0 sound.delsynth@p_i
:269
! function waveout: integer; external;
z 0 0 sound.waitsynth@p_i
:270
! function wavein: integer; external;
z 0 0 sound.waveout@f
:271
! procedure openwaveout(p: integer); external;
z 0 0 sound.wavein@f
:272
! procedure closewaveout(p: integer); external;
z 0 0 sound.openwaveout@p_i
:273
! procedure loadwave(w: integer; view fn: string); external;
z 0 0 sound.closewaveout@p_i
:274
! procedure playwave(p: integer; t: integer; w: integer); external;
z 0 0 sound.loadwave@p_i_vc
:275
! procedure delwave(w: integer); external;
z 0 0 sound.playwave@p_i_i_i
:276
! procedure volwave(p: integer; t: integer; v: integer); external;
z 0 0 sound.delwave@p_i
:277
! procedure waitwave(p: integer); external;
z 0 0 sound.volwave@p_i_i_i
:278
! procedure chanwaveout(p: integer; c: integer); external;
z 0 0 sound.waitwave@p_i
:279
! procedure ratewaveout(p: integer; r: integer); external;
z 0 0 sound.chanwaveout@p_i_i
:280
! procedure lenwaveout(p: integer; l: integer); external;
z 0 0 sound.ratewaveout@p_i_i
:281
! procedure sgnwaveout(p: integer; s: integer); external;
z 0 0 sound.lenwaveout@p_i_i
:282
! procedure fltwaveout(p: integer; f: integer); external;
z 0 0 sound.sgnwaveout@p_i_i
:283
! procedure endwaveout(p: integer; e: integer); external;
z 0 0 sound.fltwaveout@p_i_i
:284
! procedure wrwave(p: integer; view buff: bytarr); external;
z 0 0 sound.endwaveout@p_i_i
:285
! procedure openwavein(p: integer); external;
z 0 0 sound.wrwave@p_i_vx(0,255)i
:286
! procedure closewavein(p: integer); external;
z 0 0 sound.openwavein@p_i
:287
! function chanwavein(p: integer): integer; external;
z 0 0 sound.closewavein@p_i
:288
! function ratewavein(p: integer): integer; external;
z 0 0 sound.chanwavein@f_i
:289
! function lenwavein(p: integer): integer; external;
z 0 0 sound.ratewavein@f_i
:290
! function sgnwavein(p: integer): integer; external;
z 0 0 sound.lenwavein@f_i
:291
! function endwavein(p: integer): integer; external;
z 0 0 sound.sgnwavein@f_i
:292
! function fltwavein(p: integer): integer; external;
z 0 0 sound.endwavein@f_i
:293
! function rdwave(p: integer; var buff: bytarr): integer; external;
z 0 0 sound.fltwavein@f_i
:294
! procedure synthoutname(p: integer; var name: string); external;
z 0 0 sound.rdwave@f_i_vx(0,255)i
:295
! procedure synthinname(p: integer; var name: string); external;
z 0 0 sound.synthoutname@p_i_vc
:296
! procedure waveoutname(p: integer; var name: string); external;
z 0 0 sound.synthinname@p_i_vc
:297
! procedure waveinname(p: integer; var name: string); external;
z 0 0 sound.waveoutname@p_i_vc
:298
! function setparamsynthin(p: integer; view name: string; view value: string): integer; external;
z 0 0 sound.waveinname@p_i_vc
:299
! function setparamsynthout(p: integer; view name: string; view value: string): integer; external;
z 0 0 sound.setparamsynthin@f_i_vc_vc
:300
! function setparamwavein(p: integer; view name: string; view value: string): integer; external;
z 0 0 sound.setparamsynthout@f_i_vc_vc
:301
! function setparamwaveout(p: integer; view name: string; view value: string): integer; external;
z 0 0 sound.setparamwavein@f_i_vc_vc
:302
! procedure getparamsynthin(p: integer; view name: string; var value: string); external;
z 0 0 sound.setparamwaveout@f_i_vc_vc
:303
! procedure getparamsynthout(p: integer; view name: string; var value: string); external;
z 0 0 sound.getparamsynthin@p_i_vc_vc
:304
! procedure getparamwavein(p: integer; view name: string; var value: string); external;
z 0 0 sound.getparamsynthout@p_i_vc_vc
:305
! procedure getparamwaveout(p: integer; view name: string; var value: string); external;
z 0 0 sound.getparamwavein@p_i_vc_vc
:306
!
! begin
z 0 0 sound.getparamwaveout@p_i_vc_vc
l sound.3
:307
:308
:308
        mst     0 l sound.85 l sound.86 ! Mark(frame) stack
! end.
:309
        retp    0                       ! Return from procedure/function(t)
l sound.85=0
l sound.86=0
l sound.4
        mst     0 l sound.88 l sound.89 ! Mark(frame) stack
        retp    0                       ! Return from procedure/function(t)
l sound.88=0
l sound.89=0
l sound.5
g 89
e m
f       0
