#
# File generated by P6 Pascal AMD64/gcc 64 bit code generator vs. 0.5.x
#

# Header file locations
inputoff = 0
outputoff = 2
prdoff = 4
prroff = 6
erroroff = 8
listoff = 10
commandoff = 12

# Logical file numbers for header files
inputfn = 1
outputfn = 2
prdfn = 3
prrfn = 4
errorfn = 5
listfn = 6
commandfn = 7

# Error codes
ValueOutOfRange                    = 0
ArrayLengthMatch                   = 1
CaseValueNotFound                  = 2
ZeroDivide                         = 3
InvalidOperand                     = 4
NilPointerDereference              = 5
RealOverflow                       = 6
RealUnderflow                      = 7
RealProcessingFault                = 8
TagValueNotActive                  = 9
TooManyFiles                       = 10
FileIsOpen                         = 11
FileAlreadyNamed                   = 12
FileNotOpen                        = 13
FileModeIncorrect                  = 14
InvalidFieldSpecification          = 15
InvalidRealNumber                  = 16
InvalidFractionSpecification       = 17
InvalidIntegerFormat               = 18
IntegerValueOverflow               = 19
InvalidRealFormat                  = 20
EndOfFile                          = 21
InvalidFilePosition                = 22
FilenameTooLong                    = 23
FileOpenFail                       = 24
FileSIzeFail                       = 25
FileCloseFail                      = 26
FileReadFail                       = 27
FileWriteFail                      = 28
FilePositionFail                   = 29
FileDeleteFail                     = 30
FileNameChangeFail                 = 31
SpaceAllocateFail                  = 32
SpaceReleaseFail                   = 33
SpaceAllocateNegative              = 34
CannotPerformSpecial               = 35
CommandLineTooLong                 = 36
ReadPastEOF                        = 37
FileTransferLengthZero             = 38
FileSizeTooLarge                   = 39
FilenameEmpty                      = 40
CannotOpenStandard                 = 41
TooManyTemporaryFiles              = 42
InputBufferOverflow                = 43
TooManyThreads                     = 44
CannotStartThread                  = 45
InvalidThreadHandle                = 46
CannotStopThread                   = 47
TooManyIntertaskLocks              = 48
InvalidLockHandle                  = 49
LockSequenceFail                   = 50
TooManySignals                     = 51
CannotCreateSignal                 = 52
InvalidSignalHandle                = 53
CannotDeleteSignal                 = 54
CannotSendSignal                   = 55
WaitForSignalFail                  = 56
FieldNotBlank                      = 57
ReadOnWriteOnlyFile                = 58
WriteOnReadOnlyFile                = 59
FileBufferVariableUndefined        = 60
NondecimalRadixOfNegative          = 61
InvalidArgumentToLn                = 62
InvalidArgumentToSqrt              = 63
CannotResetOrRewriteStandardFile   = 64
CannotResetWriteOnlyFile           = 65
CannotRewriteReadOnlyFile          = 66
SetElementOutOfRange               = 67
RealArgumentTooLarge               = 68
BooleanOperatorOfNegative          = 69
InvalidDivisorToMod                = 70
PackElementsOutOfBounds            = 71
UnpackElementsOutOfBounds          = 72
CannotResetClosedTempFile          = 73
ReadCharacterMismatch              = 74
UndefinedLocationAccess            = 75
FunctionNotImplemented             = 76
InvalidInISO7185Mode               = 77
HeapFormatInvalid                  = 78
DisposeOfUninitalizedPointer       = 79
DisposeOfNilPointer                = 80
BadPointerValue                    = 81
BlockAlreadyFreed                  = 82
InvalidStandardProcedureOrFunction = 83
InvalidInstruction                 = 84
NewDisposeTagsMismatch             = 85
PCOutOfRange                       = 86
StoreOverflow                      = 87
StackBalance                       = 88
SetInclusion                       = 89
UninitializedPointer               = 90
DereferenceOfNilPointer            = 91
PointerUsedAfterDispose            = 92
VariantNotActive                   = 93
InvalidCase                        = 94
SystemError                        = 95
ChangeToAllocatedTagfield          = 96
UnhandledException                 = 97
ProgramCodeAssertion               = 98
VarListEmpty                       = 99
ChangeToVarReferencedVariant       = 100
DisposeOfVarReferencedBlock        = 101
VarReferencedFileBufferModified    = 102
ContainerMismatch                  = 103
InvalidContainerLevel              = 104
DisposeOfWithReferencedBlock       = 105
WithBaseListEmpty                  = 106
ExternalsNotEnabled                = 107
MasterException                    = 108


# machine parameters
lendian     =       true /* endian mode */
intsize     =          8 /* size of integer */
intal       =          4 /* alignment of integer */
intdig      =         20 /* number of decimal digits in integer */
inthex      =         16 /* number of hex digits of integer */
realsize    =          8 /* size of real */
realal      =          4 /* alignment of real */
charsize    =          1 /* size of char */
charal      =          1 /* alignment of char */
boolsize    =          1 /* size of boolean */
boolal      =          1 /* alignment of boolean */
ptrsize     =          8 /* size of pointer */
adrsize     =          8 /* size of address */
adral       =          4 /* alignment of address */
setsize     =         32 /* size of set */
setal       =          1 /* alignment of set */
filesize    =          1 /* required runtime space for file (lfn) */
fileidsize  =          1 /* size of the lfn only */
exceptsize  =          1 /* size of exception variable */
exceptal    =          1 /* alignment of exception */
stackal     =          8 /* alignment of stack */
stackelsize =          8 /* stack element size */
maxsize     =         32 /* this is the largest type that can be on the stack */
heapal      =          4 /* alignment for each heap arena */
gbsal       =          4 /* globals area alignment */
sethigh     =        255 /* set highest value */
setlow      =          0 /* set lowest value */
ordmaxchar  =        255 /* character highest value */
ordminchar  =          0 /* character lowest value */
marksize    =         24 /* size of mark */
maxexp      =        308 /* maximum exponent of real */
nilval      =          1 /* value of nil */
maxint      = 9223372036854775807 /* value of maxint on target machine */
markep      =          8 /* (old) maximum frame size */
marksb      =         16 /* stack bottom */
market      =         24 /* current ep */

        .text
#
# Code section
#
#      0:      1: !
#      0:      2: ! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
#      0:      3: !
#      0:      4: p       /home/samiam/projects/pascal/pascal-p6/libs/tests/find_getpgm.pas
        .section .debug_line,"",@progbits
.Ldw_line_start:
        .text
        .file   "find_getpgm.pas"
        .file   1 "/home/samiam/projects/pascal/pascal-p6/libs/tests/find_getpgm.pas"
#      0:      5: o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
#      0:      6: ! {******************************************************************************
#      0:      7: :1
        .loc 1 1 1
#      1:      8: ! *                                                                             *
#      1:      9: ! *                      GETPGM LOCATION TEST HELPER                            *
#      1:     10: ! *                                                                             *
#      1:     11: ! * Prints the basename of its own program directory (getpgm with the path      *
#      1:     12: ! * removed). It is installed in bin (bin/build copies every libs/tests program *
#      1:     13: ! * there) and is not relocated by the parallel test harness, so it always      *
#      1:     14: ! * reports "bin". services_test sub-executes it to test getpgm deterministically*
#      1:     15: ! * -- services_test's own binary is moved into per-model directories by the     *
#      1:     16: ! * harness, so its own getpgm would not be stable.                             *
#      1:     17: ! *                                                                             *
#      1:     18: ! ******************************************************************************}
#      1:     19: !
#      1:     20: ! program find_getpgm(output);
#      1:     21: :2
        .loc 1 2 1
#      2:     22: :3
        .loc 1 3 1
#      3:     23: :4
        .loc 1 4 1
#      4:     24: :5
        .loc 1 5 1
#      5:     25: :6
        .loc 1 6 1
#      6:     26: :7
        .loc 1 7 1
#      7:     27: :8
        .loc 1 8 1
#      8:     28: :9
        .loc 1 9 1
#      9:     29: :10
        .loc 1 10 1
#     10:     30: :11
        .loc 1 11 1
#     11:     31: :12
        .loc 1 12 1
#     12:     32: :13
        .loc 1 13 1
#     13:     33: :14
        .loc 1 14 1
#     14:     34: !
#     14:     35: ! Program find_getpgm
#     14:     36: !
#     14:     37: b       p       find_getpgm
        .globl  find_getpgm
        .type   find_getpgm, @function
find_getpgm:
        .cfi_startproc
# Align stack
        pushq   %rax
        .cfi_adjust_cfa_offset 8
# Set up default files
        movb    $inputfn,globals_start+inputoff(%rip)
        movb    $outputfn,globals_start+outputoff(%rip)
        movb    $prdfn,globals_start+prdoff(%rip)
        movb    $prrfn,globals_start+prroff(%rip)
        movb    $errorfn,globals_start+erroroff(%rip)
        movb    $listfn,globals_start+listoff(%rip)
        movb    $commandfn,globals_start+commandoff(%rip)
# Call startup code
        call    1f
        popq    %rax
        .cfi_adjust_cfa_offset -8
        sub     %rax,%rax
        ret
        .cfi_endproc
1:
#     14:     38:         sfr     l find_getpgm.6         ! Set function result
#     14:     39: l find_getpgm.6=0
find_getpgm.6 = 0
#     14:     40:         cup     l find_getpgm.3 0        ! Call user procedure
# assigning:      14:     40:  12: cup  0 rs: [] ~rf: []
# assigning~:     14:     40:  12: cup  0 rs: [] ~rf: []
#    expr:
#      14:     40:  12: cup  0 rs: []
#  call start:
#      14:     38: 245: sfr  0 rs: []
# generating:      14:     40:  12: cup  0 rs: []
# generating:      14:     38: 245: sfr  0 rs: []
        movq    %rsp,%rax               # copy stack pointer
        subq    $find_getpgm.6,%rax     # set new stack depth
1:              
        cmpq    %rax,%rsp               # check done
        jbe     2f                      # skip if below stack
        pushq   $0                      # clear stack
        jmp     1b                      # loop
2:              
# generating~:     14:     38: 245: sfr  0 rs: []
        call    find_getpgm.3           # call user procedure
# generating~:     14:     40:  12: cup  0 rs: []
#     14:     41:         ret                             ! Return code strip
        ret      
#     14:     42: !
#     14:     43: ! uses services;
#     14:     44: :15
        .loc 1 15 1
#     15:     45: :16
        .loc 1 16 1
#     16:     46: z 0 0 services.list@p_vc_pr(name:0:pvc,size:8:i,alloc:16:i,attr:24:sx(atexec,atarc,atsys,atdir,atloop),create:56:i,modify:64:i,access:72:i,backup:80:i,user:88:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),group:120:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),other:152:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),next:184:p2)
#     16:     47: z 0 0 services.list@p_pvc_pr(name:0:pvc,size:8:i,alloc:16:i,attr:24:sx(atexec,atarc,atsys,atdir,atloop),create:56:i,modify:64:i,access:72:i,backup:80:i,user:88:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),group:120:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),other:152:sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren),next:184:p2)
#     16:     48: z 0 0 services.times@p_vc_i
#     16:     49: z 0 0 services.times@f_i
#     16:     50: z 0 0 services.dates@p_vc_i
#     16:     51: z 0 0 services.dates@f_i
#     16:     52: z 0 0 services.writetime@p_fc_i
#     16:     53: z 0 0 services.writetime@p_i
#     16:     54: z 0 0 services.writedate@p_fc_i
#     16:     55: z 0 0 services.writedate@p_i
#     16:     56: z 0 0 services.time@f
#     16:     57: z 0 0 services.local@f_i
#     16:     58: z 0 0 services.clock@f
#     16:     59: z 0 0 services.elapsed@f_i
#     16:     60: z 0 0 services.validfile@f_vc
#     16:     61: z 0 0 services.validfile@f_pvc
#     16:     62: z 0 0 services.validpath@f_vc
#     16:     63: z 0 0 services.validpath@f_pvc
#     16:     64: z 0 0 services.wild@f_vc
#     16:     65: z 0 0 services.wild@f_pvc
#     16:     66: z 0 0 services.getenv@p_vc_vc
#     16:     67: z 0 0 services.getenv@f_vc
#     16:     68: z 0 0 services.setenv@p_vc_vc
#     16:     69: z 0 0 services.setenv@p_pvc_vc
#     16:     70: z 0 0 services.setenv@p_vc_pvc
#     16:     71: z 0 0 services.setenv@p_pvc_pvc
#     16:     72: z 0 0 services.allenv@p_pr(name:0:pvc,data:8:p12,next:16:p2)
#     16:     73: z 0 0 services.remenv@p_vc
#     16:     74: z 0 0 services.remenv@p_pvc
#     16:     75: z 0 0 services.exec@p_vc
#     16:     76: z 0 0 services.exec@p_pvc
#     16:     77: z 0 0 services.exece@p_vc_pr(name:0:pvc,data:8:p12,next:16:p2)
#     16:     78: z 0 0 services.exece@p_pvc_pr(name:0:pvc,data:8:p12,next:16:p2)
#     16:     79: z 0 0 services.execw@p_vc_i
#     16:     80: z 0 0 services.execw@p_pvc_i
#     16:     81: z 0 0 services.execew@p_vc_pr(name:0:pvc,data:8:p12,next:16:p2)_i
#     16:     82: z 0 0 services.execew@p_pvc_pr(name:0:pvc,data:8:p12,next:16:p2)_i
#     16:     83: z 0 0 services.getcur@p_vc
#     16:     84: z 0 0 services.getcur@f
#     16:     85: z 0 0 services.setcur@p_vc
#     16:     86: z 0 0 services.setcur@p_pvc
#     16:     87: z 0 0 services.brknam@p_vc_vc_vc_vc
#     16:     88: z 0 0 services.brknam@p_vc_pvc_pvc_pvc
#     16:     89: z 0 0 services.brknam@p_pvc_pvc_pvc_pvc
#     16:     90: z 0 0 services.maknam@p_vc_vc_vc_vc
#     16:     91: z 0 0 services.maknam@f_vc_vc_vc
#     16:     92: z 0 0 services.maknam@f_vc_vc_pvc
#     16:     93: z 0 0 services.maknam@f_vc_pvc_vc
#     16:     94: z 0 0 services.maknam@f_vc_pvc_pvc
#     16:     95: z 0 0 services.maknam@f_pvc_vc_vc
#     16:     96: z 0 0 services.maknam@f_pvc_vc_pvc
#     16:     97: z 0 0 services.maknam@f_pvc_pvc_vc
#     16:     98: z 0 0 services.maknam@f_pvc_pvc_pvc
#     16:     99: z 0 0 services.fulnam@p_vc
#     16:    100: z 0 0 services.fulnam@f_vc
#     16:    101: z 0 0 services.getpgm@p_vc
#     16:    102: z 0 0 services.getpgm@f
#     16:    103: z 0 0 services.getusr@p_vc
#     16:    104: z 0 0 services.getusr@f
#     16:    105: z 0 0 services.setatr@p_vc_sx(atexec,atarc,atsys,atdir,atloop)
#     16:    106: z 0 0 services.setatr@p_pvc_sx(atexec,atarc,atsys,atdir,atloop)
#     16:    107: z 0 0 services.resatr@p_vc_sx(atexec,atarc,atsys,atdir,atloop)
#     16:    108: z 0 0 services.resatr@p_pvc_sx(atexec,atarc,atsys,atdir,atloop)
#     16:    109: z 0 0 services.bakupd@p_vc
#     16:    110: z 0 0 services.bakupd@p_pvc
#     16:    111: z 0 0 services.setuper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    112: z 0 0 services.setuper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    113: z 0 0 services.resuper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    114: z 0 0 services.resuper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    115: z 0 0 services.setgper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    116: z 0 0 services.setgper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    117: z 0 0 services.resgper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    118: z 0 0 services.resgper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    119: z 0 0 services.setoper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    120: z 0 0 services.setoper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    121: z 0 0 services.resoper@p_vc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    122: z 0 0 services.resoper@p_pvc_sx(pmread,pmwrite,pmexec,pmdel,pmvis,pmcopy,pmren)
#     16:    123: z 0 0 services.seterr@p_i
#     16:    124: z 0 0 services.makpth@p_vc
#     16:    125: z 0 0 services.makpth@p_pvc
#     16:    126: z 0 0 services.rempth@p_vc
#     16:    127: z 0 0 services.rempth@p_pvc
#     16:    128: z 0 0 services.filchr@p_sc
#     16:    129: z 0 0 services.optchr@f
#     16:    130: z 0 0 services.pthchr@f
#     16:    131: z 0 0 services.latitude@f
#     16:    132: z 0 0 services.longitude@f
#     16:    133: z 0 0 services.altitude@f
#     16:    134: z 0 0 services.country@f
#     16:    135: z 0 0 services.countrys@p_vc_i
#     16:    136: z 0 0 services.timezone@f
#     16:    137: z 0 0 services.daysave@f
#     16:    138: z 0 0 services.time24hour@f
#     16:    139: z 0 0 services.language@f
#     16:    140: z 0 0 services.languages@p_vc_i
#     16:    141: z 0 0 services.decimal@f
#     16:    142: z 0 0 services.numbersep@f
#     16:    143: z 0 0 services.timeorder@f
#     16:    144: z 0 0 services.dateorder@f
#     16:    145: z 0 0 services.datesep@f
#     16:    146: z 0 0 services.timesep@f
#     16:    147: z 0 0 services.currchr@f
#     16:    148: !
#     16:    149: ! var s:       packed array [1..256] of char;
#     16:    150: :17
        .loc 1 17 1
#     17:    151: :18
        .loc 1 18 1
#     18:    152: t       l find_getpgm.118 1 256
#     18:    153: s       s g 89 ax(1,256)ic
        .globl   find_getpgm.s
find_getpgm.s = globals_start+89
#     18:    154: !     p, n, e: packed array [1..256] of char;
#     18:    155: :19
        .loc 1 19 1
#     19:    156: t       l find_getpgm.119 1 256
#     19:    157: s       e g 345 ax(1,256)ic
        .globl   find_getpgm.e
find_getpgm.e = globals_start+345
#     19:    158: s       n g 601 ax(1,256)ic
        .globl   find_getpgm.n
find_getpgm.n = globals_start+601
#     19:    159: s       p g 857 ax(1,256)ic
        .globl   find_getpgm.p
find_getpgm.p = globals_start+857
#     19:    160: !
#     19:    161: ! begin
#     19:    162: l find_getpgm.3
find_getpgm.3:
#     19:    163: :20
        .loc 1 20 1
#     20:    164: :21
        .loc 1 21 1
#     21:    165: :21
        .loc 1 21 1
#     21:    166:         mst     0 l find_getpgm.120 l find_getpgm.121 ! Mark(frame) stack
        .cfi_startproc
# generating:  11: mst       
        pushq   $0                      # place current ep
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place bottom of stack
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place previous ep
        .cfi_adjust_cfa_offset 8
        enterq  $0,$1                   # enter frame
        .cfi_def_cfa rbp, 40
        .cfi_offset rbp, -40
        pushq   %r9                     # save int param reg 6
        pushq   %r8                     # save int param reg 5
        pushq   %rcx                    # save int param reg 4
        pushq   %rdx                    # save int param reg 3
        pushq   %rsi                    # save int param reg 2
        pushq   %rdi                    # save int param reg 1
        pushq   %rax                    # save function result
        subq    $48,%rsp                # allocate float param save area
        movsd   %xmm0,40(%rsp)          # save float param reg 1
        movsd   %xmm1,32(%rsp)          # save float param reg 2
        movsd   %xmm2,24(%rsp)          # save float param reg 3
        movsd   %xmm3,16(%rsp)          # save float param reg 4
        movsd   %xmm4,8(%rsp)           # save float param reg 5
        movsd   %xmm5,0(%rsp)           # save float param reg 6
        movq    %rsp,%rax               # copy sp
        subq    $find_getpgm.120+find_getpgm$_tmpspc,%rax # find sp-locals
1:              
        cmpq    %rax,%rsp               # check have reached stack
        je      2f                      # skip if so
        pushq   $0                      # push 0 word for locals
        jmp     1b                      # loop
2:              
        movq    %rsp,16(%rbp)           # set bottom of stack
        andq    $0xfffffffffffffff0,%rsp # align stack
        pushq   %rbx                    # save protected registers and keep aligned
        pushq   %r12
        pushq   %r13
        pushq   %r14
        pushq   %r15
        pushq   %r15                    # second push aligns
#     21:    167: !
#     21:    168: !    getpgm(s);            { the program's directory }
#     21:    169: :22
        .loc 1 22 1 prologue_end
#     22:    170: :23
        .loc 1 23 1
#     23:    171:         sfr     l find_getpgm.123       ! Set function result
#     23:    172:         lao     89                      ! Load global address
#     23:    173:         ldci    256                     ! Load constant(t)
#     23:    174:         swp     8                       ! Swap tos with sos
#     23:    175:         mpc     0 0                     ! Make fat pointer from components
#     23:    176: l find_getpgm.123=0
find_getpgm.123 = 0
#     23:    177:         cup     l services.getpgm@p_vc 1  ! Call user procedure
# assigning:      23:    177:  12: cup  0 rs: [] ~rf: []
# assigning:      23:    175: 248: mpc  0 dr1: rdi dr2: rsi rs: [] ~rf: [rsi, rdi]
# assigning:      23:    172:   5: lao  89 dr1: rdi rs: [] ~rf: [rsi, rdi]
# assigning~:     23:    172:   5: lao  89 r1: rdi rs: [] ~rf: [rsi, rdi]
# assigning:      23:    173: 123: ldci 256 dr1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:     23:    173: 123: ldci 256 r1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:     23:    175: 248: mpc  0 r1: rdi r2: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:     23:    177:  12: cup  0 rs: [] ~rf: [rsi, rdi]
#    expr:
#      23:    177:  12: cup  0 rs: []
#  call start:
#      23:    171: 245: sfr  0 rs: []
#  Parameter:
#      23:    175: 248: mpc  0 r1: rdi r2: rsi rs: []
#     Left:
#      23:    172:   5: lao  89 r1: rdi rs: []
#     right:
#      23:    173: 123: ldci 256 r1: rsi rs: []
# generating:      23:    177:  12: cup  0 rs: []
# generating:      23:    171: 245: sfr  0 rs: []
        movq    %rsp,%rax               # copy stack pointer
        subq    $find_getpgm.123,%rax   # set new stack depth
1:              
        cmpq    %rax,%rsp               # check done
        jbe     2f                      # skip if below stack
        pushq   $0                      # clear stack
        jmp     1b                      # loop
2:              
# generating~:     23:    171: 245: sfr  0 rs: []
# generating:      23:    172:   5: lao  89 r1: rdi rs: []
        leaq    find_getpgm.s(%rip),%rdi # load address of global
# generating~:     23:    172:   5: lao  89 r1: rdi rs: []
# generating:      23:    173: 123: ldci 256 r1: rsi rs: []
        movq    $256,%rsi               # load quad constant
# generating~:     23:    173: 123: ldci 256 r1: rsi rs: []
# generating:      23:    175: 248: mpc  0 r1: rdi r2: rsi rs: []
# generating~:     23:    175: 248: mpc  0 r1: rdi r2: rsi rs: []
        call    services.getpgm$p_vc    # call user procedure
# generating~:     23:    177:  12: cup  0 rs: []
#     23:    178: :23
        .loc 1 23 1
#     23:    179: !    brknam(s, p, n, e);   { last path component -> n }
#     23:    180: :24
        .loc 1 24 1
#     24:    181:         sfr     l find_getpgm.124       ! Set function result
#     24:    182:         lao     89                      ! Load global address
#     24:    183:         ldci    256                     ! Load constant(t)
#     24:    184:         swp     8                       ! Swap tos with sos
#     24:    185:         mpc     0 0                     ! Make fat pointer from components
#     24:    186:         lao     857                     ! Load global address
#     24:    187:         ldci    256                     ! Load constant(t)
#     24:    188:         swp     8                       ! Swap tos with sos
#     24:    189:         mpc     0 0                     ! Make fat pointer from components
#     24:    190:         lao     601                     ! Load global address
#     24:    191:         ldci    256                     ! Load constant(t)
#     24:    192:         swp     8                       ! Swap tos with sos
#     24:    193:         mpc     0 0                     ! Make fat pointer from components
#     24:    194:         lao     345                     ! Load global address
#     24:    195:         ldci    256                     ! Load constant(t)
#     24:    196:         swp     8                       ! Swap tos with sos
#     24:    197:         mpc     0 0                     ! Make fat pointer from components
#     24:    198: l find_getpgm.124=0
find_getpgm.124 = 0
#     24:    199:         cup     l services.brknam@p_vc_vc_vc_vc 4  ! Call user procedure
# assigning:      24:    199:  12: cup  0 rs: [] ~rf: []
# assigning:      24:    185: 248: mpc  0 dr1: rdi dr2: rsi rs: [] ~rf: [rsi, rdi]
# assigning:      24:    182:   5: lao  89 dr1: rdi rs: [] ~rf: [rsi, rdi]
# assigning~:     24:    182:   5: lao  89 r1: rdi rs: [] ~rf: [rsi, rdi]
# assigning:      24:    183: 123: ldci 256 dr1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:     24:    183: 123: ldci 256 r1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:     24:    185: 248: mpc  0 r1: rdi r2: rsi rs: [] ~rf: [rsi, rdi]
# assigning:      24:    189: 248: mpc  0 dr1: rdx dr2: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:      24:    186:   5: lao  857 dr1: rdx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:     24:    186:   5: lao  857 r1: rdx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:      24:    187: 123: ldci 256 dr1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:     24:    187: 123: ldci 256 r1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:     24:    189: 248: mpc  0 r1: rdx r2: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:      24:    193: 248: mpc  0 dr1: r8 dr2: r9 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8, r9]
# assigning:      24:    190:   5: lao  601 dr1: r8 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8, r9]
# assigning~:     24:    190:   5: lao  601 r1: r8 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8, r9]
# assigning:      24:    191: 123: ldci 256 dr1: r9 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8, r9]
# assigning~:     24:    191: 123: ldci 256 r1: r9 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8, r9]
# assigning~:     24:    193: 248: mpc  0 r1: r8 r2: r9 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8, r9]
# assigning:      24:    197: 248: mpc  0 dr1: rbx dr2: r12 rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi, r8, r9, r12]
# assigning:      24:    194:   5: lao  345 dr1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi, r8, r9, r12]
# assigning~:     24:    194:   5: lao  345 r1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi, r8, r9, r12]
# assigning:      24:    195: 123: ldci 256 dr1: r12 rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi, r8, r9, r12]
# assigning~:     24:    195: 123: ldci 256 r1: r12 rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi, r8, r9, r12]
# assigning~:     24:    197: 248: mpc  0 r1: rbx r2: r12 rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi, r8, r9, r12]
# assigning~:     24:    199:  12: cup  0 rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi, r8, r9, r12]
#    expr:
#      24:    199:  12: cup  0 rs: []
#  call start:
#      24:    181: 245: sfr  0 rs: []
#  Parameter:
#      24:    185: 248: mpc  0 r1: rdi r2: rsi rs: []
#     Left:
#      24:    182:   5: lao  89 r1: rdi rs: []
#     right:
#      24:    183: 123: ldci 256 r1: rsi rs: []
#  Parameter:
#      24:    189: 248: mpc  0 r1: rdx r2: rcx rs: []
#     Left:
#      24:    186:   5: lao  857 r1: rdx rs: []
#     right:
#      24:    187: 123: ldci 256 r1: rcx rs: []
#  Parameter:
#      24:    193: 248: mpc  0 r1: r8 r2: r9 rs: []
#     Left:
#      24:    190:   5: lao  601 r1: r8 rs: []
#     right:
#      24:    191: 123: ldci 256 r1: r9 rs: []
#  Parameter:
#      24:    197: 248: mpc  0 r1: rbx r2: r12 rs: []
#     Left:
#      24:    194:   5: lao  345 r1: rbx rs: []
#     right:
#      24:    195: 123: ldci 256 r1: r12 rs: []
# generating:      24:    199:  12: cup  0 rs: []
# generating:      24:    181: 245: sfr  0 rs: []
        movq    %rsp,%rax               # copy stack pointer
        subq    $find_getpgm.124,%rax   # set new stack depth
1:              
        cmpq    %rax,%rsp               # check done
        jbe     2f                      # skip if below stack
        pushq   $0                      # clear stack
        jmp     1b                      # loop
2:              
# generating~:     24:    181: 245: sfr  0 rs: []
# generating:      24:    182:   5: lao  89 r1: rdi rs: []
        leaq    find_getpgm.s(%rip),%rdi # load address of global
# generating~:     24:    182:   5: lao  89 r1: rdi rs: []
# generating:      24:    183: 123: ldci 256 r1: rsi rs: []
        movq    $256,%rsi               # load quad constant
# generating~:     24:    183: 123: ldci 256 r1: rsi rs: []
# generating:      24:    185: 248: mpc  0 r1: rdi r2: rsi rs: []
# generating~:     24:    185: 248: mpc  0 r1: rdi r2: rsi rs: []
# generating:      24:    186:   5: lao  857 r1: rdx rs: []
        leaq    find_getpgm.p(%rip),%rdx # load address of global
# generating~:     24:    186:   5: lao  857 r1: rdx rs: []
# generating:      24:    187: 123: ldci 256 r1: rcx rs: []
        movq    $256,%rcx               # load quad constant
# generating~:     24:    187: 123: ldci 256 r1: rcx rs: []
# generating:      24:    189: 248: mpc  0 r1: rdx r2: rcx rs: []
# generating~:     24:    189: 248: mpc  0 r1: rdx r2: rcx rs: []
# generating:      24:    190:   5: lao  601 r1: r8 rs: []
        leaq    find_getpgm.n(%rip),%r8 # load address of global
# generating~:     24:    190:   5: lao  601 r1: r8 rs: []
# generating:      24:    191: 123: ldci 256 r1: r9 rs: []
        movq    $256,%r9                # load quad constant
# generating~:     24:    191: 123: ldci 256 r1: r9 rs: []
# generating:      24:    193: 248: mpc  0 r1: r8 r2: r9 rs: []
# generating~:     24:    193: 248: mpc  0 r1: r8 r2: r9 rs: []
# generating:      24:    194:   5: lao  345 r1: rbx rs: []
        leaq    find_getpgm.e(%rip),%rbx # load address of global
# generating~:     24:    194:   5: lao  345 r1: rbx rs: []
# generating:      24:    195: 123: ldci 256 r1: r12 rs: []
        movq    $256,%r12               # load quad constant
# generating~:     24:    195: 123: ldci 256 r1: r12 rs: []
# generating:      24:    197: 248: mpc  0 r1: rbx r2: r12 rs: []
# generating~:     24:    197: 248: mpc  0 r1: rbx r2: r12 rs: []
        pushq   %r12                    # place 2nd register on stack
        pushq   %rbx                    # save parameter
        call    services.brknam$p_vc_vc_vc_vc# call user procedure
        addq    $16,%rsp                # remove overflow parameters
# generating~:     24:    199:  12: cup  0 rs: []
#     24:    200: :24
        .loc 1 24 1
#     24:    201: !    writeln(n:*)
#     24:    202: :25
        .loc 1 25 1
#     25:    203:         lao     2                       ! Load global address
#     25:    204:         stra    1 -16                   ! Store local(t)
# assigning:      25:    203:   5: lao  2 rs: [] ~rf: []
# assigning~:     25:    203:   5: lao  2 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#      25:    203:   5: lao  2 r1: rbx rs: []
# generating:      25:    203:   5: lao  2 r1: rbx rs: []
        leaq    globals_start+2(%rip),%rbx # load address of global
# generating~:     25:    203:   5: lao  2 r1: rbx rs: []
# generating:  70: stra      
        movq    %rbx,-16(%rbp)          # store qword
#     25:    205:         lao     601                     ! Load global address
#     25:    206:         ldci    256                     ! Load constant(t)
#     25:    207:         swp     8                       ! Swap tos with sos
#     25:    208:         mpc     0 0                     ! Make fat pointer from components
#     25:    209:         loda    1 -16                   ! Load local value(t)
#     25:    210:         swp     16                      ! Swap tos with sos
#     25:    211:         csp     wrsp                    ! Call system procedure/function: Write passed string to text file
# assigning:      25:    211:  15: csp  65: wrsp rs: [] ~rf: []
# assigning:      25:    209: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     25:    209: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning:      25:    208: 248: mpc  0 dr1: rsi dr2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      25:    205:   5: lao  601 dr1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     25:    205:   5: lao  601 r1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      25:    206: 123: ldci 256 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     25:    206: 123: ldci 256 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     25:    208: 248: mpc  0 r1: rsi r2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     25:    211:  15: csp  65: wrsp rs: [] ~rf: [rdx, rsi, rdi]
#    expr:
#      25:    211:  15: csp  65: wrsp rs: []
#  Parameter:
#      25:    209: 105: loda -16 r1: rdi rs: []
#  Parameter:
#      25:    208: 248: mpc  0 r1: rsi r2: rdx rs: []
#     Left:
#      25:    205:   5: lao  601 r1: rsi rs: []
#     right:
#      25:    206: 123: ldci 256 r1: rdx rs: []
# generating:      25:    211:  15: csp  65: wrsp rs: []
# generating:      25:    209: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     25:    209: 105: loda -16 r1: rdi rs: []
# generating:      25:    205:   5: lao  601 r1: rsi rs: []
        leaq    find_getpgm.n(%rip),%rsi # load address of global
# generating~:     25:    205:   5: lao  601 r1: rsi rs: []
# generating:      25:    206: 123: ldci 256 r1: rdx rs: []
        movq    $256,%rdx               # load quad constant
# generating~:     25:    206: 123: ldci 256 r1: rdx rs: []
# generating:      25:    208: 248: mpc  0 r1: rsi r2: rdx rs: []
# generating~:     25:    208: 248: mpc  0 r1: rsi r2: rdx rs: []
        call    psystem_wrsp            # call system procedure/function
# generating~:     25:    211:  15: csp  65: wrsp rs: []
#     25:    212: !
#     25:    213: ! end.
#     25:    214:         loda    1 -16                   ! Load local value(t)
#     25:    215:         csp     wln                     ! Call system procedure/function: Write next line to text file
# assigning:      25:    215:  15: csp  5: wln  rs: [] ~rf: []
# assigning:      25:    214: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     25:    214: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning~:     25:    215:  15: csp  5: wln  rs: [] ~rf: [rdi]
#    expr:
#      25:    215:  15: csp  5: wln  rs: []
#  Parameter:
#      25:    214: 105: loda -16 r1: rdi rs: []
# generating:      25:    215:  15: csp  5: wln  rs: []
# generating:      25:    214: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     25:    214: 105: loda -16 r1: rdi rs: []
        call    psystem_wln             # call system procedure/function
# generating~:     25:    215:  15: csp  5: wln  rs: []
#     25:    216: :26
        .loc 1 26 1
#     26:    217: :27
        .loc 1 27 1
#     27:    218:         retp    0                       ! Return from procedure/function(t)
# generating:  14: retp      
        popq    %r15                    # undo alignment push
        popq    %r15                    # restore protected registers
        popq    %r14
        popq    %r13
        popq    %r12
        popq    %rbx
        leave                           # undo frame
        .cfi_restore rbp
        .cfi_def_cfa rsp, 32
        addq    $24,%rsp                # remove frame data
        .cfi_def_cfa rsp, 8
        popq    %rcx                    # get return address
        addq    $0,%rsp                 # remove caller parameters
        pushq   %rcx                    # replace return address
        ret                             # return to caller
        .cfi_endproc
.Lfnend_1:
find_getpgm$_tmpspc = 0
#     27:    219: l find_getpgm.120=16
find_getpgm.120 = 16
#     27:    220: l find_getpgm.121=64
find_getpgm.121 = 64
#     27:    221: g       1113
#     27:    222: e       p
#     27:    223: f       0
#     27:    224: q
#
# Constants section
#
        jmp     1f
modnam:
        .string  "find_getpgm"
real_zero:
        .double  0.0
real_int_max:
        .double  9223372036854775807
real_int_min:
        .double  -9223372036854775807
template119:
find_getpgm.119:
        .quad            256
template118:
find_getpgm.118:
        .quad            256
1:
        .bss
#
# Globals section
#
globals_start:
        .zero 1113

#
# DWARF debug info
#
        .section .debug_info,"",@progbits
.Ldw_info_start:
        .long   .Ldw_info_end - .Ldw_info_hdr /* unit length */
.Ldw_info_hdr:
        .short  4 /* DWARF version */
        .long   .Ldw_abbrev_start /* debug_abbrev offset */
        .byte   8 /* address size */
        .uleb128 1 /* DW_TAG_compile_unit */
        .long   .Ldw5
        .short  2 /* language */
        .long   .Ldw6
        .quad   find_getpgm /* DW_AT_low_pc */
        .quad   .Lfnend_1 /* DW_AT_high_pc */
        .long   .Ldw_line_start /* DW_AT_stmt_list */
.Ldw1:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw7
        .byte   5 /* DW_ATE_signed */
        .byte   8 /* byte_size */
.Ldw2:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw8
        .byte   2 /* DW_ATE_boolean */
        .byte   1 /* byte_size */
.Ldw3:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw9
        .byte   8 /* DW_ATE_unsigned_char */
        .byte   1 /* byte_size */
.Ldw4:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw10
        .byte   4 /* DW_ATE_float */
        .byte   8 /* byte_size */
.Ldw11:
        .uleb128 8 /* DW_TAG_array_type */
        .long   .Ldw3 - .Ldw_info_start
.Ldw12:
        .uleb128 9 /* DW_TAG_subrange_type */
        .long   .Ldw1 - .Ldw_info_start
        .sleb128 1 /* lower_bound */
        .sleb128 256 /* upper_bound */
        .byte   0 /* end array children */
        .uleb128 4 /* variable/parameter */
        .long   .Ldw13
        .long   .Ldw11 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+857
.Ldw14:
        .uleb128 8 /* DW_TAG_array_type */
        .long   .Ldw3 - .Ldw_info_start
.Ldw15:
        .uleb128 9 /* DW_TAG_subrange_type */
        .long   .Ldw1 - .Ldw_info_start
        .sleb128 1 /* lower_bound */
        .sleb128 256 /* upper_bound */
        .byte   0 /* end array children */
        .uleb128 4 /* variable/parameter */
        .long   .Ldw16
        .long   .Ldw14 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+601
.Ldw17:
        .uleb128 8 /* DW_TAG_array_type */
        .long   .Ldw3 - .Ldw_info_start
.Ldw18:
        .uleb128 9 /* DW_TAG_subrange_type */
        .long   .Ldw1 - .Ldw_info_start
        .sleb128 1 /* lower_bound */
        .sleb128 256 /* upper_bound */
        .byte   0 /* end array children */
        .uleb128 4 /* variable/parameter */
        .long   .Ldw19
        .long   .Ldw17 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+345
.Ldw20:
        .uleb128 8 /* DW_TAG_array_type */
        .long   .Ldw3 - .Ldw_info_start
.Ldw21:
        .uleb128 9 /* DW_TAG_subrange_type */
        .long   .Ldw1 - .Ldw_info_start
        .sleb128 1 /* lower_bound */
        .sleb128 256 /* upper_bound */
        .byte   0 /* end array children */
        .uleb128 4 /* variable/parameter */
        .long   .Ldw22
        .long   .Ldw20 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+89
        .uleb128 18 /* DW_TAG_subprogram */
        .long   .Ldw6
        .uleb128 1 /* frame_base length */
        .byte   86 /* DW_OP_reg 6 */
        .quad   find_getpgm /* DW_AT_low_pc */
        .quad   .Lfnend_1 /* DW_AT_high_pc */
        .byte   0 /* end compile unit children */
.Ldw_info_end:

#
# DWARF abbreviation table
#
        .section .debug_abbrev,"",@progbits
.Ldw_abbrev_start:
        .uleb128 1 /* abbreviation code */
        .uleb128 17 /* tag */
        .byte   1 /* children */
        .uleb128 37
        .uleb128 14
        .uleb128 19
        .uleb128 5
        .uleb128 3
        .uleb128 14
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .uleb128 16
        .uleb128 23
        .byte   0
        .byte   0
        .uleb128 2 /* abbreviation code */
        .uleb128 36 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 62
        .uleb128 11
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 3 /* abbreviation code */
        .uleb128 46 /* tag */
        .byte   1 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 64
        .uleb128 24
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .byte   0
        .byte   0
        .uleb128 4 /* abbreviation code */
        .uleb128 52 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 5 /* abbreviation code */
        .uleb128 52 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 6 /* abbreviation code */
        .uleb128 5 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 7 /* abbreviation code */
        .uleb128 15 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 8 /* abbreviation code */
        .uleb128 1 /* tag */
        .byte   1 /* children */
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 9 /* abbreviation code */
        .uleb128 33 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 34
        .uleb128 13
        .uleb128 47
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 10 /* abbreviation code */
        .uleb128 19 /* tag */
        .byte   1 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 11
        .uleb128 15
        .byte   0
        .byte   0
        .uleb128 11 /* abbreviation code */
        .uleb128 13 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 56
        .uleb128 15
        .byte   0
        .byte   0
        .uleb128 12 /* abbreviation code */
        .uleb128 4 /* tag */
        .byte   1 /* children */
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 13 /* abbreviation code */
        .uleb128 40 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 28
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 14 /* abbreviation code */
        .uleb128 32 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 15 /* abbreviation code */
        .uleb128 41 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 16 /* abbreviation code */
        .uleb128 51 /* tag */
        .byte   1 /* children */
        .uleb128 21
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 17 /* abbreviation code */
        .uleb128 25 /* tag */
        .byte   1 /* children */
        .uleb128 22
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 18 /* abbreviation code */
        .uleb128 46 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 64
        .uleb128 24
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .byte   0
        .byte   0
        .uleb128 19 /* abbreviation code */
        .uleb128 59 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .byte   0
        .byte   0
        .uleb128 20 /* abbreviation code */
        .uleb128 33 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 34
        .uleb128 7
        .uleb128 47
        .uleb128 7
        .byte   0
        .byte   0
        .uleb128 21 /* abbreviation code */
        .uleb128 15 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .byte   0 /* end abbreviation table */

#
# DWARF string table
#
        .section .debug_str,"MS",@progbits,1
.Ldw_str_start:
.Ldw22:
        .asciz  "s"
.Ldw19:
        .asciz  "e"
.Ldw16:
        .asciz  "n"
.Ldw13:
        .asciz  "p"
.Ldw10:
        .asciz  "real"
.Ldw9:
        .asciz  "char"
.Ldw8:
        .asciz  "boolean"
.Ldw7:
        .asciz  "integer"
.Ldw6:
        .asciz  "find_getpgm"
.Ldw5:
        .asciz  "Pascal-P6 pgen"
