!
! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
!
p       /home/samiam/projects/pascal/pascal-p6/libs/tests/netprobe.pas
o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
! program netprobe(output);
:1
!
! Program netprobe
!
b       p       netprobe
        sfr     l netprobe.6            ! Set function result
l netprobe.6=0
        cup     l netprobe.3 0           ! Call user procedure
        ret                             ! Return code strip
! uses network;
:2
z 0 0 network.addrnet@p_vc_x(0,9223372036854775807)i
z 0 0 network.addrnetv6@p_vc_x(0,9223372036854775807)i_x(0,9223372036854775807)i
z 0 0 network.maxmsg@f_x(0,9223372036854775807)i
z 0 0 network.maxmsgv6@f_x(0,9223372036854775807)i_x(0,9223372036854775807)i
z 0 0 network.relymsg@f_x(0,9223372036854775807)i
z 0 0 network.relymsgv6@f_x(0,9223372036854775807)i_x(0,9223372036854775807)i
z 0 0 network.openmsg@f_x(0,9223372036854775807)i_i_i
z 0 0 network.openmsgv6@f_x(0,9223372036854775807)i_x(0,9223372036854775807)i_i_i
z 0 0 network.wrmsg@p_i_vx(0,255)i
z 0 0 network.rdmsg@f_i_vx(0,255)i
z 0 0 network.clsmsg@p_i
z 0 0 network.waitmsg@f_i_i
z 0 0 network.certmsg@f_i_i_vc
z 0 0 network.opennet@p_fc_fc_x(0,9223372036854775807)i_i_i
z 0 0 network.opennetv6@p_fc_fc_x(0,9223372036854775807)i_x(0,9223372036854775807)i_i_i
z 0 0 network.waitnet@p_fc_fc_i_i
z 0 0 network.certnet@f_fc_i_vc
z 0 0 network.certlistnet@p_fc_i_pr(name:0:pvc,data:8:p12,critical:16:b,fork:20:p2,next:28:p2)
z 0 0 network.certlistmsg@p_i_i_pr(name:0:pvc,data:8:p12,critical:16:b,fork:20:p2,next:28:p2)
z 0 0 network.certlistfree@p_pr(name:0:pvc,data:8:p12,critical:16:b,fork:20:p2,next:28:p2)
! var a: lcardinal;
:3
s       a g 92 x(0,9223372036854775807)i
!     fi, fo: text;
:4
s       fo g 100 fc
s       fi g 102 fc
!     c: char;
:5
s       c g 104 c
! begin
l netprobe.3
:6
:6
        mst     0 l netprobe.36 l netprobe.37 ! Mark(frame) stack
!    addrnet('localhost', a);
:7
        sfr     l netprobe.39           ! Set function result
t       l netprobe.40 1 1
        lca     9 'localhost'           ! Load constant string address
        ldci    9                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        lao     92                      ! Load global address
l netprobe.39=0
        cup     l network.addrnet@p_vc_x(0,9223372036854775807)i 2  ! Call user procedure
:7
!    writeln('addr: ', a:1);
:8
t       l netprobe.41 1 1
        lao     2                       ! Load global address
        stra    1 -16                   ! Store local(t)
        lca     6 'addr:'               ! Load constant string address
        ldci    6                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    1 -16                   ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        loda    1 -16                   ! Load local value(t)
        ldoi    92                      ! Load global value(t)
        ldci    1                       ! Load constant(t)
        csp     wri                     ! Call system procedure/function: Write integer to text file decimal
        loda    1 -16                   ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!    opennet(fi, fo, a, 12399, 0);
:9
        sfr     l netprobe.42           ! Set function result
        lao     102                     ! Load global address
        lao     100                     ! Load global address
        ldoi    92                      ! Load global value(t)
        chki    0 9223372036854775807   ! Bounds check(t)
        ldci    12399                   ! Load constant(t)
        ldci    0                       ! Load constant(t)
l netprobe.42=0
        cup     l network.opennet@p_fc_fc_x(0,9223372036854775807)i_i_i 5  ! Call user procedure
:9
!    writeln(fo, 'hello from pascaline');
:10
        lao     100                     ! Load global address
        stra    1 -16                   ! Store local(t)
t       l netprobe.43 1 1
        lca     20 'hello from pascaline' ! Load constant string address
        ldci    20                      ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    1 -16                   ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        loda    1 -16                   ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!    close(fo);
:11
        lao     100                     ! Load global address
        csp     clst                    ! Call system procedure/function: Close text file
!    write('received: ');
:12
t       l netprobe.44 1 1
        lao     2                       ! Load global address
        stra    1 -16                   ! Store local(t)
        lca     10 'received:'          ! Load constant string address
        ldci    10                      ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    1 -16                   ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
!    while not eoln(fi) do begin read(fi, c); write(c) end;
:13
l netprobe.45
:13
        lao     102                     ! Load global address
        csp     eln                     ! Call system procedure/function: Find eoln of text file
        notb                            ! Not(t)
         fjp l netprobe.46
        lao     102                     ! Load global address
        stra    1 -16                   ! Store local(t)
        lao     104                     ! Load global address
        loda    1 -16                   ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldcc    0                                           ! Load constant(t)
        ldcc    255                                         ! Load constant(t)
        csp     rcb                     ! Call system procedure/function: Read character from text file with range check
        lao     2                       ! Load global address
        stra    1 -16                   ! Store local(t)
        ldoc    104                     ! Load global value(t)
        loda    1 -16                   ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldci    1                       ! Load constant(t)
        csp     wrc                     ! Call system procedure/function: Write character to text file
        ujp     l netprobe.45           ! Unconditional jump
l netprobe.46
:13
!    writeln;
:14
        lao     2                       ! Load global address
        stra    1 -16                   ! Store local(t)
        loda    1 -16                   ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!    close(fi)
:15
        lao     102                     ! Load global address
        csp     clst                    ! Call system procedure/function: Close text file
! end.
:16
        retp    0                       ! Return from procedure/function(t)
l netprobe.36=16
l netprobe.37=40
g       105
e       p
f       0
q
