#
# File generated by P6 Pascal AMD64/gcc 64 bit code generator vs. 0.5.x
#

# Header file locations
inputoff = 0
outputoff = 2
prdoff = 4
prroff = 6
erroroff = 8
listoff = 10
commandoff = 12

# Logical file numbers for header files
inputfn = 1
outputfn = 2
prdfn = 3
prrfn = 4
errorfn = 5
listfn = 6
commandfn = 7

# Error codes
ValueOutOfRange                    = 0
ArrayLengthMatch                   = 1
CaseValueNotFound                  = 2
ZeroDivide                         = 3
InvalidOperand                     = 4
NilPointerDereference              = 5
RealOverflow                       = 6
RealUnderflow                      = 7
RealProcessingFault                = 8
TagValueNotActive                  = 9
TooManyFiles                       = 10
FileIsOpen                         = 11
FileAlreadyNamed                   = 12
FileNotOpen                        = 13
FileModeIncorrect                  = 14
InvalidFieldSpecification          = 15
InvalidRealNumber                  = 16
InvalidFractionSpecification       = 17
InvalidIntegerFormat               = 18
IntegerValueOverflow               = 19
InvalidRealFormat                  = 20
EndOfFile                          = 21
InvalidFilePosition                = 22
FilenameTooLong                    = 23
FileOpenFail                       = 24
FileSIzeFail                       = 25
FileCloseFail                      = 26
FileReadFail                       = 27
FileWriteFail                      = 28
FilePositionFail                   = 29
FileDeleteFail                     = 30
FileNameChangeFail                 = 31
SpaceAllocateFail                  = 32
SpaceReleaseFail                   = 33
SpaceAllocateNegative              = 34
CannotPerformSpecial               = 35
CommandLineTooLong                 = 36
ReadPastEOF                        = 37
FileTransferLengthZero             = 38
FileSizeTooLarge                   = 39
FilenameEmpty                      = 40
CannotOpenStandard                 = 41
TooManyTemporaryFiles              = 42
InputBufferOverflow                = 43
TooManyThreads                     = 44
CannotStartThread                  = 45
InvalidThreadHandle                = 46
CannotStopThread                   = 47
TooManyIntertaskLocks              = 48
InvalidLockHandle                  = 49
LockSequenceFail                   = 50
TooManySignals                     = 51
CannotCreateSignal                 = 52
InvalidSignalHandle                = 53
CannotDeleteSignal                 = 54
CannotSendSignal                   = 55
WaitForSignalFail                  = 56
FieldNotBlank                      = 57
ReadOnWriteOnlyFile                = 58
WriteOnReadOnlyFile                = 59
FileBufferVariableUndefined        = 60
NondecimalRadixOfNegative          = 61
InvalidArgumentToLn                = 62
InvalidArgumentToSqrt              = 63
CannotResetOrRewriteStandardFile   = 64
CannotResetWriteOnlyFile           = 65
CannotRewriteReadOnlyFile          = 66
SetElementOutOfRange               = 67
RealArgumentTooLarge               = 68
BooleanOperatorOfNegative          = 69
InvalidDivisorToMod                = 70
PackElementsOutOfBounds            = 71
UnpackElementsOutOfBounds          = 72
CannotResetClosedTempFile          = 73
ReadCharacterMismatch              = 74
UndefinedLocationAccess            = 75
FunctionNotImplemented             = 76
InvalidInISO7185Mode               = 77
HeapFormatInvalid                  = 78
DisposeOfUninitalizedPointer       = 79
DisposeOfNilPointer                = 80
BadPointerValue                    = 81
BlockAlreadyFreed                  = 82
InvalidStandardProcedureOrFunction = 83
InvalidInstruction                 = 84
NewDisposeTagsMismatch             = 85
PCOutOfRange                       = 86
StoreOverflow                      = 87
StackBalance                       = 88
SetInclusion                       = 89
UninitializedPointer               = 90
DereferenceOfNilPointer            = 91
PointerUsedAfterDispose            = 92
VariantNotActive                   = 93
InvalidCase                        = 94
SystemError                        = 95
ChangeToAllocatedTagfield          = 96
UnhandledException                 = 97
ProgramCodeAssertion               = 98
VarListEmpty                       = 99
ChangeToVarReferencedVariant       = 100
DisposeOfVarReferencedBlock        = 101
VarReferencedFileBufferModified    = 102
ContainerMismatch                  = 103
InvalidContainerLevel              = 104
DisposeOfWithReferencedBlock       = 105
WithBaseListEmpty                  = 106
ExternalsNotEnabled                = 107
MasterException                    = 108


# machine parameters
lendian     =       true /* endian mode */
intsize     =          8 /* size of integer */
intal       =          4 /* alignment of integer */
intdig      =         20 /* number of decimal digits in integer */
inthex      =         16 /* number of hex digits of integer */
realsize    =          8 /* size of real */
realal      =          4 /* alignment of real */
charsize    =          1 /* size of char */
charal      =          1 /* alignment of char */
boolsize    =          1 /* size of boolean */
boolal      =          1 /* alignment of boolean */
ptrsize     =          8 /* size of pointer */
adrsize     =          8 /* size of address */
adral       =          4 /* alignment of address */
setsize     =         32 /* size of set */
setal       =          1 /* alignment of set */
filesize    =          1 /* required runtime space for file (lfn) */
fileidsize  =          1 /* size of the lfn only */
exceptsize  =          1 /* size of exception variable */
exceptal    =          1 /* alignment of exception */
stackal     =          8 /* alignment of stack */
stackelsize =          8 /* stack element size */
maxsize     =         32 /* this is the largest type that can be on the stack */
heapal      =          4 /* alignment for each heap arena */
gbsal       =          4 /* globals area alignment */
sethigh     =        255 /* set highest value */
setlow      =          0 /* set lowest value */
ordmaxchar  =        255 /* character highest value */
ordminchar  =          0 /* character lowest value */
marksize    =         24 /* size of mark */
maxexp      =        308 /* maximum exponent of real */
nilval      =          1 /* value of nil */
maxint      = 9223372036854775807 /* value of maxint on target machine */
markep      =          8 /* (old) maximum frame size */
marksb      =         16 /* stack bottom */
market      =         24 /* current ep */

        .text
#
# Code section
#
#      0:      1: !
#      0:      2: ! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
#      0:      3: !
#      0:      4: p       /home/samiam/projects/pascal/pascal-p6/libs/tests/netprobe.pas
        .section .debug_line,"",@progbits
.Ldw_line_start:
        .text
        .file   "netprobe.pas"
        .file   1 "/home/samiam/projects/pascal/pascal-p6/libs/tests/netprobe.pas"
#      0:      5: o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
#      0:      6: ! program netprobe(output);
#      0:      7: :1
        .loc 1 1 1
#      1:      8: !
#      1:      9: ! Program netprobe
#      1:     10: !
#      1:     11: b       p       netprobe
        .globl  netprobe
        .type   netprobe, @function
netprobe:
        .cfi_startproc
# Align stack
        pushq   %rax
        .cfi_adjust_cfa_offset 8
# Set up default files
        movb    $inputfn,globals_start+inputoff(%rip)
        movb    $outputfn,globals_start+outputoff(%rip)
        movb    $prdfn,globals_start+prdoff(%rip)
        movb    $prrfn,globals_start+prroff(%rip)
        movb    $errorfn,globals_start+erroroff(%rip)
        movb    $listfn,globals_start+listoff(%rip)
        movb    $commandfn,globals_start+commandoff(%rip)
# Call startup code
        call    1f
        popq    %rax
        .cfi_adjust_cfa_offset -8
        sub     %rax,%rax
        ret
        .cfi_endproc
1:
#      1:     12:         sfr     l netprobe.6            ! Set function result
#      1:     13: l netprobe.6=0
netprobe.6 = 0
#      1:     14:         cup     l netprobe.3 0           ! Call user procedure
# assigning:       1:     14:  12: cup  0 rs: [] ~rf: []
# assigning~:      1:     14:  12: cup  0 rs: [] ~rf: []
#    expr:
#       1:     14:  12: cup  0 rs: []
#  call start:
#       1:     12: 245: sfr  0 rs: []
# generating:       1:     14:  12: cup  0 rs: []
# generating:       1:     12: 245: sfr  0 rs: []
        movq    %rsp,%rax               # copy stack pointer
        subq    $netprobe.6,%rax        # set new stack depth
1:              
        cmpq    %rax,%rsp               # check done
        jbe     2f                      # skip if below stack
        pushq   $0                      # clear stack
        jmp     1b                      # loop
2:              
# generating~:      1:     12: 245: sfr  0 rs: []
        call    netprobe.3              # call user procedure
# generating~:      1:     14:  12: cup  0 rs: []
#      1:     15:         ret                             ! Return code strip
        ret      
#      1:     16: ! uses network;
#      1:     17: :2
        .loc 1 2 1
#      2:     18: z 0 0 network.addrnet@p_vc_x(0,9223372036854775807)i
#      2:     19: z 0 0 network.addrnetv6@p_vc_x(0,9223372036854775807)i_x(0,9223372036854775807)i
#      2:     20: z 0 0 network.maxmsg@f_x(0,9223372036854775807)i
#      2:     21: z 0 0 network.maxmsgv6@f_x(0,9223372036854775807)i_x(0,9223372036854775807)i
#      2:     22: z 0 0 network.relymsg@f_x(0,9223372036854775807)i
#      2:     23: z 0 0 network.relymsgv6@f_x(0,9223372036854775807)i_x(0,9223372036854775807)i
#      2:     24: z 0 0 network.openmsg@f_x(0,9223372036854775807)i_i_i
#      2:     25: z 0 0 network.openmsgv6@f_x(0,9223372036854775807)i_x(0,9223372036854775807)i_i_i
#      2:     26: z 0 0 network.wrmsg@p_i_vx(0,255)i
#      2:     27: z 0 0 network.rdmsg@f_i_vx(0,255)i
#      2:     28: z 0 0 network.clsmsg@p_i
#      2:     29: z 0 0 network.waitmsg@f_i_i
#      2:     30: z 0 0 network.certmsg@f_i_i_vc
#      2:     31: z 0 0 network.opennet@p_fc_fc_x(0,9223372036854775807)i_i_i
#      2:     32: z 0 0 network.opennetv6@p_fc_fc_x(0,9223372036854775807)i_x(0,9223372036854775807)i_i_i
#      2:     33: z 0 0 network.waitnet@p_fc_fc_i_i
#      2:     34: z 0 0 network.certnet@f_fc_i_vc
#      2:     35: z 0 0 network.certlistnet@p_fc_i_pr(name:0:pvc,data:8:p12,critical:16:b,fork:20:p2,next:28:p2)
#      2:     36: z 0 0 network.certlistmsg@p_i_i_pr(name:0:pvc,data:8:p12,critical:16:b,fork:20:p2,next:28:p2)
#      2:     37: z 0 0 network.certlistfree@p_pr(name:0:pvc,data:8:p12,critical:16:b,fork:20:p2,next:28:p2)
#      2:     38: ! var a: lcardinal;
#      2:     39: :3
        .loc 1 3 1
#      3:     40: s       a g 92 x(0,9223372036854775807)i
        .globl   netprobe.a
netprobe.a = globals_start+92
#      3:     41: !     fi, fo: text;
#      3:     42: :4
        .loc 1 4 1
#      4:     43: s       fo g 100 fc
        .globl   netprobe.fo
netprobe.fo = globals_start+100
#      4:     44: s       fi g 102 fc
        .globl   netprobe.fi
netprobe.fi = globals_start+102
#      4:     45: !     c: char;
#      4:     46: :5
        .loc 1 5 1
#      5:     47: s       c g 104 c
        .globl   netprobe.c
netprobe.c = globals_start+104
#      5:     48: ! begin
#      5:     49: l netprobe.3
netprobe.3:
#      5:     50: :6
        .loc 1 6 1
#      6:     51: :6
        .loc 1 6 1
#      6:     52:         mst     0 l netprobe.36 l netprobe.37 ! Mark(frame) stack
        .cfi_startproc
# generating:  11: mst       
        pushq   $0                      # place current ep
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place bottom of stack
        .cfi_adjust_cfa_offset 8
        pushq   $0                      # place previous ep
        .cfi_adjust_cfa_offset 8
        enterq  $0,$1                   # enter frame
        .cfi_def_cfa rbp, 40
        .cfi_offset rbp, -40
        pushq   %r9                     # save int param reg 6
        pushq   %r8                     # save int param reg 5
        pushq   %rcx                    # save int param reg 4
        pushq   %rdx                    # save int param reg 3
        pushq   %rsi                    # save int param reg 2
        pushq   %rdi                    # save int param reg 1
        pushq   %rax                    # save function result
        subq    $48,%rsp                # allocate float param save area
        movsd   %xmm0,40(%rsp)          # save float param reg 1
        movsd   %xmm1,32(%rsp)          # save float param reg 2
        movsd   %xmm2,24(%rsp)          # save float param reg 3
        movsd   %xmm3,16(%rsp)          # save float param reg 4
        movsd   %xmm4,8(%rsp)           # save float param reg 5
        movsd   %xmm5,0(%rsp)           # save float param reg 6
        movq    %rsp,%rax               # copy sp
        subq    $netprobe.36+netprobe$_tmpspc,%rax # find sp-locals
1:              
        cmpq    %rax,%rsp               # check have reached stack
        je      2f                      # skip if so
        pushq   $0                      # push 0 word for locals
        jmp     1b                      # loop
2:              
        movq    %rsp,16(%rbp)           # set bottom of stack
        andq    $0xfffffffffffffff0,%rsp # align stack
        pushq   %rbx                    # save protected registers and keep aligned
        pushq   %r12
        pushq   %r13
        pushq   %r14
        pushq   %r15
        pushq   %r15                    # second push aligns
#      6:     53: !    addrnet('localhost', a);
#      6:     54: :7
        .loc 1 7 1 prologue_end
#      7:     55:         sfr     l netprobe.39           ! Set function result
#      7:     56: t       l netprobe.40 1 1
#      7:     57:         lca     9 'localhost'           ! Load constant string address
#      7:     58:         ldci    9                       ! Load constant(t)
#      7:     59:         swp     8                       ! Swap tos with sos
#      7:     60:         mpc     0 0                     ! Make fat pointer from components
#      7:     61:         lao     92                      ! Load global address
#      7:     62: l netprobe.39=0
netprobe.39 = 0
#      7:     63:         cup     l network.addrnet@p_vc_x(0,9223372036854775807)i 2  ! Call user procedure
# assigning:       7:     63:  12: cup  0 rs: [] ~rf: []
# assigning:       7:     60: 248: mpc  0 dr1: rdi dr2: rsi rs: [] ~rf: [rsi, rdi]
# assigning:       7:     57:  56: lca  0 dr1: rdi rs: [] ~rf: [rsi, rdi]
# assigning~:      7:     57:  56: lca  0 r1: rdi rs: [] ~rf: [rsi, rdi]
# assigning:       7:     58: 123: ldci 9 dr1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:      7:     58: 123: ldci 9 r1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:      7:     60: 248: mpc  0 r1: rdi r2: rsi rs: [] ~rf: [rsi, rdi]
# assigning:       7:     61:   5: lao  92 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:      7:     61:   5: lao  92 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:      7:     63:  12: cup  0 rs: [] ~rf: [rdx, rsi, rdi]
#    expr:
#       7:     63:  12: cup  0 rs: []
#  call start:
#       7:     55: 245: sfr  0 rs: []
#  Parameter:
#       7:     60: 248: mpc  0 r1: rdi r2: rsi rs: []
#     Left:
#       7:     57:  56: lca  0 r1: rdi rs: []
#     right:
#       7:     58: 123: ldci 9 r1: rsi rs: []
#  Parameter:
#       7:     61:   5: lao  92 r1: rdx rs: []
# generating:       7:     63:  12: cup  0 rs: []
# generating:       7:     55: 245: sfr  0 rs: []
        movq    %rsp,%rax               # copy stack pointer
        subq    $netprobe.39,%rax       # set new stack depth
1:              
        cmpq    %rax,%rsp               # check done
        jbe     2f                      # skip if below stack
        pushq   $0                      # clear stack
        jmp     1b                      # loop
2:              
# generating~:      7:     55: 245: sfr  0 rs: []
# generating:       7:     57:  56: lca  0 r1: rdi rs: []
        leaq    string1(%rip),%rdi      # load string constant address
# generating~:      7:     57:  56: lca  0 r1: rdi rs: []
# generating:       7:     58: 123: ldci 9 r1: rsi rs: []
        movq    $9,%rsi                 # load quad constant
# generating~:      7:     58: 123: ldci 9 r1: rsi rs: []
# generating:       7:     60: 248: mpc  0 r1: rdi r2: rsi rs: []
# generating~:      7:     60: 248: mpc  0 r1: rdi r2: rsi rs: []
# generating:       7:     61:   5: lao  92 r1: rdx rs: []
        leaq    netprobe.a(%rip),%rdx   # load address of global
# generating~:      7:     61:   5: lao  92 r1: rdx rs: []
        call    network.addrnet$p_vc_x$0$9223372036854775807$i# call user procedure
# generating~:      7:     63:  12: cup  0 rs: []
#      7:     64: :7
        .loc 1 7 1
#      7:     65: !    writeln('addr: ', a:1);
#      7:     66: :8
        .loc 1 8 1
#      8:     67: t       l netprobe.41 1 1
#      8:     68:         lao     2                       ! Load global address
#      8:     69:         stra    1 -16                   ! Store local(t)
# assigning:       8:     68:   5: lao  2 rs: [] ~rf: []
# assigning~:      8:     68:   5: lao  2 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#       8:     68:   5: lao  2 r1: rbx rs: []
# generating:       8:     68:   5: lao  2 r1: rbx rs: []
        leaq    globals_start+2(%rip),%rbx # load address of global
# generating~:      8:     68:   5: lao  2 r1: rbx rs: []
# generating:  70: stra      
        movq    %rbx,-16(%rbp)          # store qword
#      8:     70:         lca     6 'addr:'               ! Load constant string address
#      8:     71:         ldci    6                       ! Load constant(t)
#      8:     72:         swp     8                       ! Swap tos with sos
#      8:     73:         mpc     0 0                     ! Make fat pointer from components
#      8:     74:         loda    1 -16                   ! Load local value(t)
#      8:     75:         swp     16                      ! Swap tos with sos
#      8:     76:         cpl                             ! Copy length from complex pointer
#      8:     77:         csp     wrs                     ! Call system procedure/function: Write string to text file
# assigning:       8:     77:  15: csp  6: wrs  rs: [] ~rf: []
# assigning:       8:     74: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:      8:     74: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning:       8:     73: 248: mpc  0 dr1: rsi dr2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:       8:     70:  56: lca  0 dr1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:      8:     70:  56: lca  0 r1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning:       8:     71: 123: ldci 6 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:      8:     71: 123: ldci 6 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:      8:     73: 248: mpc  0 r1: rsi r2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:       8:     76: 251: cpl  0 dr1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:       8:     73: 248: mpc  0 dr2: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:       8:     70:  56: lca  0 dr1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:      8:     70:  56: lca  0 r1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning:       8:     71: 123: ldci 6 dr1: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:      8:     71: 123: ldci 6 r1: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:      8:     73: 248: mpc  0 r1: rbx r2: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:      8:     76: 251: cpl  0 r1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:      8:     77:  15: csp  6: wrs  rs: [] ~rf: [rcx, rdx, rsi, rdi]
#    expr:
#       8:     77:  15: csp  6: wrs  rs: []
#  Parameter:
#       8:     74: 105: loda -16 r1: rdi rs: []
#  Parameter:
#       8:     73: 248: mpc  0 r1: rsi r2: rdx rs: []
#     Left:
#       8:     70:  56: lca  0 r1: rsi rs: []
#     right:
#       8:     71: 123: ldci 6 r1: rdx rs: []
#  Parameter:
#       8:     76: 251: cpl  0 r1: rcx rs: []
#     Left:
#       8:     73: 248: mpc  0 r1: rbx r2: rcx rs: []
#        Left:
#       8:     70:  56: lca  0 r1: rbx rs: []
#        right:
#       8:     71: 123: ldci 6 r1: rcx rs: []
# generating:       8:     77:  15: csp  6: wrs  rs: []
# generating:       8:     74: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:      8:     74: 105: loda -16 r1: rdi rs: []
# generating:       8:     70:  56: lca  0 r1: rsi rs: []
        leaq    string2(%rip),%rsi      # load string constant address
# generating~:      8:     70:  56: lca  0 r1: rsi rs: []
# generating:       8:     71: 123: ldci 6 r1: rdx rs: []
        movq    $6,%rdx                 # load quad constant
# generating~:      8:     71: 123: ldci 6 r1: rdx rs: []
# generating:       8:     73: 248: mpc  0 r1: rsi r2: rdx rs: []
# generating~:      8:     73: 248: mpc  0 r1: rsi r2: rdx rs: []
# generating:       8:     70:  56: lca  0 r1: rbx rs: []
        leaq    string2(%rip),%rbx      # load string constant address
# generating~:      8:     70:  56: lca  0 r1: rbx rs: []
# generating:       8:     71: 123: ldci 6 r1: rcx rs: []
        movq    $6,%rcx                 # load quad constant
# generating~:      8:     71: 123: ldci 6 r1: rcx rs: []
# generating:       8:     73: 248: mpc  0 r1: rbx r2: rcx rs: []
# generating~:      8:     73: 248: mpc  0 r1: rbx r2: rcx rs: []
# generating:       8:     76: 251: cpl  0 r1: rcx rs: []
# generating~:      8:     76: 251: cpl  0 r1: rcx rs: []
        call    psystem_wrs             # call system procedure/function
# generating~:      8:     77:  15: csp  6: wrs  rs: []
#      8:     78:         loda    1 -16                   ! Load local value(t)
#      8:     79:         ldoi    92                      ! Load global value(t)
#      8:     80:         ldci    1                       ! Load constant(t)
#      8:     81:         csp     wri                     ! Call system procedure/function: Write integer to text file decimal
# assigning:       8:     81:  15: csp  8: wri  rs: [] ~rf: []
# assigning:       8:     78: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:      8:     78: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning:       8:     79:   1: ldoi 92 dr1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:      8:     79:   1: ldoi 92 r1: rsi rs: [] ~rf: [rsi, rdi]
# assigning:       8:     80: 123: ldci 1 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:      8:     80: 123: ldci 1 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:      8:     81:  15: csp  8: wri  rs: [] ~rf: [rdx, rsi, rdi]
#    expr:
#       8:     81:  15: csp  8: wri  rs: []
#  Parameter:
#       8:     78: 105: loda -16 r1: rdi rs: []
#  Parameter:
#       8:     79:   1: ldoi 92 r1: rsi rs: []
#  Parameter:
#       8:     80: 123: ldci 1 r1: rdx rs: []
# generating:       8:     81:  15: csp  8: wri  rs: []
# generating:       8:     78: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:      8:     78: 105: loda -16 r1: rdi rs: []
# generating:       8:     79:   1: ldoi 92 r1: rsi rs: []
        movq    netprobe.a(%rip),%rsi   # load global quad
# generating~:      8:     79:   1: ldoi 92 r1: rsi rs: []
# generating:       8:     80: 123: ldci 1 r1: rdx rs: []
        movq    $1,%rdx                 # load quad constant
# generating~:      8:     80: 123: ldci 1 r1: rdx rs: []
        call    psystem_wri             # call system procedure/function
# generating~:      8:     81:  15: csp  8: wri  rs: []
#      8:     82:         loda    1 -16                   ! Load local value(t)
#      8:     83:         csp     wln                     ! Call system procedure/function: Write next line to text file
# assigning:       8:     83:  15: csp  5: wln  rs: [] ~rf: []
# assigning:       8:     82: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:      8:     82: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning~:      8:     83:  15: csp  5: wln  rs: [] ~rf: [rdi]
#    expr:
#       8:     83:  15: csp  5: wln  rs: []
#  Parameter:
#       8:     82: 105: loda -16 r1: rdi rs: []
# generating:       8:     83:  15: csp  5: wln  rs: []
# generating:       8:     82: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:      8:     82: 105: loda -16 r1: rdi rs: []
        call    psystem_wln             # call system procedure/function
# generating~:      8:     83:  15: csp  5: wln  rs: []
#      8:     84: !    opennet(fi, fo, a, 12399, 0);
#      8:     85: :9
        .loc 1 9 1
#      9:     86:         sfr     l netprobe.42           ! Set function result
#      9:     87:         lao     102                     ! Load global address
#      9:     88:         lao     100                     ! Load global address
#      9:     89:         ldoi    92                      ! Load global value(t)
#      9:     90:         chki    0 9223372036854775807   ! Bounds check(t)
#      9:     91:         ldci    12399                   ! Load constant(t)
#      9:     92:         ldci    0                       ! Load constant(t)
#      9:     93: l netprobe.42=0
netprobe.42 = 0
#      9:     94:         cup     l network.opennet@p_fc_fc_x(0,9223372036854775807)i_i_i 5  ! Call user procedure
# assigning:       9:     94:  12: cup  0 rs: [] ~rf: []
# assigning:       9:     87:   5: lao  102 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:      9:     87:   5: lao  102 r1: rdi rs: [] ~rf: [rdi]
# assigning:       9:     88:   5: lao  100 dr1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:      9:     88:   5: lao  100 r1: rsi rs: [] ~rf: [rsi, rdi]
# assigning:       9:     90:  26: chki 0 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:       9:     89:   1: ldoi 92 dr1: rdx rs: [] ~rf: [rbx, rdx, rsi, rdi]
# assigning~:      9:     89:   1: ldoi 92 r1: rdx rs: [] ~rf: [rbx, rdx, rsi, rdi]
# assigning~:      9:     90:  26: chki 0 r1: rdx t1: rbx rs: [] ~rf: [rbx, rdx, rsi, rdi]
# assigning:       9:     91: 123: ldci 12399 dr1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:      9:     91: 123: ldci 12399 r1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:       9:     92: 123: ldci 0 dr1: r8 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8]
# assigning~:      9:     92: 123: ldci 0 r1: r8 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8]
# assigning~:      9:     94:  12: cup  0 rs: [] ~rf: [rcx, rdx, rsi, rdi, r8]
#    expr:
#       9:     94:  12: cup  0 rs: []
#  call start:
#       9:     86: 245: sfr  0 rs: []
#  Parameter:
#       9:     87:   5: lao  102 r1: rdi rs: []
#  Parameter:
#       9:     88:   5: lao  100 r1: rsi rs: []
#  Parameter:
#       9:     90:  26: chki 0 r1: rdx t1: rbx rs: []
#     Left:
#       9:     89:   1: ldoi 92 r1: rdx rs: []
#  Parameter:
#       9:     91: 123: ldci 12399 r1: rcx rs: []
#  Parameter:
#       9:     92: 123: ldci 0 r1: r8 rs: []
# generating:       9:     94:  12: cup  0 rs: []
# generating:       9:     86: 245: sfr  0 rs: []
        movq    %rsp,%rax               # copy stack pointer
        subq    $netprobe.42,%rax       # set new stack depth
1:              
        cmpq    %rax,%rsp               # check done
        jbe     2f                      # skip if below stack
        pushq   $0                      # clear stack
        jmp     1b                      # loop
2:              
# generating~:      9:     86: 245: sfr  0 rs: []
# generating:       9:     87:   5: lao  102 r1: rdi rs: []
        leaq    netprobe.fi(%rip),%rdi  # load address of global
# generating~:      9:     87:   5: lao  102 r1: rdi rs: []
# generating:       9:     88:   5: lao  100 r1: rsi rs: []
        leaq    netprobe.fo(%rip),%rsi  # load address of global
# generating~:      9:     88:   5: lao  100 r1: rsi rs: []
# generating:       9:     89:   1: ldoi 92 r1: rdx rs: []
        movq    netprobe.a(%rip),%rdx   # load global quad
# generating~:      9:     89:   1: ldoi 92 r1: rdx rs: []
# generating:       9:     90:  26: chki 0 r1: rdx t1: rbx rs: []
        movq    $0,%rbx                 # load low bound
        cmpq    %rbx,%rdx               # compare
        jge     1f                      # skip if greater or equal
        leaq    modnam(%rip),%rdi       # load module name
        movq    $9,%rsi                 # load line number
        movq    $ValueOutOfRange,%rdx   # load error code
        call    psystem_errore          # process error
1:               
        movq    $9223372036854775807,%rbx # load high bound
        cmpq    %rbx,%rdx               # compare
        jle     1f                      # skip if less or equal
        leaq    modnam(%rip),%rdi       # load module name
        movq    $9,%rsi                 # load line number
        movq    $ValueOutOfRange,%rdx   # load error code
        call    psystem_errore          # process error
1:              
# generating~:      9:     90:  26: chki 0 r1: rdx t1: rbx rs: []
# generating:       9:     91: 123: ldci 12399 r1: rcx rs: []
        movq    $12399,%rcx             # load quad constant
# generating~:      9:     91: 123: ldci 12399 r1: rcx rs: []
# generating:       9:     92: 123: ldci 0 r1: r8 rs: []
        movq    $0,%r8                  # load quad constant
# generating~:      9:     92: 123: ldci 0 r1: r8 rs: []
        call    network.opennet$p_fc_fc_x$0$9223372036854775807$i_i_i# call user procedure
# generating~:      9:     94:  12: cup  0 rs: []
#      9:     95: :9
        .loc 1 9 1
#      9:     96: !    writeln(fo, 'hello from pascaline');
#      9:     97: :10
        .loc 1 10 1
#     10:     98:         lao     100                     ! Load global address
#     10:     99:         stra    1 -16                   ! Store local(t)
# assigning:      10:     98:   5: lao  100 rs: [] ~rf: []
# assigning~:     10:     98:   5: lao  100 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#      10:     98:   5: lao  100 r1: rbx rs: []
# generating:      10:     98:   5: lao  100 r1: rbx rs: []
        leaq    netprobe.fo(%rip),%rbx  # load address of global
# generating~:     10:     98:   5: lao  100 r1: rbx rs: []
# generating:  70: stra      
        movq    %rbx,-16(%rbp)          # store qword
#     10:    100: t       l netprobe.43 1 1
#     10:    101:         lca     20 'hello from pascaline' ! Load constant string address
#     10:    102:         ldci    20                      ! Load constant(t)
#     10:    103:         swp     8                       ! Swap tos with sos
#     10:    104:         mpc     0 0                     ! Make fat pointer from components
#     10:    105:         loda    1 -16                   ! Load local value(t)
#     10:    106:         swp     16                      ! Swap tos with sos
#     10:    107:         cpl                             ! Copy length from complex pointer
#     10:    108:         csp     wrs                     ! Call system procedure/function: Write string to text file
# assigning:      10:    108:  15: csp  6: wrs  rs: [] ~rf: []
# assigning:      10:    105: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     10:    105: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning:      10:    104: 248: mpc  0 dr1: rsi dr2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      10:    101:  56: lca  0 dr1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     10:    101:  56: lca  0 r1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      10:    102: 123: ldci 20 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     10:    102: 123: ldci 20 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     10:    104: 248: mpc  0 r1: rsi r2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      10:    107: 251: cpl  0 dr1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:      10:    104: 248: mpc  0 dr2: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:      10:    101:  56: lca  0 dr1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     10:    101:  56: lca  0 r1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning:      10:    102: 123: ldci 20 dr1: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     10:    102: 123: ldci 20 r1: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     10:    104: 248: mpc  0 r1: rbx r2: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     10:    107: 251: cpl  0 r1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:     10:    108:  15: csp  6: wrs  rs: [] ~rf: [rcx, rdx, rsi, rdi]
#    expr:
#      10:    108:  15: csp  6: wrs  rs: []
#  Parameter:
#      10:    105: 105: loda -16 r1: rdi rs: []
#  Parameter:
#      10:    104: 248: mpc  0 r1: rsi r2: rdx rs: []
#     Left:
#      10:    101:  56: lca  0 r1: rsi rs: []
#     right:
#      10:    102: 123: ldci 20 r1: rdx rs: []
#  Parameter:
#      10:    107: 251: cpl  0 r1: rcx rs: []
#     Left:
#      10:    104: 248: mpc  0 r1: rbx r2: rcx rs: []
#        Left:
#      10:    101:  56: lca  0 r1: rbx rs: []
#        right:
#      10:    102: 123: ldci 20 r1: rcx rs: []
# generating:      10:    108:  15: csp  6: wrs  rs: []
# generating:      10:    105: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     10:    105: 105: loda -16 r1: rdi rs: []
# generating:      10:    101:  56: lca  0 r1: rsi rs: []
        leaq    string3(%rip),%rsi      # load string constant address
# generating~:     10:    101:  56: lca  0 r1: rsi rs: []
# generating:      10:    102: 123: ldci 20 r1: rdx rs: []
        movq    $20,%rdx                # load quad constant
# generating~:     10:    102: 123: ldci 20 r1: rdx rs: []
# generating:      10:    104: 248: mpc  0 r1: rsi r2: rdx rs: []
# generating~:     10:    104: 248: mpc  0 r1: rsi r2: rdx rs: []
# generating:      10:    101:  56: lca  0 r1: rbx rs: []
        leaq    string3(%rip),%rbx      # load string constant address
# generating~:     10:    101:  56: lca  0 r1: rbx rs: []
# generating:      10:    102: 123: ldci 20 r1: rcx rs: []
        movq    $20,%rcx                # load quad constant
# generating~:     10:    102: 123: ldci 20 r1: rcx rs: []
# generating:      10:    104: 248: mpc  0 r1: rbx r2: rcx rs: []
# generating~:     10:    104: 248: mpc  0 r1: rbx r2: rcx rs: []
# generating:      10:    107: 251: cpl  0 r1: rcx rs: []
# generating~:     10:    107: 251: cpl  0 r1: rcx rs: []
        call    psystem_wrs             # call system procedure/function
# generating~:     10:    108:  15: csp  6: wrs  rs: []
#     10:    109:         loda    1 -16                   ! Load local value(t)
#     10:    110:         csp     wln                     ! Call system procedure/function: Write next line to text file
# assigning:      10:    110:  15: csp  5: wln  rs: [] ~rf: []
# assigning:      10:    109: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     10:    109: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning~:     10:    110:  15: csp  5: wln  rs: [] ~rf: [rdi]
#    expr:
#      10:    110:  15: csp  5: wln  rs: []
#  Parameter:
#      10:    109: 105: loda -16 r1: rdi rs: []
# generating:      10:    110:  15: csp  5: wln  rs: []
# generating:      10:    109: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     10:    109: 105: loda -16 r1: rdi rs: []
        call    psystem_wln             # call system procedure/function
# generating~:     10:    110:  15: csp  5: wln  rs: []
#     10:    111: !    close(fo);
#     10:    112: :11
        .loc 1 11 1
#     11:    113:         lao     100                     ! Load global address
#     11:    114:         csp     clst                    ! Call system procedure/function: Close text file
# assigning:      11:    114:  15: csp  47: clst rs: [] ~rf: []
# assigning:      11:    113:   5: lao  100 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     11:    113:   5: lao  100 r1: rdi rs: [] ~rf: [rdi]
# assigning~:     11:    114:  15: csp  47: clst rs: [] ~rf: [rdi]
#    expr:
#      11:    114:  15: csp  47: clst rs: []
#  Parameter:
#      11:    113:   5: lao  100 r1: rdi rs: []
# generating:      11:    114:  15: csp  47: clst rs: []
# generating:      11:    113:   5: lao  100 r1: rdi rs: []
        leaq    netprobe.fo(%rip),%rdi  # load address of global
# generating~:     11:    113:   5: lao  100 r1: rdi rs: []
        call    psystem_clst            # call system procedure/function
# generating~:     11:    114:  15: csp  47: clst rs: []
#     11:    115: !    write('received: ');
#     11:    116: :12
        .loc 1 12 1
#     12:    117: t       l netprobe.44 1 1
#     12:    118:         lao     2                       ! Load global address
#     12:    119:         stra    1 -16                   ! Store local(t)
# assigning:      12:    118:   5: lao  2 rs: [] ~rf: []
# assigning~:     12:    118:   5: lao  2 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#      12:    118:   5: lao  2 r1: rbx rs: []
# generating:      12:    118:   5: lao  2 r1: rbx rs: []
        leaq    globals_start+2(%rip),%rbx # load address of global
# generating~:     12:    118:   5: lao  2 r1: rbx rs: []
# generating:  70: stra      
        movq    %rbx,-16(%rbp)          # store qword
#     12:    120:         lca     10 'received:'          ! Load constant string address
#     12:    121:         ldci    10                      ! Load constant(t)
#     12:    122:         swp     8                       ! Swap tos with sos
#     12:    123:         mpc     0 0                     ! Make fat pointer from components
#     12:    124:         loda    1 -16                   ! Load local value(t)
#     12:    125:         swp     16                      ! Swap tos with sos
#     12:    126:         cpl                             ! Copy length from complex pointer
#     12:    127:         csp     wrs                     ! Call system procedure/function: Write string to text file
# assigning:      12:    127:  15: csp  6: wrs  rs: [] ~rf: []
# assigning:      12:    124: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     12:    124: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning:      12:    123: 248: mpc  0 dr1: rsi dr2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      12:    120:  56: lca  0 dr1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     12:    120:  56: lca  0 r1: rsi rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      12:    121: 123: ldci 10 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     12:    121: 123: ldci 10 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     12:    123: 248: mpc  0 r1: rsi r2: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      12:    126: 251: cpl  0 dr1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:      12:    123: 248: mpc  0 dr2: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning:      12:    120:  56: lca  0 dr1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     12:    120:  56: lca  0 r1: rbx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning:      12:    121: 123: ldci 10 dr1: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     12:    121: 123: ldci 10 r1: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     12:    123: 248: mpc  0 r1: rbx r2: rcx rs: [] ~rf: [rbx, rcx, rdx, rsi, rdi]
# assigning~:     12:    126: 251: cpl  0 r1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:     12:    127:  15: csp  6: wrs  rs: [] ~rf: [rcx, rdx, rsi, rdi]
#    expr:
#      12:    127:  15: csp  6: wrs  rs: []
#  Parameter:
#      12:    124: 105: loda -16 r1: rdi rs: []
#  Parameter:
#      12:    123: 248: mpc  0 r1: rsi r2: rdx rs: []
#     Left:
#      12:    120:  56: lca  0 r1: rsi rs: []
#     right:
#      12:    121: 123: ldci 10 r1: rdx rs: []
#  Parameter:
#      12:    126: 251: cpl  0 r1: rcx rs: []
#     Left:
#      12:    123: 248: mpc  0 r1: rbx r2: rcx rs: []
#        Left:
#      12:    120:  56: lca  0 r1: rbx rs: []
#        right:
#      12:    121: 123: ldci 10 r1: rcx rs: []
# generating:      12:    127:  15: csp  6: wrs  rs: []
# generating:      12:    124: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     12:    124: 105: loda -16 r1: rdi rs: []
# generating:      12:    120:  56: lca  0 r1: rsi rs: []
        leaq    string4(%rip),%rsi      # load string constant address
# generating~:     12:    120:  56: lca  0 r1: rsi rs: []
# generating:      12:    121: 123: ldci 10 r1: rdx rs: []
        movq    $10,%rdx                # load quad constant
# generating~:     12:    121: 123: ldci 10 r1: rdx rs: []
# generating:      12:    123: 248: mpc  0 r1: rsi r2: rdx rs: []
# generating~:     12:    123: 248: mpc  0 r1: rsi r2: rdx rs: []
# generating:      12:    120:  56: lca  0 r1: rbx rs: []
        leaq    string4(%rip),%rbx      # load string constant address
# generating~:     12:    120:  56: lca  0 r1: rbx rs: []
# generating:      12:    121: 123: ldci 10 r1: rcx rs: []
        movq    $10,%rcx                # load quad constant
# generating~:     12:    121: 123: ldci 10 r1: rcx rs: []
# generating:      12:    123: 248: mpc  0 r1: rbx r2: rcx rs: []
# generating~:     12:    123: 248: mpc  0 r1: rbx r2: rcx rs: []
# generating:      12:    126: 251: cpl  0 r1: rcx rs: []
# generating~:     12:    126: 251: cpl  0 r1: rcx rs: []
        call    psystem_wrs             # call system procedure/function
# generating~:     12:    127:  15: csp  6: wrs  rs: []
#     12:    128: !    while not eoln(fi) do begin read(fi, c); write(c) end;
#     12:    129: :13
        .loc 1 13 1
#     13:    130: l netprobe.45
netprobe.45:
#     13:    131: :13
        .loc 1 13 1
#     13:    132:         lao     102                     ! Load global address
#     13:    133:         csp     eln                     ! Call system procedure/function: Find eoln of text file
#     13:    134:         notb                            ! Not(t)
#     13:    135:          fjp l netprobe.46
# assigning:      13:    134:  42: notb 0 rs: [] ~rf: []
# assigning:      13:    133:  15: csp  7: eln  dr1: rbx rs: [] ~rf: [rbx]
# assigning:      13:    132:   5: lao  102 dr1: rdi rs: [] ~rf: [rbx, rdi]
# assigning~:     13:    132:   5: lao  102 r1: rdi rs: [] ~rf: [rbx, rdi]
# assigning~:     13:    133:  15: csp  7: eln  r1: rbx rs: [rax] ~rf: [rbx, rdi]
# assigning~:     13:    134:  42: notb 0 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#      13:    134:  42: notb 0 r1: rbx rs: []
#  Left:
#      13:    133:  15: csp  7: eln  r1: rbx rs: [rax]
#     Parameter:
#      13:    132:   5: lao  102 r1: rdi rs: []
        pushq   %rax                    # save used register
# generating:      13:    133:  15: csp  7: eln  r1: rbx rs: [rax]
# generating:      13:    132:   5: lao  102 r1: rdi rs: []
        leaq    netprobe.fi(%rip),%rdi  # load address of global
# generating~:     13:    132:   5: lao  102 r1: rdi rs: []
        pushq   %rbx                    # align
        call    psystem_eln             # call system procedure/function
        popq    %rbx                    # drop alignment
        movq    %rax,%rbx               # place result
        popq    %rax                    # restore used quad register
# generating~:     13:    133:  15: csp  7: eln  r1: rbx rs: [rax]
# generating:      13:    134:  42: notb 0 r1: rbx rs: []
        orq     %rbx,%rbx               # test boolean
        movq    $1,%rbx                 # set true
        jz      1f                      # skip if so
        movq    $0,%rbx                 # otherwise set false
1:              
# generating~:     13:    134:  42: notb 0 r1: rbx rs: []
# generating:  24: fjp       
        orb     %bl,%bl                 # move boolean to flags
        jz      netprobe.46             # go if false
#     13:    136:         lao     102                     ! Load global address
#     13:    137:         stra    1 -16                   ! Store local(t)
# assigning:      13:    136:   5: lao  102 rs: [] ~rf: []
# assigning~:     13:    136:   5: lao  102 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#      13:    136:   5: lao  102 r1: rbx rs: []
# generating:      13:    136:   5: lao  102 r1: rbx rs: []
        leaq    netprobe.fi(%rip),%rbx  # load address of global
# generating~:     13:    136:   5: lao  102 r1: rbx rs: []
# generating:  70: stra      
        movq    %rbx,-16(%rbp)          # store qword
#     13:    138:         lao     104                     ! Load global address
#     13:    139:         loda    1 -16                   ! Load local value(t)
#     13:    140:         swp     8                       ! Swap tos with sos
#     13:    141:         ldcc    0                                           ! Load constant(t)
#     13:    142:         ldcc    255                                         ! Load constant(t)
#     13:    143:         csp     rcb                     ! Call system procedure/function: Read character from text file with range check
# assigning:      13:    143:  15: csp  38: rcb  rs: [] ~rf: []
# assigning:      13:    139: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     13:    139: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning:      13:    138:   5: lao  104 dr1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:     13:    138:   5: lao  104 r1: rsi rs: [] ~rf: [rsi, rdi]
# assigning:      13:    141: 127: ldcc 0 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     13:    141: 127: ldcc 0 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning:      13:    142: 127: ldcc 255 dr1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:     13:    142: 127: ldcc 255 r1: rcx rs: [] ~rf: [rcx, rdx, rsi, rdi]
# assigning~:     13:    143:  15: csp  38: rcb  rs: [] ~rf: [rcx, rdx, rsi, rdi]
#    expr:
#      13:    143:  15: csp  38: rcb  rs: []
#  Parameter:
#      13:    139: 105: loda -16 r1: rdi rs: []
#  Parameter:
#      13:    138:   5: lao  104 r1: rsi rs: []
#  Parameter:
#      13:    141: 127: ldcc 0 r1: rdx rs: []
#  Parameter:
#      13:    142: 127: ldcc 255 r1: rcx rs: []
# generating:      13:    143:  15: csp  38: rcb  rs: []
# generating:      13:    139: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     13:    139: 105: loda -16 r1: rdi rs: []
# generating:      13:    138:   5: lao  104 r1: rsi rs: []
        leaq    netprobe.c(%rip),%rsi   # load address of global
# generating~:     13:    138:   5: lao  104 r1: rsi rs: []
# generating:      13:    141: 127: ldcc 0 r1: rdx rs: []
        movq    $0,%rdx                 # load quad constant
# generating~:     13:    141: 127: ldcc 0 r1: rdx rs: []
# generating:      13:    142: 127: ldcc 255 r1: rcx rs: []
        movq    $255,%rcx               # load quad constant
# generating~:     13:    142: 127: ldcc 255 r1: rcx rs: []
        call    psystem_rcb             # call system procedure/function
# generating~:     13:    143:  15: csp  38: rcb  rs: []
#     13:    144:         lao     2                       ! Load global address
#     13:    145:         stra    1 -16                   ! Store local(t)
# assigning:      13:    144:   5: lao  2 rs: [] ~rf: []
# assigning~:     13:    144:   5: lao  2 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#      13:    144:   5: lao  2 r1: rbx rs: []
# generating:      13:    144:   5: lao  2 r1: rbx rs: []
        leaq    globals_start+2(%rip),%rbx # load address of global
# generating~:     13:    144:   5: lao  2 r1: rbx rs: []
# generating:  70: stra      
        movq    %rbx,-16(%rbp)          # store qword
#     13:    146:         ldoc    104                     ! Load global value(t)
#     13:    147:         loda    1 -16                   ! Load local value(t)
#     13:    148:         swp     8                       ! Swap tos with sos
#     13:    149:         ldci    1                       ! Load constant(t)
#     13:    150:         csp     wrc                     ! Call system procedure/function: Write character to text file
# assigning:      13:    150:  15: csp  10: wrc  rs: [] ~rf: []
# assigning:      13:    147: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     13:    147: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning:      13:    146:  69: ldoc 104 dr1: rsi rs: [] ~rf: [rsi, rdi]
# assigning~:     13:    146:  69: ldoc 104 r1: rsi rs: [] ~rf: [rsi, rdi]
# assigning:      13:    149: 123: ldci 1 dr1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     13:    149: 123: ldci 1 r1: rdx rs: [] ~rf: [rdx, rsi, rdi]
# assigning~:     13:    150:  15: csp  10: wrc  rs: [] ~rf: [rdx, rsi, rdi]
#    expr:
#      13:    150:  15: csp  10: wrc  rs: []
#  Parameter:
#      13:    147: 105: loda -16 r1: rdi rs: []
#  Parameter:
#      13:    146:  69: ldoc 104 r1: rsi rs: []
#  Parameter:
#      13:    149: 123: ldci 1 r1: rdx rs: []
# generating:      13:    150:  15: csp  10: wrc  rs: []
# generating:      13:    147: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     13:    147: 105: loda -16 r1: rdi rs: []
# generating:      13:    146:  69: ldoc 104 r1: rsi rs: []
        movzx   netprobe.c(%rip),%rsi   # load and zero extend global byte
# generating~:     13:    146:  69: ldoc 104 r1: rsi rs: []
# generating:      13:    149: 123: ldci 1 r1: rdx rs: []
        movq    $1,%rdx                 # load quad constant
# generating~:     13:    149: 123: ldci 1 r1: rdx rs: []
        call    psystem_wrc             # call system procedure/function
# generating~:     13:    150:  15: csp  10: wrc  rs: []
#     13:    151:         ujp     l netprobe.45           ! Unconditional jump
        jmp     netprobe.45
#     13:    152: l netprobe.46
netprobe.46:
#     13:    153: :13
        .loc 1 13 1
#     13:    154: !    writeln;
#     13:    155: :14
        .loc 1 14 1
#     14:    156:         lao     2                       ! Load global address
#     14:    157:         stra    1 -16                   ! Store local(t)
# assigning:      14:    156:   5: lao  2 rs: [] ~rf: []
# assigning~:     14:    156:   5: lao  2 r1: rbx rs: [] ~rf: [rbx]
#    expr:
#      14:    156:   5: lao  2 r1: rbx rs: []
# generating:      14:    156:   5: lao  2 r1: rbx rs: []
        leaq    globals_start+2(%rip),%rbx # load address of global
# generating~:     14:    156:   5: lao  2 r1: rbx rs: []
# generating:  70: stra      
        movq    %rbx,-16(%rbp)          # store qword
#     14:    158:         loda    1 -16                   ! Load local value(t)
#     14:    159:         csp     wln                     ! Call system procedure/function: Write next line to text file
# assigning:      14:    159:  15: csp  5: wln  rs: [] ~rf: []
# assigning:      14:    158: 105: loda -16 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     14:    158: 105: loda -16 r1: rdi rs: [] ~rf: [rdi]
# assigning~:     14:    159:  15: csp  5: wln  rs: [] ~rf: [rdi]
#    expr:
#      14:    159:  15: csp  5: wln  rs: []
#  Parameter:
#      14:    158: 105: loda -16 r1: rdi rs: []
# generating:      14:    159:  15: csp  5: wln  rs: []
# generating:      14:    158: 105: loda -16 r1: rdi rs: []
        movq    -16(%rbp),%rdi          # fetch local qword
# generating~:     14:    158: 105: loda -16 r1: rdi rs: []
        call    psystem_wln             # call system procedure/function
# generating~:     14:    159:  15: csp  5: wln  rs: []
#     14:    160: !    close(fi)
#     14:    161: :15
        .loc 1 15 1
#     15:    162:         lao     102                     ! Load global address
#     15:    163:         csp     clst                    ! Call system procedure/function: Close text file
# assigning:      15:    163:  15: csp  47: clst rs: [] ~rf: []
# assigning:      15:    162:   5: lao  102 dr1: rdi rs: [] ~rf: [rdi]
# assigning~:     15:    162:   5: lao  102 r1: rdi rs: [] ~rf: [rdi]
# assigning~:     15:    163:  15: csp  47: clst rs: [] ~rf: [rdi]
#    expr:
#      15:    163:  15: csp  47: clst rs: []
#  Parameter:
#      15:    162:   5: lao  102 r1: rdi rs: []
# generating:      15:    163:  15: csp  47: clst rs: []
# generating:      15:    162:   5: lao  102 r1: rdi rs: []
        leaq    netprobe.fi(%rip),%rdi  # load address of global
# generating~:     15:    162:   5: lao  102 r1: rdi rs: []
        call    psystem_clst            # call system procedure/function
# generating~:     15:    163:  15: csp  47: clst rs: []
#     15:    164: ! end.
#     15:    165: :16
        .loc 1 16 1
#     16:    166:         retp    0                       ! Return from procedure/function(t)
# generating:  14: retp      
        popq    %r15                    # undo alignment push
        popq    %r15                    # restore protected registers
        popq    %r14
        popq    %r13
        popq    %r12
        popq    %rbx
        leave                           # undo frame
        .cfi_restore rbp
        .cfi_def_cfa rsp, 32
        addq    $24,%rsp                # remove frame data
        .cfi_def_cfa rsp, 8
        popq    %rcx                    # get return address
        addq    $0,%rsp                 # remove caller parameters
        pushq   %rcx                    # replace return address
        ret                             # return to caller
        .cfi_endproc
.Lfnend_1:
netprobe$_tmpspc = 0
#     16:    167: l netprobe.36=16
netprobe.36 = 16
#     16:    168: l netprobe.37=40
netprobe.37 = 40
#     16:    169: g       105
#     16:    170: e       p
#     16:    171: f       0
#     16:    172: q
#
# Constants section
#
        jmp     1f
modnam:
        .string  "netprobe"
real_zero:
        .double  0.0
real_int_max:
        .double  9223372036854775807
real_int_min:
        .double  -9223372036854775807
string4:
        .ascii  "received: "
template44:
netprobe.44:
        .quad              1
string3:
        .ascii  "hello from pascaline"
template43:
netprobe.43:
        .quad              1
string2:
        .ascii  "addr: "
template41:
netprobe.41:
        .quad              1
string1:
        .ascii  "localhost"
template40:
netprobe.40:
        .quad              1
1:
        .bss
#
# Globals section
#
globals_start:
        .zero 105

#
# DWARF debug info
#
        .section .debug_info,"",@progbits
.Ldw_info_start:
        .long   .Ldw_info_end - .Ldw_info_hdr /* unit length */
.Ldw_info_hdr:
        .short  4 /* DWARF version */
        .long   .Ldw_abbrev_start /* debug_abbrev offset */
        .byte   8 /* address size */
        .uleb128 1 /* DW_TAG_compile_unit */
        .long   .Ldw5
        .short  2 /* language */
        .long   .Ldw6
        .quad   netprobe /* DW_AT_low_pc */
        .quad   .Lfnend_1 /* DW_AT_high_pc */
        .long   .Ldw_line_start /* DW_AT_stmt_list */
.Ldw1:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw7
        .byte   5 /* DW_ATE_signed */
        .byte   8 /* byte_size */
.Ldw2:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw8
        .byte   2 /* DW_ATE_boolean */
        .byte   1 /* byte_size */
.Ldw3:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw9
        .byte   8 /* DW_ATE_unsigned_char */
        .byte   1 /* byte_size */
.Ldw4:
        .uleb128 2 /* DW_TAG_base_type */
        .long   .Ldw10
        .byte   4 /* DW_ATE_float */
        .byte   8 /* byte_size */
        .uleb128 4 /* variable/parameter */
        .long   .Ldw11
        .long   .Ldw3 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+104
.Ldw12:
        .uleb128 15 /* DW_TAG_file_type */
        .byte   1 /* byte_size */
        .long   .Ldw3 - .Ldw_info_start
        .uleb128 4 /* variable/parameter */
        .long   .Ldw13
        .long   .Ldw12 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+102
.Ldw14:
        .uleb128 15 /* DW_TAG_file_type */
        .byte   1 /* byte_size */
        .long   .Ldw3 - .Ldw_info_start
        .uleb128 4 /* variable/parameter */
        .long   .Ldw15
        .long   .Ldw14 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+100
.Ldw16:
        .uleb128 20 /* DW_TAG_subrange_type */
        .long   .Ldw1 - .Ldw_info_start
        .quad   0 /* lower_bound */
        .quad   9223372036854775807 /* upper_bound */
        .uleb128 4 /* variable/parameter */
        .long   .Ldw17
        .long   .Ldw16 - .Ldw_info_start
        .uleb128 9 /* location expression length */
        .byte   3 /* DW_OP_addr */
        .quad   globals_start+92
        .uleb128 18 /* DW_TAG_subprogram */
        .long   .Ldw6
        .uleb128 1 /* frame_base length */
        .byte   86 /* DW_OP_reg 6 */
        .quad   netprobe /* DW_AT_low_pc */
        .quad   .Lfnend_1 /* DW_AT_high_pc */
        .byte   0 /* end compile unit children */
.Ldw_info_end:

#
# DWARF abbreviation table
#
        .section .debug_abbrev,"",@progbits
.Ldw_abbrev_start:
        .uleb128 1 /* abbreviation code */
        .uleb128 17 /* tag */
        .byte   1 /* children */
        .uleb128 37
        .uleb128 14
        .uleb128 19
        .uleb128 5
        .uleb128 3
        .uleb128 14
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .uleb128 16
        .uleb128 23
        .byte   0
        .byte   0
        .uleb128 2 /* abbreviation code */
        .uleb128 36 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 62
        .uleb128 11
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 3 /* abbreviation code */
        .uleb128 46 /* tag */
        .byte   1 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 64
        .uleb128 24
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .byte   0
        .byte   0
        .uleb128 4 /* abbreviation code */
        .uleb128 52 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 5 /* abbreviation code */
        .uleb128 52 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 6 /* abbreviation code */
        .uleb128 5 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 2
        .uleb128 24
        .byte   0
        .byte   0
        .uleb128 7 /* abbreviation code */
        .uleb128 15 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 8 /* abbreviation code */
        .uleb128 1 /* tag */
        .byte   1 /* children */
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 9 /* abbreviation code */
        .uleb128 33 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 34
        .uleb128 13
        .uleb128 47
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 10 /* abbreviation code */
        .uleb128 19 /* tag */
        .byte   1 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 11
        .uleb128 15
        .byte   0
        .byte   0
        .uleb128 11 /* abbreviation code */
        .uleb128 13 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 73
        .uleb128 19
        .uleb128 56
        .uleb128 15
        .byte   0
        .byte   0
        .uleb128 12 /* abbreviation code */
        .uleb128 4 /* tag */
        .byte   1 /* children */
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .uleb128 13 /* abbreviation code */
        .uleb128 40 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 28
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 14 /* abbreviation code */
        .uleb128 32 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 15 /* abbreviation code */
        .uleb128 41 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .uleb128 73
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 16 /* abbreviation code */
        .uleb128 51 /* tag */
        .byte   1 /* children */
        .uleb128 21
        .uleb128 19
        .byte   0
        .byte   0
        .uleb128 17 /* abbreviation code */
        .uleb128 25 /* tag */
        .byte   1 /* children */
        .uleb128 22
        .uleb128 13
        .byte   0
        .byte   0
        .uleb128 18 /* abbreviation code */
        .uleb128 46 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .uleb128 64
        .uleb128 24
        .uleb128 17
        .uleb128 1
        .uleb128 18
        .uleb128 1
        .byte   0
        .byte   0
        .uleb128 19 /* abbreviation code */
        .uleb128 59 /* tag */
        .byte   0 /* children */
        .uleb128 3
        .uleb128 14
        .byte   0
        .byte   0
        .uleb128 20 /* abbreviation code */
        .uleb128 33 /* tag */
        .byte   0 /* children */
        .uleb128 73
        .uleb128 19
        .uleb128 34
        .uleb128 7
        .uleb128 47
        .uleb128 7
        .byte   0
        .byte   0
        .uleb128 21 /* abbreviation code */
        .uleb128 15 /* tag */
        .byte   0 /* children */
        .uleb128 11
        .uleb128 11
        .byte   0
        .byte   0
        .byte   0 /* end abbreviation table */

#
# DWARF string table
#
        .section .debug_str,"MS",@progbits,1
.Ldw_str_start:
.Ldw17:
        .asciz  "a"
.Ldw15:
        .asciz  "fo"
.Ldw13:
        .asciz  "fi"
.Ldw11:
        .asciz  "c"
.Ldw10:
        .asciz  "real"
.Ldw9:
        .asciz  "char"
.Ldw8:
        .asciz  "boolean"
.Ldw7:
        .asciz  "integer"
.Ldw6:
        .asciz  "netprobe"
.Ldw5:
        .asciz  "Pascal-P6 pgen"
