{*******************************************************************************
*
*                       Terminal external execution                            *
*                                                                              *
* The terminal flavor of the external execution module: executes the terminal *
* externals against the native terminal model. Selected by the pintt          *
* instruction file module path; the plain interpreter uses the stub flavor    *
* in source/plain, which errors.                                              *
*                                                                              *
* The execterminal case bodies are generated by tools/extgen/genexec.py from  *
* the terminal symbol list; the case index matches the exttables terminal     *
* table order.                                                                *
*
*******************************************************************************}

module extterm;

joins terminal; { terminal model I/O }

uses pint_mem; { low level vm access for pint }

{ place event record to client memory }

procedure putevt(view er: terminal.evtrec; ad: address);

begin

   putint(ad, er.winid); { winid at 0 }
   putbyt(ad+8, ord(er.handled)); { handled at 8 }
   putbyt(ad+9, ord(er.etype)); { etype tag at 9 }
   case er.etype of { variant data, reverse order from 12 }

      terminal.etchar:   putbyt(ad+12, ord(er.echar));
      terminal.ettim:    putint(ad+12, er.timnum);
      terminal.etmoumov: begin putint(ad+12, er.moupy);
                               putint(ad+20, er.moupx);
                               putint(ad+28, er.mmoun) end;
      terminal.etmouba:  begin putint(ad+12, er.amoubn);
                               putint(ad+20, er.amoun) end;
      terminal.etmoubd:  begin putint(ad+12, er.dmoubn);
                               putint(ad+20, er.dmoun) end;
      terminal.etjoyba:  begin putint(ad+12, er.ajoybn);
                               putint(ad+20, er.ajoyn) end;
      terminal.etjoybd:  begin putint(ad+12, er.djoybn);
                               putint(ad+20, er.djoyn) end;
      terminal.etjoymov: begin putint(ad+12, er.joyp6);
                               putint(ad+20, er.joyp5);
                               putint(ad+28, er.joyp4);
                               putint(ad+36, er.joypz);
                               putint(ad+44, er.joypy);
                               putint(ad+52, er.joypx);
                               putint(ad+60, er.mjoyn) end;
      terminal.etfun:    putint(ad+12, er.fkey);
      terminal.etresize: begin putint(ad+12, er.rszy);
                               putint(ad+20, er.rszx) end;
      terminal.etmenus:  putint(ad+12, er.menuid);
   else { events without parameter data }
   end

end;

{ Event callback support: interpreted programs register global-level
  handlers through eventover/eventsover; a native thunk converts the event
  record into interpreted memory, runs the handler through the interpreter
  (callvm), and carries the handled flag back. Old vectors are opaque
  integers by the interface, and there is no facility to reinstall them, so
  registration simply replaces the previous interpreted handler. Handlers at
  nested level would need the thunk securing planned for the compiler, and
  error as not implemented. }

const nevtcod = 56; { number of event codes (etchar..etmenus) }
      evtrecvmsiz = 80; { interpreted event record scratch size }

var vmhand:    array [1..nevtcod] of address; { per-event interpreted handlers }
    vmhandall: address; { master interpreted handler }
    hooked:    array [1..nevtcod] of boolean; { native vector hooked }
    hookedall: boolean;
    evtinit:   boolean; { tables initialized }

{ initialize the callback tables on first use }

procedure evtsetup;

var i: integer;

begin

   if not evtinit then begin

      for i := 1 to nevtcod do begin vmhand[i] := 0; hooked[i] := false end;
      vmhandall := 0;
      hookedall := false;
      evtinit := true

   end

end;

{ convert ordinal to event code }

function int2evtcod(i: integer): terminal.evtcod;

var c: terminal.evtcod;
    j: integer;

begin

   c := terminal.etchar;
   for j := 1 to i do c := succ(c);
   int2evtcod := c

end;

{ run an interpreted handler against an event record }

procedure callhand(h: address; var er: terminal.evtrec);

var ad: address;

begin

   ad := resvm(evtrecvmsiz); { scratch on the interpreted stack }
   putevt(er, ad);
   callvm(globalframe, h, ad);
   er.handled := getbyt(ad+8) <> 0; { carry the handled flag back }
   relvm(evtrecvmsiz)

end;

{ native thunk for per-event vectors }

procedure evtthunk(var er: terminal.evtrec);

var h: address;

begin

   h := vmhand[ord(er.etype)+1];
   if h <> 0 then callhand(h, er)

end;

{ native thunk for the master vector }

procedure evtsthunk(var er: terminal.evtrec);

begin

   if vmhandall <> 0 then callhand(vmhandall, er)

end;

procedure execterminal(routine: integer; var params: integer); forward;

private

const

    strmax = 1000; { size of string buffers }
    FileModeIncorrect = 28; { file mode incorrect }
    strparsiz = ptrsize+intsize; { size of string parameter }

type str = packed array [1..strmax] of char;

{ load string from vm }

procedure getstr(sa: address; var s: string);

var ad: address;
    l:  integer;
    i:  integer;

begin

   for i := 1 to max(s) do s[i] := ' '; { clear result }
   ad := getadr(sa); { get base address of string }
   l := getint(sa+ptrsize); { get logical length }
   if l > max(s) then l := max(s); { limit to buffer }
   for i := 1 to l do begin { transfer string }

      s[i] := chr(getbyt(ad)); { get character }
      ad := ad+1 { next }

   end

end;


procedure execterminal(
    { module routine to execute }               routine: integer;
    { address of parameters bottom/result } var params:  integer
);

const FunctionNotImplemented = 90; { external function not implemented }

var a, a2, a3, a9: integer;
    s:             str;
    ad, ad2:       address;
    fn:            fileno;
    er:            terminal.evtrec;

{ convert ordinal to color }

function int2color(i: integer): terminal.color;

var c: terminal.color;

begin

   case i of
      0: c := terminal.black;
      1: c := terminal.white;
      2: c := terminal.red;
      3: c := terminal.green;
      4: c := terminal.blue;
      5: c := terminal.cyan;
      6: c := terminal.yellow;
      7: c := terminal.magenta;
   else c := terminal.black
   end;
   int2color := c

end;


begin

    case routine of

       1: begin { cursor@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params+intsize);
           a2 := getint(params);
           terminal.cursor(output, a, a2);
           params := params+adrsize+intsize+intsize;

       end;

       2: begin { cursor@p_i_i }

           a := getint(params+intsize);
           a2 := getint(params);
           terminal.cursor(a, a2);
           params := params+intsize+intsize;

       end;

       3: begin { maxx@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.maxx(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       4: begin { maxx@f }

           a9 := ord(terminal.maxx);
           putint(params, a9);

       end;

       5: begin { maxy@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.maxy(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       6: begin { maxy@f }

           a9 := ord(terminal.maxy);
           putint(params, a9);

       end;

       7: begin { home@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.home(output);
           params := params+adrsize;

       end;

       8: begin { home@p }

           terminal.home;

       end;

       9: begin { del@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.del(output);
           params := params+adrsize;

       end;

       10: begin { del@p }

           terminal.del;

       end;

       11: begin { up@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.up(output);
           params := params+adrsize;

       end;

       12: begin { up@p }

           terminal.up;

       end;

       13: begin { down@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.down(output);
           params := params+adrsize;

       end;

       14: begin { down@p }

           terminal.down;

       end;

       15: begin { left@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.left(output);
           params := params+adrsize;

       end;

       16: begin { left@p }

           terminal.left;

       end;

       17: begin { right@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.right(output);
           params := params+adrsize;

       end;

       18: begin { right@p }

           terminal.right;

       end;

       19: begin { blink@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.blink(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       20: begin { blink@p_b }

           a := getint(params);
           terminal.blink(a <> 0);
           params := params+intsize;

       end;

       21: begin { reverse@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.reverse(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       22: begin { reverse@p_b }

           a := getint(params);
           terminal.reverse(a <> 0);
           params := params+intsize;

       end;

       23: begin { underline@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.underline(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       24: begin { underline@p_b }

           a := getint(params);
           terminal.underline(a <> 0);
           params := params+intsize;

       end;

       25: begin { superscript@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.superscript(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       26: begin { superscript@p_b }

           a := getint(params);
           terminal.superscript(a <> 0);
           params := params+intsize;

       end;

       27: begin { subscript@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.subscript(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       28: begin { subscript@p_b }

           a := getint(params);
           terminal.subscript(a <> 0);
           params := params+intsize;

       end;

       29: begin { italic@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.italic(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       30: begin { italic@p_b }

           a := getint(params);
           terminal.italic(a <> 0);
           params := params+intsize;

       end;

       31: begin { bold@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.bold(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       32: begin { bold@p_b }

           a := getint(params);
           terminal.bold(a <> 0);
           params := params+intsize;

       end;

       33: begin { strikeout@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.strikeout(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       34: begin { strikeout@p_b }

           a := getint(params);
           terminal.strikeout(a <> 0);
           params := params+intsize;

       end;

       35: begin { standout@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.standout(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       36: begin { standout@p_b }

           a := getint(params);
           terminal.standout(a <> 0);
           params := params+intsize;

       end;

       37: begin { fcolor@p_fc_x(black,white,red,green,blue,cyan,y }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.fcolor(output, int2color(a));
           params := params+adrsize+intsize;

       end;

       38: begin { fcolor@p_x(black,white,red,green,blue,cyan,yell }

           a := getint(params);
           terminal.fcolor(int2color(a));
           params := params+intsize;

       end;

       39: begin { bcolor@p_fc_x(black,white,red,green,blue,cyan,y }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.bcolor(output, int2color(a));
           params := params+adrsize+intsize;

       end;

       40: begin { bcolor@p_x(black,white,red,green,blue,cyan,yell }

           a := getint(params);
           terminal.bcolor(int2color(a));
           params := params+intsize;

       end;

       41: begin { auto@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.auto(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       42: begin { auto@p_b }

           a := getint(params);
           terminal.auto(a <> 0);
           params := params+intsize;

       end;

       43: begin { curvis@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.curvis(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       44: begin { curvis@p_b }

           a := getint(params);
           terminal.curvis(a <> 0);
           params := params+intsize;

       end;

       45: begin { scroll@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params+intsize);
           a2 := getint(params);
           terminal.scroll(output, a, a2);
           params := params+adrsize+intsize+intsize;

       end;

       46: begin { scroll@p_i_i }

           a := getint(params+intsize);
           a2 := getint(params);
           terminal.scroll(a, a2);
           params := params+intsize+intsize;

       end;

       47: begin { curx@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.curx(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       48: begin { curx@f }

           a9 := ord(terminal.curx);
           putint(params, a9);

       end;

       49: begin { cury@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.cury(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       50: begin { cury@f }

           a9 := ord(terminal.cury);
           putint(params, a9);

       end;

       51: begin { curbnd@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.curbnd(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       52: begin { curbnd@f }

           a9 := ord(terminal.curbnd);
           putint(params, a9);

       end;

       53: begin { select@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params+intsize);
           a2 := getint(params);
           terminal.select(output, a, a2);
           params := params+adrsize+intsize+intsize;

       end;

       54: begin { select@p_i_i }

           a := getint(params+intsize);
           a2 := getint(params);
           terminal.select(a, a2);
           params := params+intsize+intsize;

       end;

       55: begin { event@p_fc_r(winid:0:i,handled:8:b,etype:9:x(e }

           ad := getadr(params+adrsize); valfil(ad); fn := getbyt(ad);
           if (fn <> inputfn) and (fn > commandfn) then
              errore(FileModeIncorrect);
           ad2 := getadr(params);
           terminal.event(input, er);
           putevt(er, ad2);
           params := params+adrsize+adrsize;

       end;

       56: begin { event@p_r(winid:0:i,handled:8:b,etype:9:x(etch }

           ad2 := getadr(params);
           terminal.event(er);
           putevt(er, ad2);
           params := params+adrsize;

       end;

       57: begin { timer@p_fc_i_i_b }

           ad := getadr(params+intsize+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.timer(output, a, a2, a3 <> 0);
           params := params+adrsize+intsize+intsize+intsize;

       end;

       58: begin { timer@p_i_i_b }

           a := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.timer(a, a2, a3 <> 0);
           params := params+intsize+intsize+intsize;

       end;

       59: begin { killtimer@p_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.killtimer(output, a);
           params := params+adrsize+intsize;

       end;

       60: begin { killtimer@p_i }

           a := getint(params);
           terminal.killtimer(a);
           params := params+intsize;

       end;

       61: begin { mouse@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.mouse(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       62: begin { mouse@f }

           a9 := ord(terminal.mouse);
           putint(params, a9);

       end;

       63: begin { mousebutton@f_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           a9 := ord(terminal.mousebutton(output, a));
           params := params+adrsize+intsize;
           putint(params, a9);

       end;

       64: begin { mousebutton@f_i }

           a := getint(params);
           a9 := ord(terminal.mousebutton(a));
           params := params+intsize;
           putint(params, a9);

       end;

       65: begin { joystick@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.joystick(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       66: begin { joystick@f }

           a9 := ord(terminal.joystick);
           putint(params, a9);

       end;

       67: begin { joybutton@f_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           a9 := ord(terminal.joybutton(output, a));
           params := params+adrsize+intsize;
           putint(params, a9);

       end;

       68: begin { joybutton@f_i }

           a := getint(params);
           a9 := ord(terminal.joybutton(a));
           params := params+intsize;
           putint(params, a9);

       end;

       69: begin { joyaxis@f_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           a9 := ord(terminal.joyaxis(output, a));
           params := params+adrsize+intsize;
           putint(params, a9);

       end;

       70: begin { joyaxis@f_i }

           a := getint(params);
           a9 := ord(terminal.joyaxis(a));
           params := params+intsize;
           putint(params, a9);

       end;

       71: begin { settab@p_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.settab(output, a);
           params := params+adrsize+intsize;

       end;

       72: begin { settab@p_i }

           a := getint(params);
           terminal.settab(a);
           params := params+intsize;

       end;

       73: begin { restab@p_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.restab(output, a);
           params := params+adrsize+intsize;

       end;

       74: begin { restab@p_i }

           a := getint(params);
           terminal.restab(a);
           params := params+intsize;

       end;

       75: begin { clrtab@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.clrtab(output);
           params := params+adrsize;

       end;

       76: begin { clrtab@p }

           terminal.clrtab;

       end;

       77: begin { funkey@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a9 := ord(terminal.funkey(output));
           params := params+adrsize;
           putint(params, a9);

       end;

       78: begin { funkey@f }

           a9 := ord(terminal.funkey);
           putint(params, a9);

       end;

       79: begin { frametimer@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params);
           terminal.frametimer(output, a <> 0);
           params := params+adrsize+intsize;

       end;

       80: begin { frametimer@p_b }

           a := getint(params);
           terminal.frametimer(a <> 0);
           params := params+intsize;

       end;

       81: begin { autohold@p_b }

           a := getint(params);
           terminal.autohold(a <> 0);
           params := params+intsize;

       end;

       82: begin { wrtstr@p_fc_vc }

           ad := getadr(params+strparsiz); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           getstr(params, s);
           terminal.wrtstr(output, s);
           params := params+adrsize+strparsiz;

       end;

       83: begin { wrtstr@p_vc }

           getstr(params, s);
           terminal.wrtstr(s);
           params := params+strparsiz;

       end;

       84: begin { sizbuf@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params+intsize);
           a2 := getint(params);
           terminal.sizbuf(output, a, a2);
           params := params+adrsize+intsize+intsize;

       end;

       85: begin { sizbuf@p_i_i }

           a := getint(params+intsize);
           a2 := getint(params);
           terminal.sizbuf(a, a2);
           params := params+intsize+intsize;

       end;

       86: begin { title@p_fc_vc }

           ad := getadr(params+strparsiz); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           getstr(params, s);
           terminal.title(output, s);
           params := params+adrsize+strparsiz;

       end;

       87: begin { title@p_vc }

           getstr(params, s);
           terminal.title(s);
           params := params+strparsiz;

       end;

       88: begin { fcolorc@p_fc_i_i_i }

           ad := getadr(params+intsize+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.fcolorc(output, a, a2, a3);
           params := params+adrsize+intsize+intsize+intsize;

       end;

       89: begin { fcolorc@p_i_i_i }

           a := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.fcolorc(a, a2, a3);
           params := params+intsize+intsize+intsize;

       end;

       90: begin { bcolorc@p_fc_i_i_i }

           ad := getadr(params+intsize+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.bcolorc(output, a, a2, a3);
           params := params+adrsize+intsize+intsize+intsize;

       end;

       91: begin { bcolorc@p_i_i_i }

           a := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.bcolorc(a, a2, a3);
           params := params+intsize+intsize+intsize;

       end;

       92: begin { eventover@p_x(...)_q(...)_i }

           { (e: evtcod; eh: handler; out oeh: integer): oeh at params, the
             handler pair above it (address below frame), e on top }
           evtsetup;
           ad := getadr(params); { out oeh }
           ad2 := getadr(params+adrsize); { handler address }
           a2 := getadr(params+adrsize+ptrsize); { handler frame }
           a := getint(params+adrsize+ptrsize*2); { event code ordinal }
           { only global-level handlers: nested ones need the planned thunk
             securing }
           if ad2 <> 0 then if a2 <> globalframe then
              errore(FunctionNotImplemented);
           putint(ad, vmhand[a+1]); { old vector as opaque integer }
           vmhand[a+1] := ad2;
           if not hooked[a+1] then begin

              terminal.eventover(int2evtcod(a), evtthunk, a3);
              hooked[a+1] := true

           end;
           params := params+adrsize+ptrsize*2+intsize

       end;

       93: begin { eventsover@p_q(...)_i }

           { (eh: handler; out oeh: integer) }
           evtsetup;
           ad := getadr(params); { out oeh }
           ad2 := getadr(params+adrsize); { handler address }
           a2 := getadr(params+adrsize+ptrsize); { handler frame }
           if ad2 <> 0 then if a2 <> globalframe then
              errore(FunctionNotImplemented);
           putint(ad, vmhandall);
           vmhandall := ad2;
           if not hookedall then begin

              terminal.eventsover(evtsthunk, a3);
              hookedall := true

           end;
           params := params+adrsize+ptrsize*2

       end;

    else errore(FunctionNotImplemented)

    end

end;

begin

   evtinit := false

end.
