{*******************************************************************************
*                                                                              *
*                       Terminal external execution                            *
*                                                                              *
* The terminal flavor of the external execution module, selected for the      *
* pintt interpreter by module path: terminal externals execute against the    *
* native terminal model; graphics externals error.                            *
*                                                                              *
* Generated by tools/extgen/genexec.py; do not edit by hand.                  *
*                                                                              *
*******************************************************************************}

module extterm;

joins terminal; { terminal model I/O }

uses pint_mem; { low level vm access for pint }

procedure execterminal(routine: integer; var params: integer); forward;
procedure execgraph(routine: integer; var params: integer); forward;

private


const strmax = 1000; { size of string buffers }
      strparsiz = ptrsize+intsize; { size of string parameter }
      FileModeIncorrect = 28; { file mode incorrect }
      FunctionNotImplemented = 90; { external function not implemented }

type str = packed array [1..strmax] of char;

{ load string from vm }

procedure getstr(sa: address; var s: string);

var ad: address;
    l:  integer;
    i:  integer;

begin

   for i := 1 to max(s) do s[i] := ' '; { clear result }
   ad := getadr(sa); { get base address of string }
   l := getint(sa+ptrsize); { get logical length }
   if l > max(s) then l := max(s); { limit to buffer }
   for i := 1 to l do begin { transfer string }

      s[i] := chr(getbyt(ad)); { get character }
      ad := ad+1 { next }

   end

end;

{ store string to vm }

procedure putstr(var s: str; sa: address);

var ad: address;
    l:  integer;
    i:  integer;

begin

   ad := getadr(sa); { get base address of string }
   l := getint(sa+ptrsize); { get logical length }
   if l > strmax then l := strmax;
   for i := 1 to l do begin

      putbyt(ad, ord(s[i]));
      ad := ad+1

   end

end;

{ convert ordinal to color }

function cnvcolor(i: integer): terminal.color;

var c: terminal.color;
    j: integer;

begin

   c := terminal.black;
   for j := 1 to i do c := succ(c);
   cnvcolor := c

end;

{ convert ordinal to evtcod }

function cnvevtcod(i: integer): terminal.evtcod;

var c: terminal.evtcod;
    j: integer;

begin

   c := terminal.etchar;
   for j := 1 to i do c := succ(c);
   cnvevtcod := c

end;

{ place event record to client memory }

procedure putevt(view er: terminal.evtrec; ad: address);

begin

   putint(ad, er.winid); { winid at 0 }
   putbyt(ad+8, ord(er.handled)); { handled at 8 }
   putbyt(ad+9, ord(er.etype)); { etype tag at 9 }
   case er.etype of { variant data, reverse order from 12 }

      terminal.etchar: putbyt(ad+12, ord(er.echar));
      terminal.etfun: putint(ad+12, er.fkey);
      terminal.etmouba: begin putint(ad+20, er.amoun);
         putint(ad+12, er.amoubn) end;
      terminal.etmoubd: begin putint(ad+20, er.dmoun);
         putint(ad+12, er.dmoubn) end;
      terminal.etmoumov: begin putint(ad+28, er.mmoun);
         putint(ad+20, er.moupx);
         putint(ad+12, er.moupy) end;
      terminal.ettim: putint(ad+12, er.timnum);
      terminal.etjoyba: begin putint(ad+20, er.ajoyn);
         putint(ad+12, er.ajoybn) end;
      terminal.etjoybd: begin putint(ad+20, er.djoyn);
         putint(ad+12, er.djoybn) end;
      terminal.etjoymov: begin putint(ad+60, er.mjoyn);
         putint(ad+52, er.joypx);
         putint(ad+44, er.joypy);
         putint(ad+36, er.joypz);
         putint(ad+28, er.joyp4);
         putint(ad+20, er.joyp5);
         putint(ad+12, er.joyp6) end;
      terminal.etresize: begin putint(ad+20, er.rszx);
         putint(ad+12, er.rszy) end;
      terminal.etmenus: putint(ad+12, er.menuid);
      else { events without parameter data }
   end

end;

{ get event record from client memory }

procedure getevt(out er: terminal.evtrec; ad: address);

var i: integer;
    c: terminal.evtcod;

begin

   i := getbyt(ad+9); { etype tag }
   c := terminal.etchar;
   while i > 0 do begin c := succ(c); i := i-1 end;
   case c of { construct against the variant }

      terminal.etchar: begin er.etype := terminal.etchar;
         er.echar := chr(getbyt(ad+12)) end;
      terminal.etup: begin er.etype := terminal.etup end;
      terminal.etdown: begin er.etype := terminal.etdown end;
      terminal.etleft: begin er.etype := terminal.etleft end;
      terminal.etright: begin er.etype := terminal.etright end;
      terminal.etleftw: begin er.etype := terminal.etleftw end;
      terminal.etrightw: begin er.etype := terminal.etrightw end;
      terminal.ethome: begin er.etype := terminal.ethome end;
      terminal.ethomes: begin er.etype := terminal.ethomes end;
      terminal.ethomel: begin er.etype := terminal.ethomel end;
      terminal.etend: begin er.etype := terminal.etend end;
      terminal.etends: begin er.etype := terminal.etends end;
      terminal.etendl: begin er.etype := terminal.etendl end;
      terminal.etscrl: begin er.etype := terminal.etscrl end;
      terminal.etscrr: begin er.etype := terminal.etscrr end;
      terminal.etscru: begin er.etype := terminal.etscru end;
      terminal.etscrd: begin er.etype := terminal.etscrd end;
      terminal.etpagd: begin er.etype := terminal.etpagd end;
      terminal.etpagu: begin er.etype := terminal.etpagu end;
      terminal.ettab: begin er.etype := terminal.ettab end;
      terminal.etenter: begin er.etype := terminal.etenter end;
      terminal.etinsert: begin er.etype := terminal.etinsert end;
      terminal.etinsertl: begin er.etype := terminal.etinsertl end;
      terminal.etinsertt: begin er.etype := terminal.etinsertt end;
      terminal.etdel: begin er.etype := terminal.etdel end;
      terminal.etdell: begin er.etype := terminal.etdell end;
      terminal.etdelcf: begin er.etype := terminal.etdelcf end;
      terminal.etdelcb: begin er.etype := terminal.etdelcb end;
      terminal.etcopy: begin er.etype := terminal.etcopy end;
      terminal.etcopyl: begin er.etype := terminal.etcopyl end;
      terminal.etcan: begin er.etype := terminal.etcan end;
      terminal.etstop: begin er.etype := terminal.etstop end;
      terminal.etcont: begin er.etype := terminal.etcont end;
      terminal.etprint: begin er.etype := terminal.etprint end;
      terminal.etprintb: begin er.etype := terminal.etprintb end;
      terminal.etprints: begin er.etype := terminal.etprints end;
      terminal.etfun: begin er.etype := terminal.etfun;
         er.fkey := getint(ad+12) end;
      terminal.etmenu: begin er.etype := terminal.etmenu end;
      terminal.etmouba: begin er.etype := terminal.etmouba;
         er.amoun := getint(ad+20);
         er.amoubn := getint(ad+12) end;
      terminal.etmoubd: begin er.etype := terminal.etmoubd;
         er.dmoun := getint(ad+20);
         er.dmoubn := getint(ad+12) end;
      terminal.etmoumov: begin er.etype := terminal.etmoumov;
         er.mmoun := getint(ad+28);
         er.moupx := getint(ad+20);
         er.moupy := getint(ad+12) end;
      terminal.ettim: begin er.etype := terminal.ettim;
         er.timnum := getint(ad+12) end;
      terminal.etjoyba: begin er.etype := terminal.etjoyba;
         er.ajoyn := getint(ad+20);
         er.ajoybn := getint(ad+12) end;
      terminal.etjoybd: begin er.etype := terminal.etjoybd;
         er.djoyn := getint(ad+20);
         er.djoybn := getint(ad+12) end;
      terminal.etjoymov: begin er.etype := terminal.etjoymov;
         er.mjoyn := getint(ad+60);
         er.joypx := getint(ad+52);
         er.joypy := getint(ad+44);
         er.joypz := getint(ad+36);
         er.joyp4 := getint(ad+28);
         er.joyp5 := getint(ad+20);
         er.joyp6 := getint(ad+12) end;
      terminal.etresize: begin er.etype := terminal.etresize;
         er.rszx := getint(ad+20);
         er.rszy := getint(ad+12) end;
      terminal.etfocus: begin er.etype := terminal.etfocus end;
      terminal.etnofocus: begin er.etype := terminal.etnofocus end;
      terminal.ethover: begin er.etype := terminal.ethover end;
      terminal.etnohover: begin er.etype := terminal.etnohover end;
      terminal.etterm: begin er.etype := terminal.etterm end;
      terminal.etframe: begin er.etype := terminal.etframe end;
      terminal.etredraw: begin er.etype := terminal.etredraw end;
      terminal.etmin: begin er.etype := terminal.etmin end;
      terminal.etmax: begin er.etype := terminal.etmax end;
      terminal.etnorm: begin er.etype := terminal.etnorm end;
      terminal.etmenus: begin er.etype := terminal.etmenus;
         er.menuid := getint(ad+12) end;
      else er.etype := c
   end;
   er.winid := getint(ad);
   er.handled := getbyt(ad+8) <> 0

end;

{ Event callback support: interpreted programs register global-level
  handlers through eventover/eventsover; a native thunk converts the event
  record into interpreted memory, runs the handler through the interpreter
  (callvm), and carries the handled flag back. Old vectors are opaque
  integers by the interface with no reinstall facility, so registration
  replaces the previous interpreted handler. }

const nevtcod = 57; { number of event codes }
      evtrecvmsiz = 96; { interpreted event record scratch size }

var vmhand:    array [1..nevtcod] of address; { per-event handlers }
    vmhandall: address; { master handler }
    hooked:    array [1..nevtcod] of boolean; { native vector hooked }
    hookedall: boolean;
    evtinit:   boolean; { tables initialized }

{ initialize the callback tables on first use }

procedure evtsetup;

var i: integer;

begin

   if not evtinit then begin

      for i := 1 to nevtcod do begin vmhand[i] := 0; hooked[i] := false end;
      vmhandall := 0;
      hookedall := false;
      evtinit := true

   end

end;

{ run an interpreted handler against an event record }

procedure callhand(h: address; var er: terminal.evtrec);

var ad: address;

begin

   ad := resvm(evtrecvmsiz); { scratch on the interpreted stack }
   putevt(er, ad);
   callvm(globalframe, h, ad);
   er.handled := getbyt(ad+8) <> 0; { carry the handled flag back }
   relvm(evtrecvmsiz)

end;

{ native thunk for per-event vectors }

procedure evtthunk(var er: terminal.evtrec);

var h: address;

begin

   h := vmhand[ord(er.etype)+1];
   if h <> 0 then callhand(h, er)

end;

{ native thunk for the master vector }

procedure evtsthunk(var er: terminal.evtrec);

begin

   if vmhandall <> 0 then callhand(vmhandall, er)

end;

procedure execterminal(routine: integer; var params: integer);

var a1, a2, a3, rv: integer;
    r1: real;
    s:        str;
    ad, ad2:  address;
    fn:       fileno;
    st:       settype;
    er:       terminal.evtrec;

begin

    case routine of

       1: begin { cursor@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.cursor(output, a1, a2);
           params := params+adrsize+intsize+intsize;

       end;

       2: begin { cursor@p_i_i }

           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.cursor(a1, a2);
           params := params+intsize+intsize;

       end;

       3: begin { maxx@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.maxx(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       4: begin { maxx@f }

           rv := ord(terminal.maxx);
           putint(params, rv);

       end;

       5: begin { maxy@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.maxy(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       6: begin { maxy@f }

           rv := ord(terminal.maxy);
           putint(params, rv);

       end;

       7: begin { home@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.home(output);
           params := params+adrsize;

       end;

       8: begin { home@p }

           terminal.home;

       end;

       9: begin { del@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.del(output);
           params := params+adrsize;

       end;

       10: begin { del@p }

           terminal.del;

       end;

       11: begin { up@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.up(output);
           params := params+adrsize;

       end;

       12: begin { up@p }

           terminal.up;

       end;

       13: begin { down@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.down(output);
           params := params+adrsize;

       end;

       14: begin { down@p }

           terminal.down;

       end;

       15: begin { left@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.left(output);
           params := params+adrsize;

       end;

       16: begin { left@p }

           terminal.left;

       end;

       17: begin { right@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.right(output);
           params := params+adrsize;

       end;

       18: begin { right@p }

           terminal.right;

       end;

       19: begin { blink@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.blink(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       20: begin { blink@p_b }

           a1 := getint(params);
           terminal.blink(a1 <> 0);
           params := params+intsize;

       end;

       21: begin { reverse@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.reverse(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       22: begin { reverse@p_b }

           a1 := getint(params);
           terminal.reverse(a1 <> 0);
           params := params+intsize;

       end;

       23: begin { underline@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.underline(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       24: begin { underline@p_b }

           a1 := getint(params);
           terminal.underline(a1 <> 0);
           params := params+intsize;

       end;

       25: begin { superscript@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.superscript(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       26: begin { superscript@p_b }

           a1 := getint(params);
           terminal.superscript(a1 <> 0);
           params := params+intsize;

       end;

       27: begin { subscript@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.subscript(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       28: begin { subscript@p_b }

           a1 := getint(params);
           terminal.subscript(a1 <> 0);
           params := params+intsize;

       end;

       29: begin { italic@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.italic(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       30: begin { italic@p_b }

           a1 := getint(params);
           terminal.italic(a1 <> 0);
           params := params+intsize;

       end;

       31: begin { bold@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.bold(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       32: begin { bold@p_b }

           a1 := getint(params);
           terminal.bold(a1 <> 0);
           params := params+intsize;

       end;

       33: begin { strikeout@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.strikeout(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       34: begin { strikeout@p_b }

           a1 := getint(params);
           terminal.strikeout(a1 <> 0);
           params := params+intsize;

       end;

       35: begin { standout@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.standout(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       36: begin { standout@p_b }

           a1 := getint(params);
           terminal.standout(a1 <> 0);
           params := params+intsize;

       end;

       37: begin { fcolor@p_fc_x(black,white,red,green,blue,cyan,y }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.fcolor(output, cnvcolor(a1));
           params := params+adrsize+intsize;

       end;

       38: begin { fcolor@p_x(black,white,red,green,blue,cyan,yell }

           a1 := getint(params);
           terminal.fcolor(cnvcolor(a1));
           params := params+intsize;

       end;

       39: begin { bcolor@p_fc_x(black,white,red,green,blue,cyan,y }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.bcolor(output, cnvcolor(a1));
           params := params+adrsize+intsize;

       end;

       40: begin { bcolor@p_x(black,white,red,green,blue,cyan,yell }

           a1 := getint(params);
           terminal.bcolor(cnvcolor(a1));
           params := params+intsize;

       end;

       41: begin { auto@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.auto(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       42: begin { auto@p_b }

           a1 := getint(params);
           terminal.auto(a1 <> 0);
           params := params+intsize;

       end;

       43: begin { curvis@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.curvis(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       44: begin { curvis@p_b }

           a1 := getint(params);
           terminal.curvis(a1 <> 0);
           params := params+intsize;

       end;

       45: begin { scroll@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.scroll(output, a1, a2);
           params := params+adrsize+intsize+intsize;

       end;

       46: begin { scroll@p_i_i }

           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.scroll(a1, a2);
           params := params+intsize+intsize;

       end;

       47: begin { curx@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.curx(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       48: begin { curx@f }

           rv := ord(terminal.curx);
           putint(params, rv);

       end;

       49: begin { cury@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.cury(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       50: begin { cury@f }

           rv := ord(terminal.cury);
           putint(params, rv);

       end;

       51: begin { curbnd@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.curbnd(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       52: begin { curbnd@f }

           rv := ord(terminal.curbnd);
           putint(params, rv);

       end;

       53: begin { select@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.select(output, a1, a2);
           params := params+adrsize+intsize+intsize;

       end;

       54: begin { select@p_i_i }

           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.select(a1, a2);
           params := params+intsize+intsize;

       end;

       55: begin { event@p_fc_r(winid:0:i,handled:8:b,etype:9:x(e }

           ad := getadr(params+adrsize); valfil(ad); fn := getbyt(ad);
           if (fn <> inputfn) and (fn > commandfn) then
              errore(FileModeIncorrect);
           ad2 := getadr(params);
           terminal.event(input, er);
           putevt(er, ad2);
           params := params+adrsize+adrsize;

       end;

       56: begin { event@p_r(winid:0:i,handled:8:b,etype:9:x(etch }

           ad2 := getadr(params);
           terminal.event(er);
           putevt(er, ad2);
           params := params+adrsize;

       end;

       57: begin { timer@p_fc_i_i_b }

           ad := getadr(params+intsize+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.timer(output, a1, a2, a3 <> 0);
           params := params+adrsize+intsize+intsize+intsize;

       end;

       58: begin { timer@p_i_i_b }

           a1 := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.timer(a1, a2, a3 <> 0);
           params := params+intsize+intsize+intsize;

       end;

       59: begin { killtimer@p_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.killtimer(output, a1);
           params := params+adrsize+intsize;

       end;

       60: begin { killtimer@p_i }

           a1 := getint(params);
           terminal.killtimer(a1);
           params := params+intsize;

       end;

       61: begin { mouse@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.mouse(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       62: begin { mouse@f }

           rv := ord(terminal.mouse);
           putint(params, rv);

       end;

       63: begin { mousebutton@f_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           rv := ord(terminal.mousebutton(output, a1));
           params := params+adrsize+intsize;
           putint(params, rv);

       end;

       64: begin { mousebutton@f_i }

           a1 := getint(params);
           rv := ord(terminal.mousebutton(a1));
           params := params+intsize;
           putint(params, rv);

       end;

       65: begin { joystick@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.joystick(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       66: begin { joystick@f }

           rv := ord(terminal.joystick);
           putint(params, rv);

       end;

       67: begin { joybutton@f_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           rv := ord(terminal.joybutton(output, a1));
           params := params+adrsize+intsize;
           putint(params, rv);

       end;

       68: begin { joybutton@f_i }

           a1 := getint(params);
           rv := ord(terminal.joybutton(a1));
           params := params+intsize;
           putint(params, rv);

       end;

       69: begin { joyaxis@f_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           rv := ord(terminal.joyaxis(output, a1));
           params := params+adrsize+intsize;
           putint(params, rv);

       end;

       70: begin { joyaxis@f_i }

           a1 := getint(params);
           rv := ord(terminal.joyaxis(a1));
           params := params+intsize;
           putint(params, rv);

       end;

       71: begin { settab@p_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.settab(output, a1);
           params := params+adrsize+intsize;

       end;

       72: begin { settab@p_i }

           a1 := getint(params);
           terminal.settab(a1);
           params := params+intsize;

       end;

       73: begin { restab@p_fc_i }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.restab(output, a1);
           params := params+adrsize+intsize;

       end;

       74: begin { restab@p_i }

           a1 := getint(params);
           terminal.restab(a1);
           params := params+intsize;

       end;

       75: begin { clrtab@p_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           terminal.clrtab(output);
           params := params+adrsize;

       end;

       76: begin { clrtab@p }

           terminal.clrtab;

       end;

       77: begin { funkey@f_fc }

           ad := getadr(params); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           rv := ord(terminal.funkey(output));
           params := params+adrsize;
           putint(params, rv);

       end;

       78: begin { funkey@f }

           rv := ord(terminal.funkey);
           putint(params, rv);

       end;

       79: begin { frametimer@p_fc_b }

           ad := getadr(params+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params);
           terminal.frametimer(output, a1 <> 0);
           params := params+adrsize+intsize;

       end;

       80: begin { frametimer@p_b }

           a1 := getint(params);
           terminal.frametimer(a1 <> 0);
           params := params+intsize;

       end;

       81: begin { autohold@p_b }

           a1 := getint(params);
           terminal.autohold(a1 <> 0);
           params := params+intsize;

       end;

       82: begin { wrtstr@p_fc_vc }

           ad := getadr(params+strparsiz); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           getstr(params, s);
           terminal.wrtstr(output, s);
           params := params+adrsize+strparsiz;

       end;

       83: begin { wrtstr@p_vc }

           getstr(params, s);
           terminal.wrtstr(s);
           params := params+strparsiz;

       end;

       84: begin { sizbuf@p_fc_i_i }

           ad := getadr(params+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.sizbuf(output, a1, a2);
           params := params+adrsize+intsize+intsize;

       end;

       85: begin { sizbuf@p_i_i }

           a1 := getint(params+intsize);
           a2 := getint(params);
           terminal.sizbuf(a1, a2);
           params := params+intsize+intsize;

       end;

       86: begin { title@p_fc_vc }

           ad := getadr(params+strparsiz); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           getstr(params, s);
           terminal.title(output, s);
           params := params+adrsize+strparsiz;

       end;

       87: begin { title@p_vc }

           getstr(params, s);
           terminal.title(s);
           params := params+strparsiz;

       end;

       88: begin { fcolorc@p_fc_i_i_i }

           ad := getadr(params+intsize+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.fcolorc(output, a1, a2, a3);
           params := params+adrsize+intsize+intsize+intsize;

       end;

       89: begin { fcolorc@p_i_i_i }

           a1 := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.fcolorc(a1, a2, a3);
           params := params+intsize+intsize+intsize;

       end;

       90: begin { bcolorc@p_fc_i_i_i }

           ad := getadr(params+intsize+intsize+intsize); valfil(ad); fn := getbyt(ad);
           if fn > commandfn then errore(FileModeIncorrect);
           a1 := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.bcolorc(output, a1, a2, a3);
           params := params+adrsize+intsize+intsize+intsize;

       end;

       91: begin { bcolorc@p_i_i_i }

           a1 := getint(params+intsize+intsize);
           a2 := getint(params+intsize);
           a3 := getint(params);
           terminal.bcolorc(a1, a2, a3);
           params := params+intsize+intsize+intsize;

       end;

       92: begin { eventover }

           evtsetup;
           ad := getadr(params); { out oeh }
           ad2 := getadr(params+adrsize); { handler address }
           a1 := getadr(params+adrsize+ptrsize); { handler frame }
           { only global-level handlers: nested ones need the
             planned thunk securing }
           if ad2 <> 0 then if a1 <> globalframe then
              errore(FunctionNotImplemented);
           a2 := getint(params+adrsize+ptrsize*2); { event code }
           putint(ad, vmhand[a2+1]);
           vmhand[a2+1] := ad2;
           if not hooked[a2+1] then begin

              terminal.eventover(cnvevtcod(a2), evtthunk, a3);
              hooked[a2+1] := true

           end;
           params := params+adrsize+ptrsize*2+intsize

       end;

       93: begin { eventsover }

           evtsetup;
           ad := getadr(params); { out oeh }
           ad2 := getadr(params+adrsize); { handler address }
           a1 := getadr(params+adrsize+ptrsize); { handler frame }
           { only global-level handlers: nested ones need the
             planned thunk securing }
           if ad2 <> 0 then if a1 <> globalframe then
              errore(FunctionNotImplemented);
           putint(ad, vmhandall);
           vmhandall := ad2;
           if not hookedall then begin

              terminal.eventsover(evtsthunk, a3);
              hookedall := true

           end;
           params := params+adrsize+ptrsize*2

       end;

    else errore(FunctionNotImplemented)

    end

end;

procedure execgraph(routine: integer; var params: integer);

begin

   refer(routine);
   refer(params);

   errore(FunctionNotImplemented)

end;

begin
end.
