!
! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
!
p       /home/samiam/projects/pascal/pascal-p6/libs/source/terminal.pas
o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv- 
! {******************************************************************************
:1
! *                                                                             *
! *                         TERMINAL MODEL LIBRARY                              *
! *                                                                             *
! *                           Copyright (C) 2024                                *
! *                                                                             *
! *                               S. A. FRANCO                                  *
! *                                                                             *
! * Defines the Pascaline interface to the Ami terminal module. The             *
! * terminal interface describes a 2 dimensional, fixed window on which         *
! * characters are drawn. Each character can have colors or attributes. The     *
! * size of the window can be determined, and timer, mouse, and joystick        *
! * services are supported.                                                     *
! *                                                                             *
! * This is the Pascaline binding. The actual implementation lives in the C     *
! * Ami terminal module (terminal.c), reached through terminal_wrapper.         *
! *                                                                             *
! ******************************************************************************}
!
! module terminal;
:2
:3
:4
:5
:6
:7
:8
:9
:10
:11
:12
:13
:14
:15
:16
:17
:18
:19
:20
!
! Module terminal
!
b       m       terminal
        sfr     l terminal.6            ! Set function result
l terminal.6=0
        cup     l terminal.3 0           ! Call user procedure
        cal     l terminal.5            ! Call initializer code strip
        sfr     l terminal.6            ! Set function result
        cup     l terminal.4 0           ! Call user procedure
        ret                             ! Return code strip
!
! const
:21
:22
!
!    maxtim = 10; { maximum number of timers available }
:23
:24
!
! type
:25
:26
!
!    { colors displayable in text mode }
!    color = (black, white, red, green, blue, cyan, yellow, magenta);
:27
:28
:29
!
!    { events }
!    evtcod = (etchar,    { ANSI character returned }
:30
:31
:32
!              etup,      { cursor up one line }
:33
!              etdown,    { down one line }
:34
!              etleft,    { left one character }
:35
!              etright,   { right one character }
:36
!              etleftw,   { left one word }
:37
!              etrightw,  { right one word }
:38
!              ethome,    { home of document }
:39
!              ethomes,   { home of screen }
:40
!              ethomel,   { home of line }
:41
!              etend,     { end of document }
:42
!              etends,    { end of screen }
:43
!              etendl,    { end of line }
:44
!              etscrl,    { scroll left one character }
:45
!              etscrr,    { scroll right one character }
:46
!              etscru,    { scroll up one line }
:47
!              etscrd,    { scroll down one line }
:48
!              etpagd,    { page down }
:49
!              etpagu,    { page up }
:50
!              ettab,     { tab }
:51
!              etenter,   { enter line }
:52
!              etinsert,  { insert block }
:53
!              etinsertl, { insert line }
:54
!              etinsertt, { insert toggle }
:55
!              etdel,     { delete block }
:56
!              etdell,    { delete line }
:57
!              etdelcf,   { delete character forward }
:58
!              etdelcb,   { delete character backward }
:59
!              etcopy,    { copy block }
:60
!              etcopyl,   { copy line }
:61
!              etcan,     { cancel current operation }
:62
!              etstop,    { stop current operation }
:63
!              etcont,    { continue current operation }
:64
!              etprint,   { print document }
:65
!              etprintb,  { print block }
:66
!              etprints,  { print screen }
:67
!              etfun,     { function key }
:68
!              etmenu,    { display menu }
:69
!              etmouba,   { mouse button assertion }
:70
!              etmoubd,   { mouse button deassertion }
:71
!              etmoumov,  { mouse move }
:72
!              ettim,     { timer matures }
:73
!              etjoyba,   { joystick button assertion }
:74
!              etjoybd,   { joystick button deassertion }
:75
!              etjoymov,  { joystick move }
:76
!              etresize,  { window was resized }
:77
!              etfocus,   { window has focus }
:78
!              etnofocus, { window lost focus }
:79
!              ethover,   { window being hovered }
:80
!              etnohover, { window stopped being hovered }
:81
!              etterm,    { terminate program }
:82
!              etframe,   { frame sync }
:83
!              etredraw,  { window redraw }
:84
!              etmin,     { window minimized }
:85
!              etmax,     { window maximized }
:86
!              etnorm,    { window normalized }
:87
!              etmenus);  { menu item selected }
:88
!
!    { event record }
!    evtptr = ^evtrec;
:89
:90
:91
!    evtrec = record
:92
!
!       winid:   integer; { identifier of window for event }
:93
:94
!       handled: boolean; { event was handled }
:95
!       case etype: evtcod of { event type }
:96
!
!          { events that carry parameter data }
!          etchar:   (echar: char);                  { ANSI character returned }
:97
:98
:99
!          ettim:    (timnum: integer);              { timer handle that matured }
:100
!          etmoumov: (mmoun, moupx, moupy: integer); { mouse number and movement }
:101
!          etmouba:  (amoun, amoubn: integer);       { mouse and button asserted }
:102
!          etmoubd:  (dmoun, dmoubn: integer);       { mouse and button deasserted }
:103
!          etjoyba:  (ajoyn, ajoybn: integer);       { joystick and button asserted }
:104
!          etjoybd:  (djoyn, djoybn: integer);       { joystick and button deasserted }
:105
!          etjoymov: (mjoyn, joypx, joypy, joypz,    { joystick and coordinates }
:106
!                     joyp4, joyp5, joyp6: integer);
:107
!          etfun:    (fkey: integer);                { function key number }
:108
!          etresize: (rszx, rszy: integer);          { new window size }
:109
!          etmenus:  (menuid: integer);              { menu item selected }
:110
!
!          { events without parameter data carry no fields }
!          etup, etdown, etleft, etright, etleftw, etrightw, ethome, ethomes,
:111
:112
:113
!          ethomel, etend, etends, etendl, etscrl, etscrr, etscru, etscrd, etpagd,
:114
!          etpagu, ettab, etenter, etinsert, etinsertl, etinsertt, etdel, etdell,
:115
!          etdelcf, etdelcb, etcopy, etcopyl, etcan, etstop, etcont, etprint,
:116
!          etprintb, etprints, etmenu, etfocus, etnofocus, ethover, etnohover,
:117
!          etterm, etframe, etredraw, etmin, etmax, etnorm: ()
:118
!
!    end;
v       l terminal.7 57 1 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 9 12 4 5 3 2 6 7 8 10 12 12 12 12 12 12 12 12 12 12 11
:119
:120
!
! {
!  * Routines at this level. Each screen routine has an explicit file form
!  * (var f: text) and a default form that operates on the standard output
!  * (or, for event, the standard input).
! }
! procedure cursor(var f: text; x, y: integer); external;
:121
:122
:123
:124
:125
:126
:127
! overload procedure cursor(x, y: integer); external;
z 0 0 terminal.cursor@p_fc_i_i
:128
! function maxx(var f: text): integer; external;
z 0 0 terminal.cursor@p_i_i
:129
! overload function maxx: integer; external;
z 0 0 terminal.maxx@f_fc
:130
! function maxy(var f: text): integer; external;
z 0 0 terminal.maxx@f
:131
! overload function maxy: integer; external;
z 0 0 terminal.maxy@f_fc
:132
! procedure home(var f: text); external;
z 0 0 terminal.maxy@f
:133
! overload procedure home; external;
z 0 0 terminal.home@p_fc
:134
! procedure del(var f: text); external;
z 0 0 terminal.home@p
:135
! overload procedure del; external;
z 0 0 terminal.del@p_fc
:136
! procedure up(var f: text); external;
z 0 0 terminal.del@p
:137
! overload procedure up; external;
z 0 0 terminal.up@p_fc
:138
! procedure down(var f: text); external;
z 0 0 terminal.up@p
:139
! overload procedure down; external;
z 0 0 terminal.down@p_fc
:140
! procedure left(var f: text); external;
z 0 0 terminal.down@p
:141
! overload procedure left; external;
z 0 0 terminal.left@p_fc
:142
! procedure right(var f: text); external;
z 0 0 terminal.left@p
:143
! overload procedure right; external;
z 0 0 terminal.right@p_fc
:144
! procedure blink(var f: text; e: boolean); external;
z 0 0 terminal.right@p
:145
! overload procedure blink(e: boolean); external;
z 0 0 terminal.blink@p_fc_b
:146
! procedure reverse(var f: text; e: boolean); external;
z 0 0 terminal.blink@p_b
:147
! overload procedure reverse(e: boolean); external;
z 0 0 terminal.reverse@p_fc_b
:148
! procedure underline(var f: text; e: boolean); external;
z 0 0 terminal.reverse@p_b
:149
! overload procedure underline(e: boolean); external;
z 0 0 terminal.underline@p_fc_b
:150
! procedure superscript(var f: text; e: boolean); external;
z 0 0 terminal.underline@p_b
:151
! overload procedure superscript(e: boolean); external;
z 0 0 terminal.superscript@p_fc_b
:152
! procedure subscript(var f: text; e: boolean); external;
z 0 0 terminal.superscript@p_b
:153
! overload procedure subscript(e: boolean); external;
z 0 0 terminal.subscript@p_fc_b
:154
! procedure italic(var f: text; e: boolean); external;
z 0 0 terminal.subscript@p_b
:155
! overload procedure italic(e: boolean); external;
z 0 0 terminal.italic@p_fc_b
:156
! procedure bold(var f: text; e: boolean); external;
z 0 0 terminal.italic@p_b
:157
! overload procedure bold(e: boolean); external;
z 0 0 terminal.bold@p_fc_b
:158
! procedure strikeout(var f: text; e: boolean); external;
z 0 0 terminal.bold@p_b
:159
! overload procedure strikeout(e: boolean); external;
z 0 0 terminal.strikeout@p_fc_b
:160
! procedure standout(var f: text; e: boolean); external;
z 0 0 terminal.strikeout@p_b
:161
! overload procedure standout(e: boolean); external;
z 0 0 terminal.standout@p_fc_b
:162
! procedure fcolor(var f: text; c: color); external;
z 0 0 terminal.standout@p_b
:163
! overload procedure fcolor(c: color); external;
z 0 0 terminal.fcolor@p_fc_x(black,white,red,green,blue,cyan,yellow,magenta)
:164
! procedure bcolor(var f: text; c: color); external;
z 0 0 terminal.fcolor@p_x(black,white,red,green,blue,cyan,yellow,magenta)
:165
! overload procedure bcolor(c: color); external;
z 0 0 terminal.bcolor@p_fc_x(black,white,red,green,blue,cyan,yellow,magenta)
:166
! procedure auto(var f: text; e: boolean); external;
z 0 0 terminal.bcolor@p_x(black,white,red,green,blue,cyan,yellow,magenta)
:167
! overload procedure auto(e: boolean); external;
z 0 0 terminal.auto@p_fc_b
:168
! procedure curvis(var f: text; e: boolean); external;
z 0 0 terminal.auto@p_b
:169
! overload procedure curvis(e: boolean); external;
z 0 0 terminal.curvis@p_fc_b
:170
! procedure scroll(var f: text; x, y: integer); external;
z 0 0 terminal.curvis@p_b
:171
! overload procedure scroll(x, y: integer); external;
z 0 0 terminal.scroll@p_fc_i_i
:172
! function curx(var f: text): integer; external;
z 0 0 terminal.scroll@p_i_i
:173
! overload function curx: integer; external;
z 0 0 terminal.curx@f_fc
:174
! function cury(var f: text): integer; external;
z 0 0 terminal.curx@f
:175
! overload function cury: integer; external;
z 0 0 terminal.cury@f_fc
:176
! function curbnd(var f: text): boolean; external;
z 0 0 terminal.cury@f
:177
! overload function curbnd: boolean; external;
z 0 0 terminal.curbnd@f_fc
:178
! procedure select(var f: text; u, d: integer); external;
z 0 0 terminal.curbnd@f
:179
! overload procedure select(u, d: integer); external;
z 0 0 terminal.select@p_fc_i_i
:180
! procedure event(var f: text; var er: evtrec); external;
z 0 0 terminal.select@p_i_i
:181
! overload procedure event(var er: evtrec); external;
z 0 0 terminal.event@p_fc_r(winid:0:i,handled:8:b,etype:9:x(etchar,etup,etdown,etleft,etright,etleftw,etrightw,ethome,ethomes,ethomel,etend,etends,etendl,etscrl,etscrr,etscru,etscrd,etpagd,etpagu,ettab,etenter,etinsert,etinsertl,etinsertt,etdel,etdell,etdelcf,etdelcb,etcopy,etcopyl,etcan,etstop,etcont,etprint,etprintb,etprints,etfun,etmenu,etmouba,etmoubd,etmoumov,ettim,etjoyba,etjoybd,etjoymov,etresize,etfocus,etnofocus,ethover,etnohover,etterm,etframe,etredraw,etmin,etmax,etnorm,etmenus)(55()54()53()52()51()50()49()48()47()46()37()35()34()33()32()31()30()29()28()27()26()25()24()23()22()21()20()19()18()17()16()15()14()13()12()11()10()9()8()7()6()5()4()3()2()1()56(menuid:12:i)45(rszx:20:i,rszy:12:i)36(fkey:12:i)44(mjoyn:60:i,joypx:52:i,joypy:44:i,joypz:36:i,joyp4:28:i,joyp5:20:i,joyp6:12:i)43(djoyn:20:i,djoybn:12:i)42(ajoyn:20:i,ajoybn:12:i)39(dmoun:20:i,dmoubn:12:i)38(amoun:20:i,amoubn:12:i)40(mmoun:28:i,moupx:20:i,moupy:12:i)41(timnum:12:i)0(echar:12:c)))
:182
! procedure timer(var f: text; i: integer; t: integer; r: boolean); external;
z 0 0 terminal.event@p_r(winid:0:i,handled:8:b,etype:9:x(etchar,etup,etdown,etleft,etright,etleftw,etrightw,ethome,ethomes,ethomel,etend,etends,etendl,etscrl,etscrr,etscru,etscrd,etpagd,etpagu,ettab,etenter,etinsert,etinsertl,etinsertt,etdel,etdell,etdelcf,etdelcb,etcopy,etcopyl,etcan,etstop,etcont,etprint,etprintb,etprints,etfun,etmenu,etmouba,etmoubd,etmoumov,ettim,etjoyba,etjoybd,etjoymov,etresize,etfocus,etnofocus,ethover,etnohover,etterm,etframe,etredraw,etmin,etmax,etnorm,etmenus)(55()54()53()52()51()50()49()48()47()46()37()35()34()33()32()31()30()29()28()27()26()25()24()23()22()21()20()19()18()17()16()15()14()13()12()11()10()9()8()7()6()5()4()3()2()1()56(menuid:12:i)45(rszx:20:i,rszy:12:i)36(fkey:12:i)44(mjoyn:60:i,joypx:52:i,joypy:44:i,joypz:36:i,joyp4:28:i,joyp5:20:i,joyp6:12:i)43(djoyn:20:i,djoybn:12:i)42(ajoyn:20:i,ajoybn:12:i)39(dmoun:20:i,dmoubn:12:i)38(amoun:20:i,amoubn:12:i)40(mmoun:28:i,moupx:20:i,moupy:12:i)41(timnum:12:i)0(echar:12:c)))
:183
! overload procedure timer(i: integer; t: integer; r: boolean); external;
z 0 0 terminal.timer@p_fc_i_i_b
:184
! procedure killtimer(var f: text; i: integer); external;
z 0 0 terminal.timer@p_i_i_b
:185
! overload procedure killtimer(i: integer); external;
z 0 0 terminal.killtimer@p_fc_i
:186
! function mouse(var f: text): integer; external;
z 0 0 terminal.killtimer@p_i
:187
! overload function mouse: integer; external;
z 0 0 terminal.mouse@f_fc
:188
! function mousebutton(var f: text; m: integer): integer; external;
z 0 0 terminal.mouse@f
:189
! overload function mousebutton(m: integer): integer; external;
z 0 0 terminal.mousebutton@f_fc_i
:190
! function joystick(var f: text): integer; external;
z 0 0 terminal.mousebutton@f_i
:191
! overload function joystick: integer; external;
z 0 0 terminal.joystick@f_fc
:192
! function joybutton(var f: text; j: integer): integer; external;
z 0 0 terminal.joystick@f
:193
! overload function joybutton(j: integer): integer; external;
z 0 0 terminal.joybutton@f_fc_i
:194
! function joyaxis(var f: text; j: integer): integer; external;
z 0 0 terminal.joybutton@f_i
:195
! overload function joyaxis(j: integer): integer; external;
z 0 0 terminal.joyaxis@f_fc_i
:196
! procedure settab(var f: text; t: integer); external;
z 0 0 terminal.joyaxis@f_i
:197
! overload procedure settab(t: integer); external;
z 0 0 terminal.settab@p_fc_i
:198
! procedure restab(var f: text; t: integer); external;
z 0 0 terminal.settab@p_i
:199
! overload procedure restab(t: integer); external;
z 0 0 terminal.restab@p_fc_i
:200
! procedure clrtab(var f: text); external;
z 0 0 terminal.restab@p_i
:201
! overload procedure clrtab; external;
z 0 0 terminal.clrtab@p_fc
:202
! function funkey(var f: text): integer; external;
z 0 0 terminal.clrtab@p
:203
! overload function funkey: integer; external;
z 0 0 terminal.funkey@f_fc
:204
! procedure frametimer(var f: text; e: boolean); external;
z 0 0 terminal.funkey@f
:205
! overload procedure frametimer(e: boolean); external;
z 0 0 terminal.frametimer@p_fc_b
:206
! procedure autohold(e: boolean); external;
z 0 0 terminal.frametimer@p_b
:207
! procedure wrtstr(var f: text; view s: string); external;
z 0 0 terminal.autohold@p_b
:208
! overload procedure wrtstr(view s: string); external;
z 0 0 terminal.wrtstr@p_fc_vc
:209
! procedure sizbuf(var f: text; x, y: integer); external;
z 0 0 terminal.wrtstr@p_vc
:210
! overload procedure sizbuf(x, y: integer); external;
z 0 0 terminal.sizbuf@p_fc_i_i
:211
! procedure title(var f: text; view ts: string); external;
z 0 0 terminal.sizbuf@p_i_i
:212
! overload procedure title(view ts: string); external;
z 0 0 terminal.title@p_fc_vc
:213
! procedure fcolorc(var f: text; r, g, b: integer); external;
z 0 0 terminal.title@p_vc
:214
! overload procedure fcolorc(r, g, b: integer); external;
z 0 0 terminal.fcolorc@p_fc_i_i_i
:215
! procedure bcolorc(var f: text; r, g, b: integer); external;
z 0 0 terminal.fcolorc@p_i_i_i
:216
! overload procedure bcolorc(r, g, b: integer); external;
z 0 0 terminal.bcolorc@p_fc_i_i_i
:217
! procedure eventover(e: evtcod; procedure eh(var er: evtrec); out oeh: integer);
z 0 0 terminal.bcolorc@p_i_i_i
:218
!    external;
:219
! procedure eventsover(procedure eh(var er: evtrec); out oeh: integer); external;
z 0 0 terminal.eventover@p_x(etchar,etup,etdown,etleft,etright,etleftw,etrightw,ethome,ethomes,ethomel,etend,etends,etendl,etscrl,etscrr,etscru,etscrd,etpagd,etpagu,ettab,etenter,etinsert,etinsertl,etinsertt,etdel,etdell,etdelcf,etdelcb,etcopy,etcopyl,etcan,etstop,etcont,etprint,etprintb,etprints,etfun,etmenu,etmouba,etmoubd,etmoumov,ettim,etjoyba,etjoybd,etjoymov,etresize,etfocus,etnofocus,ethover,etnohover,etterm,etframe,etredraw,etmin,etmax,etnorm,etmenus)_q(r(winid:0:i,handled:8:b,etype:9:x(etchar,etup,etdown,etleft,etright,etleftw,etrightw,ethome,ethomes,ethomel,etend,etends,etendl,etscrl,etscrr,etscru,etscrd,etpagd,etpagu,ettab,etenter,etinsert,etinsertl,etinsertt,etdel,etdell,etdelcf,etdelcb,etcopy,etcopyl,etcan,etstop,etcont,etprint,etprintb,etprints,etfun,etmenu,etmouba,etmoubd,etmoumov,ettim,etjoyba,etjoybd,etjoymov,etresize,etfocus,etnofocus,ethover,etnohover,etterm,etframe,etredraw,etmin,etmax,etnorm,etmenus)(55()54()53()52()51()50()49()48()47()46()37()35()34()33()32()31()30()29()28()27()26()25()24()23()22()21()20()19()18()17()16()15()14()13()12()11()10()9()8()7()6()5()4()3()2()1()56(menuid:12:i)45(rszx:20:i,rszy:12:i)36(fkey:12:i)44(mjoyn:60:i,joypx:52:i,joypy:44:i,joypz:36:i,joyp4:28:i,joyp5:20:i,joyp6:12:i)43(djoyn:20:i,djoybn:12:i)42(ajoyn:20:i,ajoybn:12:i)39(dmoun:20:i,dmoubn:12:i)38(amoun:20:i,amoubn:12:i)40(mmoun:28:i,moupx:20:i,moupy:12:i)41(timnum:12:i)0(echar:12:c))))_i
:220
!
! begin
z 0 0 terminal.eventsover@p_q(r(winid:0:i,handled:8:b,etype:9:x(etchar,etup,etdown,etleft,etright,etleftw,etrightw,ethome,ethomes,ethomel,etend,etends,etendl,etscrl,etscrr,etscru,etscrd,etpagd,etpagu,ettab,etenter,etinsert,etinsertl,etinsertt,etdel,etdell,etdelcf,etdelcb,etcopy,etcopyl,etcan,etstop,etcont,etprint,etprintb,etprints,etfun,etmenu,etmouba,etmoubd,etmoumov,ettim,etjoyba,etjoybd,etjoymov,etresize,etfocus,etnofocus,ethover,etnohover,etterm,etframe,etredraw,etmin,etmax,etnorm,etmenus)(55()54()53()52()51()50()49()48()47()46()37()35()34()33()32()31()30()29()28()27()26()25()24()23()22()21()20()19()18()17()16()15()14()13()12()11()10()9()8()7()6()5()4()3()2()1()56(menuid:12:i)45(rszx:20:i,rszy:12:i)36(fkey:12:i)44(mjoyn:60:i,joypx:52:i,joypy:44:i,joypz:36:i,joyp4:28:i,joyp5:20:i,joyp6:12:i)43(djoyn:20:i,djoybn:12:i)42(ajoyn:20:i,ajoybn:12:i)39(dmoun:20:i,dmoubn:12:i)38(amoun:20:i,amoubn:12:i)40(mmoun:28:i,moupx:20:i,moupy:12:i)41(timnum:12:i)0(echar:12:c))))_i
l terminal.3
:221
:222
:222
        mst     0 l terminal.101 l terminal.102 ! Mark(frame) stack
! end.
:223
        retp    0                       ! Return from procedure/function(t)
l terminal.101=0
l terminal.102=0
l terminal.4
        mst     0 l terminal.104 l terminal.105 ! Mark(frame) stack
        retp    0                       ! Return from procedure/function(t)
l terminal.104=0
l terminal.105=0
l terminal.5
g 89
e m
f       0
