{*******************************************************************************

Reserved word hash table

!!! DO NOT EDIT !!!

This file is autoamatically generated by hashtabr.

*******************************************************************************}

module restbl;

uses strings, { string functions}
     tolkens; { scanner tolkens }

const

    resmax = 81;
    hashoff = 6;

type

    resinx = 1..resmax; { index for reserved table }
    resequ = record { reserved word table entry }

                 lab:  pstring;  { reserved word }
                 tolk: tolken;   { equivalent tolken }
                 chn:  0..resmax { chain to next entry }

             end;

var

    restbl: array [resinx] of resequ; { reserved words table }

begin

    restbl[  1].lab := copy('while'); restbl[  1].chn :=   0;
    restbl[  1].tolk := c_while;
    restbl[  2].lab := copy('and'); restbl[  2].chn :=   0;
    restbl[  2].tolk := c_and;
    restbl[  3].lab := copy('nil'); restbl[  3].chn :=  19;
    restbl[  3].tolk := c_nil;
    restbl[  4].lab := copy('case'); restbl[  4].chn :=   0;
    restbl[  4].tolk := c_case;
    restbl[  5].lab := copy('packed'); restbl[  5].chn :=   0;
    restbl[  5].tolk := c_packed;
    restbl[  6].lab := copy('end'); restbl[  6].chn :=   0;
    restbl[  6].tolk := c_end;
    restbl[  7].lab := copy('array'); restbl[  7].chn :=   0;
    restbl[  7].tolk := c_array;
    restbl[  8].lab := copy('virtual'); restbl[  8].chn :=   0;
    restbl[  8].tolk := c_virtual;
    restbl[  9].lab := copy('monitor'); restbl[  9].chn :=   0;
    restbl[  9].tolk := c_monitor;
    restbl[ 10].lab := copy('begin'); restbl[ 10].chn :=   0;
    restbl[ 10].tolk := c_begin;
    restbl[ 11].lab := copy('joins'); restbl[ 11].chn :=   0;
    restbl[ 11].tolk := c_joins;
    restbl[ 12].lab := copy('with'); restbl[ 12].chn :=   0;
    restbl[ 12].tolk := c_with;
    restbl[ 13].lab := copy('const'); restbl[ 13].chn :=   0;
    restbl[ 13].tolk := c_const;
    restbl[ 14].lab := copy('function'); restbl[ 14].chn :=   0;
    restbl[ 14].tolk := c_function;
    restbl[ 15].lab := copy('mod'); restbl[ 15].chn :=  13;
    restbl[ 15].tolk := c_mod;
    restbl[ 16].lab := copy('share'); restbl[ 16].chn :=   0;
    restbl[ 16].tolk := c_share;
    restbl[ 17].lab := copy('is'); restbl[ 17].chn :=   0;
    restbl[ 17].tolk := c_is;
    restbl[ 18].lab := copy('div'); restbl[ 18].chn :=   3;
    restbl[ 18].tolk := c_div;
    restbl[ 19].lab := copy('overload'); restbl[ 19].chn :=   0;
    restbl[ 19].tolk := c_overload;
    restbl[ 20].lab := copy('until'); restbl[ 20].chn :=   0;
    restbl[ 20].tolk := c_until;
    restbl[ 21].lab := copy('thread'); restbl[ 21].chn :=   0;
    restbl[ 21].tolk := c_thread;
    restbl[ 22].lab := copy('for'); restbl[ 22].chn :=  23;
    restbl[ 22].tolk := c_for;
    restbl[ 23].lab := copy('override'); restbl[ 23].chn :=   0;
    restbl[ 23].tolk := c_override;
    restbl[ 24].lab := copy('var'); restbl[ 24].chn :=   0;
    restbl[ 24].tolk := c_var;
    restbl[ 25].lab := copy('external'); restbl[ 25].chn :=   0;
    restbl[ 25].tolk := c_external;
    restbl[ 26].lab := copy('reference'); restbl[ 26].chn :=   0;
    restbl[ 26].tolk := c_reference;
    restbl[ 27].lab := copy('set'); restbl[ 27].chn :=   0;
    restbl[ 27].tolk := c_set;
    restbl[ 28].lab := copy('record'); restbl[ 28].chn :=  14;
    restbl[ 28].tolk := c_record;
    restbl[ 29].lab := copy('try'); restbl[ 29].chn :=   0;
    restbl[ 29].tolk := c_try;
    restbl[ 30].lab := copy('repeat'); restbl[ 30].chn :=   0;
    restbl[ 30].tolk := c_repeat;
    restbl[ 31].lab := copy('extends'); restbl[ 31].chn :=   0;
    restbl[ 31].tolk := c_extends;
    restbl[ 32].lab := copy('not'); restbl[ 32].chn :=   4;
    restbl[ 32].tolk := c_not;
    restbl[ 33].lab := copy('property'); restbl[ 33].chn :=   0;
    restbl[ 33].tolk := c_property;
    restbl[ 34].lab := copy('operator'); restbl[ 34].chn :=   0;
    restbl[ 34].tolk := c_operator;
    restbl[ 35].lab := copy('module'); restbl[ 35].chn :=   0;
    restbl[ 35].tolk := c_module;
    restbl[ 36].lab := copy('file'); restbl[ 36].chn :=   0;
    restbl[ 36].tolk := c_file;
    restbl[ 37].lab := copy('static'); restbl[ 37].chn :=   0;
    restbl[ 37].tolk := c_static;
    restbl[ 38].lab := copy('except'); restbl[ 38].chn :=   0;
    restbl[ 38].tolk := c_except;
    restbl[ 39].lab := copy('inherited'); restbl[ 39].chn :=  42;
    restbl[ 39].tolk := c_inherited;
    restbl[ 40].lab := copy('xor'); restbl[ 40].chn :=   0;
    restbl[ 40].tolk := c_xor;
    restbl[ 41].lab := copy('stream'); restbl[ 41].chn :=   0;
    restbl[ 41].tolk := c_stream;
    restbl[ 42].lab := copy('out'); restbl[ 42].chn :=   0;
    restbl[ 42].tolk := c_out;
    restbl[ 43].lab := copy('channel'); restbl[ 43].chn :=   0;
    restbl[ 43].tolk := c_channel;
    restbl[ 44].lab := copy('<undefined>'); restbl[ 44].chn :=   0;
    restbl[ 44].tolk := c_undefined;
    restbl[ 45].lab := copy('else'); restbl[ 45].chn :=   0;
    restbl[ 45].tolk := c_else;
    restbl[ 46].lab := copy('self'); restbl[ 46].chn :=  29;
    restbl[ 46].tolk := c_self;
    restbl[ 47].lab := copy('<undefined>'); restbl[ 47].chn :=   0;
    restbl[ 47].tolk := c_undefined;
    restbl[ 48].lab := copy('<undefined>'); restbl[ 48].chn :=   0;
    restbl[ 48].tolk := c_undefined;
    restbl[ 49].lab := copy('cexternal'); restbl[ 49].chn :=   0;
    restbl[ 49].tolk := c_cexternal;
    restbl[ 50].lab := copy('<undefined>'); restbl[ 50].chn :=   0;
    restbl[ 50].tolk := c_undefined;
    restbl[ 51].lab := copy('then'); restbl[ 51].chn :=   0;
    restbl[ 51].tolk := c_then;
    restbl[ 52].lab := copy('procedure'); restbl[ 52].chn :=   0;
    restbl[ 52].tolk := c_procedure;
    restbl[ 53].lab := copy('atom'); restbl[ 53].chn :=   0;
    restbl[ 53].tolk := c_atom;
    restbl[ 54].lab := copy('<undefined>'); restbl[ 54].chn :=   0;
    restbl[ 54].tolk := c_undefined;
    restbl[ 55].lab := copy('task'); restbl[ 55].chn :=   0;
    restbl[ 55].tolk := c_task;
    restbl[ 56].lab := copy('downto'); restbl[ 56].chn :=   0;
    restbl[ 56].tolk := c_downto;
    restbl[ 57].lab := copy('label'); restbl[ 57].chn :=   0;
    restbl[ 57].tolk := c_label;
    restbl[ 58].lab := copy('if'); restbl[ 58].chn :=   0;
    restbl[ 58].tolk := c_if;
    restbl[ 59].lab := copy('mexternal'); restbl[ 59].chn :=  33;
    restbl[ 59].tolk := c_mexternal;
    restbl[ 60].lab := copy('result'); restbl[ 60].chn :=   0;
    restbl[ 60].tolk := c_result;
    restbl[ 61].lab := copy('goto'); restbl[ 61].chn :=   0;
    restbl[ 61].tolk := c_goto;
    restbl[ 62].lab := copy('do'); restbl[ 62].chn :=  10;
    restbl[ 62].tolk := c_do;
    restbl[ 63].lab := copy('view'); restbl[ 63].chn :=   0;
    restbl[ 63].tolk := c_view;
    restbl[ 64].lab := copy('of'); restbl[ 64].chn :=  12;
    restbl[ 64].tolk := c_of;
    restbl[ 65].lab := copy('<undefined>'); restbl[ 65].chn :=   0;
    restbl[ 65].tolk := c_undefined;
    restbl[ 66].lab := copy('in'); restbl[ 66].chn :=   0;
    restbl[ 66].tolk := c_in;
    restbl[ 67].lab := copy('<undefined>'); restbl[ 67].chn :=   0;
    restbl[ 67].tolk := c_undefined;
    restbl[ 68].lab := copy('uses'); restbl[ 68].chn :=   0;
    restbl[ 68].tolk := c_uses;
    restbl[ 69].lab := copy('<undefined>'); restbl[ 69].chn :=   0;
    restbl[ 69].tolk := c_undefined;
    restbl[ 70].lab := copy('type'); restbl[ 70].chn :=   0;
    restbl[ 70].tolk := c_type;
    restbl[ 71].lab := copy('forward'); restbl[ 71].chn :=  17;
    restbl[ 71].tolk := c_forward;
    restbl[ 72].lab := copy('on'); restbl[ 72].chn :=   0;
    restbl[ 72].tolk := c_on;
    restbl[ 73].lab := copy('fixed'); restbl[ 73].chn :=   0;
    restbl[ 73].tolk := c_fixed;
    restbl[ 74].lab := copy('program'); restbl[ 74].chn :=   0;
    restbl[ 74].tolk := c_program;
    restbl[ 75].lab := copy('<undefined>'); restbl[ 75].chn :=   0;
    restbl[ 75].tolk := c_undefined;
    restbl[ 76].lab := copy('or'); restbl[ 76].chn :=  16;
    restbl[ 76].tolk := c_or;
    restbl[ 77].lab := copy('private'); restbl[ 77].chn :=  31;
    restbl[ 77].tolk := c_private;
    restbl[ 78].lab := copy('to'); restbl[ 78].chn :=   0;
    restbl[ 78].tolk := c_to;
    restbl[ 79].lab := copy('class'); restbl[ 79].chn :=   0;
    restbl[ 79].tolk := c_class;
    restbl[ 80].lab := copy('<undefined>'); restbl[ 80].chn :=   0;
    restbl[ 80].tolk := c_undefined;
    restbl[ 81].lab := copy('process'); restbl[ 81].chn :=   0;
    restbl[ 81].tolk := c_process;

end.
