{*******************************************************************************

Symbol hash table

!!! DO NOT EDIT !!!

This file is autoamatically generated by hashtabs.

*******************************************************************************}

module spctbl;

uses tolkens; { scanner tolkens }

const

    chrmax = 42; { number of special character sequences }
    chroff = 28; { special character hash offset }
    spcmax = 2;  { special character string length }

type

    chrinx = 1..chrmax; { special character index }
    chrstr = packed array [1..spcmax] of char; { special character string }
    chrequ = record { special character table entry }

                lab:  chrstr;   { characters }
                tolk: tolken;   { equivalent tolken }
                chn:  0..chrmax { next entry chain }

             end;

var

    spctbl: array [chrinx] of chrequ; { special character table }

begin

    spctbl[  1].lab  := '><';
    spctbl[  1].tolk := c_nequa;
    spctbl[  2].lab  := '=<';
    spctbl[  2].tolk := c_lequa;
    spctbl[  3].lab  := ': ';
    spctbl[  3].tolk := c_cln;
    spctbl[  4].lab  := '; ';
    spctbl[  4].tolk := c_scn;
    spctbl[  5].lab  := '< ';
    spctbl[  5].tolk := c_ltn;
    spctbl[  6].lab  := '= ';
    spctbl[  6].tolk := c_equ;
    spctbl[  7].lab  := '> ';
    spctbl[  7].tolk := c_gtn;
    spctbl[  8].lab  := ':=';
    spctbl[  8].tolk := c_bcms;
    spctbl[  9].lab  := '@ ';
    spctbl[  9].tolk := c_cmf;
    spctbl[ 10].lab  := '<='; spctbl[ 10].chn :=   2;
    spctbl[ 10].tolk := c_lequ;
    spctbl[ 11].lab  := '<>'; spctbl[ 11].chn :=   1;
    spctbl[ 11].tolk := c_nequ;
    spctbl[ 12].lab  := '>='; spctbl[ 12].chn :=  15;
    spctbl[ 12].tolk := c_gequ;
    spctbl[ 13].lab  := '(*';
    spctbl[ 13].tolk := c_lct;
    spctbl[ 14].lab  := '*)';
    spctbl[ 14].tolk := c_rct;
    spctbl[ 15].lab  := '=>';
    spctbl[ 15].tolk := c_gequa;
    spctbl[ 16].lab  := '} ';
    spctbl[ 16].tolk := c_rct;
    spctbl[ 17].lab  := '(.';
    spctbl[ 17].tolk := c_lbrkt;
    spctbl[ 18].lab  := '.)';
    spctbl[ 18].tolk := c_rbrkt;
    spctbl[ 19].lab  := '$ ';
    spctbl[ 19].tolk := c_hex;
    spctbl[ 20].lab  := '! ';
    spctbl[ 20].tolk := c_linc;
    spctbl[ 21].lab  := '  ';
    spctbl[ 21].tolk := c_undefined;
    spctbl[ 22].lab  := '# ';
    spctbl[ 22].tolk := c_num;
    spctbl[ 23].lab  := '..'; spctbl[ 23].chn :=  19;
    spctbl[ 23].tolk := c_range;
    spctbl[ 24].lab  := '% ';
    spctbl[ 24].tolk := c_bin;
    spctbl[ 25].lab  := '& ';
    spctbl[ 25].tolk := c_oct;
    spctbl[ 26].lab  := '{ ';
    spctbl[ 26].tolk := c_lct;
    spctbl[ 27].lab  := '( ';
    spctbl[ 27].tolk := c_lparen;
    spctbl[ 28].lab  := ') '; spctbl[ 28].chn :=  16;
    spctbl[ 28].tolk := c_rparen;
    spctbl[ 29].lab  := '* ';
    spctbl[ 29].tolk := c_times;
    spctbl[ 30].lab  := '+ ';
    spctbl[ 30].tolk := c_plus;
    spctbl[ 31].lab  := ', ';
    spctbl[ 31].tolk := c_cma;
    spctbl[ 32].lab  := '- ';
    spctbl[ 32].tolk := c_minus;
    spctbl[ 33].lab  := '. ';
    spctbl[ 33].tolk := c_period;
    spctbl[ 34].lab  := '/ ';
    spctbl[ 34].tolk := c_rdiv;
    spctbl[ 35].lab  := '  ';
    spctbl[ 35].tolk := c_undefined;
    spctbl[ 36].lab  := '[ ';
    spctbl[ 36].tolk := c_lbrkt;
    spctbl[ 37].lab  := '  ';
    spctbl[ 37].tolk := c_undefined;
    spctbl[ 38].lab  := '] ';
    spctbl[ 38].tolk := c_rbrkt;
    spctbl[ 39].lab  := '^ ';
    spctbl[ 39].tolk := c_cmf;
    spctbl[ 40].lab  := '  ';
    spctbl[ 40].tolk := c_undefined;
    spctbl[ 41].lab  := '  ';
    spctbl[ 41].tolk := c_undefined;
    spctbl[ 42].lab  := '  ';
    spctbl[ 42].tolk := c_undefined;

end.
