!
! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
!
p       /home/samiam/projects/pascal/pascal-p6/source/extend.pas
o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
! { 
:1
!
! Language extension routines. These routines allow specification of semantic
! functions beyond the base ISO 7185 specification. 
!
! }
!
! module extend;  
:2
:3
:4
:5
:6
:7
:8
!
! Module extend
!
b       m       extend
        sfr     l extend.6              ! Set function result
l extend.6=0
        cup     l extend.3 0             ! Call user procedure
        cal     l extend.5              ! Call initializer code strip
        sfr     l extend.6              ! Set function result
        cup     l extend.4 0             ! Call user procedure
        ret                             ! Return code strip
!
! procedure capture;
:9
:10
! begin
b r capture@p
l extend.7
:11
:11
        mst     1 l extend.8 l extend.9 ! Mark(frame) stack
! end;
:12
        retp    0                       ! Return from procedure/function(t)
l extend.8=112
l extend.9=0
!
! function chkbrk: boolean;
e r
:13
:14
! begin
b f chkbrk@f
l extend.11
:15
:15
        mst     1 l extend.12 l extend.13 ! Mark(frame) stack
!   chkbrk := false
:16
! end;
        ldcb    0                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
        strb    2 -72                   ! Store local(t)
:17
        retb    0                       ! Return from procedure/function(t)
l extend.12=112
l extend.13=8
!
! begin
e f
l extend.3
:18
:19
:19
        mst     0 l extend.15 l extend.16 ! Mark(frame) stack
! end.
:20
        retp    0                       ! Return from procedure/function(t)
l extend.15=0
l extend.16=0
l extend.4
        mst     0 l extend.18 l extend.19 ! Mark(frame) stack
        retp    0                       ! Return from procedure/function(t)
l extend.18=0
l extend.19=0
l extend.5
g 89
e m
f       0
