!
! Pascal intermediate file Generated by P6 Pascal compiler vs. 0.5
!
p       /home/samiam/projects/pascal/pascal-p6/source/genobj.pas
o prtlab- lstcod+ chk+ varblk- experror+ list- prttables- undestag+ chkvar+ prtlex- prtdisplay- amd64_sysv+ 
! {$l-}
:1
o       list-
! {*******************************************************************************
! *                                                                              *
! *                           GENERATE C OBJECT FILE                             *
! *                                                                              *
! * LICENSING:                                                                   *
! *                                                                              *
! * Copyright (c) 1996, 2018, Scott A. Franco                                    *
! * All rights reserved.                                                         *
! *                                                                              *
! * Redistribution and use in source and binary forms, with or without           *
! * modification, are permitted provided that the following conditions are met:  *
! *                                                                              *
! * 1. Redistributions of source code must retain the above copyright notice,    *
! *    this list of conditions and the following disclaimer.                     *
! * 2. Redistributions in binary form must reproduce the above copyright         *
! *    notice, this list of conditions and the following disclaimer in the       *
! *    documentation and/or other materials provided with the distribution.      *
! *                                                                              *
! * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"  *
! * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE    *
! * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE   *
! * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE     *
! * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR          *
! * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF         *
! * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS     *
! * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN      *
! * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)      *
! * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE   *
! * POSSIBILITY OF SUCH DAMAGE.                                                  *
! *                                                                              *
! * The views and conclusions contained in the software and documentation are    *
! * those of the authors and should not be interpreted as representing official  *
! * policies, either expressed or implied, of the Pascal-P6 project.             *
! *                                                                              *
! * FUNCTION:                                                                    *
! *                                                                              *
! * Generates a C constant data array with embedded code from a pmach generated  *
! * object file.                                                                 *
! *                                                                              *
! *******************************************************************************}
!
! program pmach(input,output,prd,prr);
:2
:3
:4
:5
:6
:7
:8
:9
:10
:11
:12
:13
:14
:15
:16
:17
:18
:19
:20
:21
:22
:23
:24
:25
:26
:27
:28
:29
:30
:31
:32
:33
:34
:35
:36
:37
:38
:39
:40
:41
:42
:43
!
! Program pmach
!
b       p       pmach
        sfr     l pmach.6               ! Set function result
l pmach.6=0
        cup     l pmach.3 0              ! Call user procedure
        ret                             ! Return code strip
!
! label 99;
:44
:45
!
! var prd,prr: text;
:46
:47
s       prr g 89 fc
s       prd g 91 fc
!
! procedure wrtnum(var tf: text; v: integer; r: integer; f: integer; lz: boolean);
:48
:49
! const digmax = 32;
b r wrtnum@p_fc_i_i_i_b
s       tf p -64 fc
s       v p -56 i
s       r p -48 i
s       f p -40 i
s       lz p -32 b
:50
! var p,i,x,d,t,n: integer; sgn: boolean;
:51
s       n l -128 i
s       t l -136 i
s       d l -144 i
s       x l -152 i
s       i l -160 i
s       p l -168 i
s       sgn l -169 b
!     digits: packed array [1..digmax] of char;
:52
t       l pmach.9 1 32
s       digits l -201 ax(1,32)ic
! function digit(d: integer): char;
:53
! var c: char;
b f digit@f_i
s       d p -72 i
:54
s       c l -129 c
! begin
l pmach.10
:55
:55
        mst     2 l pmach.11 l pmach.12 ! Mark(frame) stack
!   if d < 10 then c := chr(d+ord('0'))
:56
        lodi    3 -72                   ! Load local value(t)
        ldci    10                      ! Load constant(t)
        lesi                            ! Less than(t)
         fjp l pmach.14
        lodi    3 -72                   ! Load local value(t)
        ldcc    '0'                     ! Load constant(t)
        ordc                            ! Ordinal(t)
        adi                             ! Add integers
        chr                             ! Character from integer
!   else c := chr(d-10+ord('A'));
        chkc    0 255                   ! Bounds check(t)
        strc    3 -129                  ! Store local(t)
        ujp     l pmach.15              ! Unconditional jump
l pmach.14
:57
:57
        lodi    3 -72                   ! Load local value(t)
        ldci    10                      ! Load constant(t)
        sbi                             ! Subtract integer
        ldcc    'A'                     ! Load constant(t)
        ordc                            ! Ordinal(t)
        adi                             ! Add integers
        chr                             ! Character from integer
        chkc    0 255                   ! Bounds check(t)
        strc    3 -129                  ! Store local(t)
l pmach.15
:57
!   digit := c
:58
! end;
        lodc    3 -129                  ! Load local value(t)
        chkc    0 255                   ! Bounds check(t)
        strc    3 -80                   ! Store local(t)
:59
        retc    0                       ! Return from procedure/function(t)
l pmach.11=112
l pmach.12=16
! begin sgn := false;
e f
l pmach.8
:60
:60
        mst     1 l pmach.16 l pmach.17 ! Mark(frame) stack
        ldcb    0                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
        strb    2 -169                  ! Store local(t)
!    if (r = 10) and (v < 0) then begin sgn := true; v := -v; lz := false end;
:61
        lodi    2 -48                   ! Load local value(t)
        ldci    10                      ! Load constant(t)
        equi                            ! Equal(t)
        lodi    2 -56                   ! Load local value(t)
        ldci    0                       ! Load constant(t)
        lesi                            ! Less than(t)
        and                             ! And booleans
         fjp l pmach.19
        ldcb    1                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
        strb    2 -169                  ! Store local(t)
        lodi    2 -56                   ! Load local value(t)
        ngi                             ! Negate integer
        stri    2 -56                   ! Store local(t)
        ldcb    0                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
        strb    2 -32                   ! Store local(t)
l pmach.19
:61
!    if r = 16 then n := 8
:62
        lodi    2 -48                   ! Load local value(t)
        ldci    16                      ! Load constant(t)
        equi                            ! Equal(t)
         fjp l pmach.20
!    else if r = 10 then n := 10
        ldci    8                       ! Load constant(t)
        stri    2 -128                  ! Store local(t)
        ujp     l pmach.21              ! Unconditional jump
l pmach.20
:63
:63
        lodi    2 -48                   ! Load local value(t)
        ldci    10                      ! Load constant(t)
        equi                            ! Equal(t)
         fjp l pmach.22
!    else if r = 8 then n := 11
        ldci    10                      ! Load constant(t)
        stri    2 -128                  ! Store local(t)
        ujp     l pmach.23              ! Unconditional jump
l pmach.22
:64
:64
        lodi    2 -48                   ! Load local value(t)
        ldci    8                       ! Load constant(t)
        equi                            ! Equal(t)
         fjp l pmach.24
!    else n := 32;
        ldci    11                      ! Load constant(t)
        stri    2 -128                  ! Store local(t)
        ujp     l pmach.25              ! Unconditional jump
l pmach.24
:65
:65
        ldci    32                      ! Load constant(t)
        stri    2 -128                  ! Store local(t)
l pmach.25
:65
l pmach.23
:65
l pmach.21
:65
!    for i := 1 to digmax do digits[i] := '0';
:66
        ldci    1                       ! Load constant(t)
        stri    2 -209                  ! Store local(t)
        ldci    32                      ! Load constant(t)
        stri    2 -217                  ! Store local(t)
        lodi    2 -209                  ! Load local value(t)
        stri    2 -160                  ! Store local(t)
l pmach.26
:66
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        leqi                            ! Less than or equal(t)
        fjp     l pmach.27              ! False jump
        lda     2 -201                  ! Load local address
        lodi    2 -160                  ! Load local value(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        ldcc    '0'                     ! Load constant(t)
        chkc    0 255                   ! Bounds check(t)
        stoc                            ! Store to address(t)
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l pmach.27              ! True jump
        lodi    2 -160                  ! Load local value(t)
        inci    1                       ! Increment(t)
        stri    2 -160                  ! Store local(t)
        ujp     l pmach.26              ! Unconditional jump
l pmach.27
:66
        lda     2 -160                  ! Load local address
        inv                             ! Invalidate address
!    { adjust signed radix }
!    if (r = 16) and (v < 0) then begin
:67
:68
        lodi    2 -48                   ! Load local value(t)
        ldci    16                      ! Load constant(t)
        equi                            ! Equal(t)
        lodi    2 -56                   ! Load local value(t)
        ldci    0                       ! Load constant(t)
        lesi                            ! Less than(t)
        and                             ! And booleans
         fjp l pmach.28
!      v := v+1+maxint; { convert number to 31 bit unsigned }
:69
        lodi    2 -56                   ! Load local value(t)
        ldci    1                       ! Load constant(t)
        adi                             ! Add integers
        ldci    9223372036854775807     ! Load constant(t)
        adi                             ! Add integers
        stri    2 -56                   ! Store local(t)
!      t := v div 268435456{ $1000_0000}+8; { extract high digit }
:70
        lodi    2 -56                   ! Load local value(t)
        ldci    268435456               ! Load constant(t)
        dvi                             ! Divide integers
        ldci    8                       ! Load constant(t)
        adi                             ! Add integers
        stri    2 -136                  ! Store local(t)
!      digits[8] := digit(t); { place high digit }
:71
        lda     2 -201                  ! Load local address
        ldci    8                       ! Load constant(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        sfr     l pmach.29              ! Set function result
        lodi    2 -136                  ! Load local value(t)
l pmach.29=8
        cuf     l pmach.10 1 0 1 8      ! Call user function
:71
        chkc    0 255                   ! Bounds check(t)
        stoc                            ! Store to address(t)
!      v := v mod 268435456{ $1000_0000}; { remove digit }
:72
        lodi    2 -56                   ! Load local value(t)
        ldci    268435456               ! Load constant(t)
        mod                             ! Modulo integers
        stri    2 -56                   ! Store local(t)
!      n := 7 { set number of digits-1 }
:73
!    end else if (r = 8) and (v < 0) then begin
        ldci    7                       ! Load constant(t)
        stri    2 -128                  ! Store local(t)
:74
        ujp     l pmach.30              ! Unconditional jump
l pmach.28
:74
        lodi    2 -48                   ! Load local value(t)
        ldci    8                       ! Load constant(t)
        equi                            ! Equal(t)
        lodi    2 -56                   ! Load local value(t)
        ldci    0                       ! Load constant(t)
        lesi                            ! Less than(t)
        and                             ! And booleans
         fjp l pmach.31
!      v := v+1+maxint; { convert number to 31 bit unsigned }
:75
        lodi    2 -56                   ! Load local value(t)
        ldci    1                       ! Load constant(t)
        adi                             ! Add integers
        ldci    9223372036854775807     ! Load constant(t)
        adi                             ! Add integers
        stri    2 -56                   ! Store local(t)
!      t := v div 1073741824{ &10_000_000_000}+2; { extract high digit }
:76
        lodi    2 -56                   ! Load local value(t)
        ldci    1073741824              ! Load constant(t)
        dvi                             ! Divide integers
        ldci    2                       ! Load constant(t)
        adi                             ! Add integers
        stri    2 -136                  ! Store local(t)
!      digits[11] := digit(t); { place high digit }
:77
        lda     2 -201                  ! Load local address
        ldci    11                      ! Load constant(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        sfr     l pmach.32              ! Set function result
        lodi    2 -136                  ! Load local value(t)
l pmach.32=8
        cuf     l pmach.10 1 0 1 8      ! Call user function
:77
        chkc    0 255                   ! Bounds check(t)
        stoc                            ! Store to address(t)
!      v := v mod 1073741824{ $10_000_000_000}; { remove digit }
:78
        lodi    2 -56                   ! Load local value(t)
        ldci    1073741824              ! Load constant(t)
        mod                             ! Modulo integers
        stri    2 -56                   ! Store local(t)
!      n := 10 { set number of digits-1 }
:79
!    end else if (r = 2) and (v < 0) then begin
        ldci    10                      ! Load constant(t)
        stri    2 -128                  ! Store local(t)
:80
        ujp     l pmach.33              ! Unconditional jump
l pmach.31
:80
        lodi    2 -48                   ! Load local value(t)
        ldci    2                       ! Load constant(t)
        equi                            ! Equal(t)
        lodi    2 -56                   ! Load local value(t)
        ldci    0                       ! Load constant(t)
        lesi                            ! Less than(t)
        and                             ! And booleans
         fjp l pmach.34
!      v := v+1+maxint; { convert number to 31 bit unsigned }
:81
        lodi    2 -56                   ! Load local value(t)
        ldci    1                       ! Load constant(t)
        adi                             ! Add integers
        ldci    9223372036854775807     ! Load constant(t)
        adi                             ! Add integers
        stri    2 -56                   ! Store local(t)
!      t := v div 268435456{ $1000_0000}+8; { extract high digit }
:82
        lodi    2 -56                   ! Load local value(t)
        ldci    268435456               ! Load constant(t)
        dvi                             ! Divide integers
        ldci    8                       ! Load constant(t)
        adi                             ! Add integers
        stri    2 -136                  ! Store local(t)
!      digits[32] := '1'; { place high digit }
:83
        lda     2 -201                  ! Load local address
        ldci    32                      ! Load constant(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        ldcc    '1'                     ! Load constant(t)
        chkc    0 255                   ! Bounds check(t)
        stoc                            ! Store to address(t)
!      n := 31 { set number of digits-1 }
:84
!    end;
        ldci    31                      ! Load constant(t)
        stri    2 -128                  ! Store local(t)
:85
l pmach.34
:85
l pmach.33
:85
l pmach.30
:85
!    p := 1;
:86
        ldci    1                       ! Load constant(t)
        stri    2 -168                  ! Store local(t)
!    for i := 1 to n do begin
:87
        ldci    1                       ! Load constant(t)
        stri    2 -209                  ! Store local(t)
        lodi    2 -128                  ! Load local value(t)
        stri    2 -217                  ! Store local(t)
        lodi    2 -209                  ! Load local value(t)
        stri    2 -160                  ! Store local(t)
l pmach.35
:87
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        leqi                            ! Less than or equal(t)
        fjp     l pmach.36              ! False jump
!       d := v div p mod r; { extract digit }
:88
        lodi    2 -56                   ! Load local value(t)
        lodi    2 -168                  ! Load local value(t)
        dvi                             ! Divide integers
        lodi    2 -48                   ! Load local value(t)
        mod                             ! Modulo integers
        stri    2 -144                  ! Store local(t)
!       digits[i] := digit(d); { place }
:89
        lda     2 -201                  ! Load local address
        lodi    2 -160                  ! Load local value(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        sfr     l pmach.37              ! Set function result
        lodi    2 -144                  ! Load local value(t)
l pmach.37=8
        cuf     l pmach.10 1 0 1 8      ! Call user function
:89
        chkc    0 255                   ! Bounds check(t)
        stoc                            ! Store to address(t)
!       p := p*r
:90
        lodi    2 -168                  ! Load local value(t)
!    end;
        lodi    2 -48                   ! Load local value(t)
        mpi                             ! Multiply integers
        stri    2 -168                  ! Store local(t)
:91
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l pmach.36              ! True jump
        lodi    2 -160                  ! Load local value(t)
        inci    1                       ! Increment(t)
        stri    2 -160                  ! Store local(t)
        ujp     l pmach.35              ! Unconditional jump
l pmach.36
:91
        lda     2 -160                  ! Load local address
        inv                             ! Invalidate address
!    i := digmax; 
:92
        ldci    32                      ! Load constant(t)
        stri    2 -160                  ! Store local(t)
!    while (digits[i] = '0') and (i > 1) do i := i-1; { find sig digits }
:93
l pmach.38
:93
        lda     2 -201                  ! Load local address
        lodi    2 -160                  ! Load local value(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        indc    0                       ! Load indirect(t)
        ldcc    '0'                     ! Load constant(t)
        equc                            ! Equal(t)
        lodi    2 -160                  ! Load local value(t)
        ldci    1                       ! Load constant(t)
        grti                            ! Greater than(t)
        and                             ! And booleans
         fjp l pmach.39
        lodi    2 -160                  ! Load local value(t)
        ldci    1                       ! Load constant(t)
        sbi                             ! Subtract integer
        stri    2 -160                  ! Store local(t)
        ujp     l pmach.38              ! Unconditional jump
l pmach.39
:93
!    if sgn then begin digits[i+1] := '-'; i := i+1 end;
:94
        lodb    2 -169                  ! Load local value(t)
         fjp l pmach.40
        lda     2 -201                  ! Load local address
        lodi    2 -160                  ! Load local value(t)
        ldci    1                       ! Load constant(t)
        adi                             ! Add integers
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        ldcc    '-'                     ! Load constant(t)
        chkc    0 255                   ! Bounds check(t)
        stoc                            ! Store to address(t)
        lodi    2 -160                  ! Load local value(t)
        ldci    1                       ! Load constant(t)
        adi                             ! Add integers
        stri    2 -160                  ! Store local(t)
l pmach.40
:94
!    if not lz then for x := digmax downto i+1 do digits[x] := ' '; 
:95
        lodb    2 -32                   ! Load local value(t)
        notb                            ! Not(t)
         fjp l pmach.41
        ldci    32                      ! Load constant(t)
        stri    2 -209                  ! Store local(t)
        lodi    2 -160                  ! Load local value(t)
        ldci    1                       ! Load constant(t)
        adi                             ! Add integers
        stri    2 -217                  ! Store local(t)
        lodi    2 -209                  ! Load local value(t)
        stri    2 -152                  ! Store local(t)
l pmach.42
:95
        lodi    2 -152                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        geqi                            ! Greater than or equal(t)
        fjp     l pmach.43              ! False jump
        lda     2 -201                  ! Load local address
        lodi    2 -152                  ! Load local value(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        ldcc    ' '                     ! Load constant(t)
        chkc    0 255                   ! Bounds check(t)
        stoc                            ! Store to address(t)
        lodi    2 -152                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l pmach.43              ! True jump
        lodi    2 -152                  ! Load local value(t)
        deci    1                       ! Decrement(t)
        stri    2 -152                  ! Store local(t)
        ujp     l pmach.42              ! Unconditional jump
l pmach.43
:95
        lda     2 -152                  ! Load local address
        inv                             ! Invalidate address
l pmach.41
:95
!    if i > f then f := i;
:96
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -40                   ! Load local value(t)
        grti                            ! Greater than(t)
         fjp l pmach.44
        lodi    2 -160                  ! Load local value(t)
        stri    2 -40                   ! Store local(t)
l pmach.44
:96
!    if f > digmax then begin 
:97
        lodi    2 -40                   ! Load local value(t)
        ldci    32                      ! Load constant(t)
        grti                            ! Greater than(t)
         fjp l pmach.45
!      for i := 1 to f-8 do if lz then write(tf, '0') else write(tf, ' '); 
:98
        ldci    1                       ! Load constant(t)
        stri    2 -209                  ! Store local(t)
        lodi    2 -40                   ! Load local value(t)
        ldci    8                       ! Load constant(t)
        sbi                             ! Subtract integer
        stri    2 -217                  ! Store local(t)
        lodi    2 -209                  ! Load local value(t)
        stri    2 -160                  ! Store local(t)
l pmach.46
:98
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        leqi                            ! Less than or equal(t)
        fjp     l pmach.47              ! False jump
        lodb    2 -32                   ! Load local value(t)
         fjp l pmach.48
        loda    2 -64                   ! Load local value(t)
        stra    2 -228                  ! Store local(t)
        ldcc    '0'                     ! Load constant(t)
        loda    2 -228                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldci    1                       ! Load constant(t)
        csp     wrc                     ! Call system procedure/function: Write character to text file
        ujp     l pmach.49              ! Unconditional jump
l pmach.48
:98
        loda    2 -64                   ! Load local value(t)
        stra    2 -228                  ! Store local(t)
        ldcc    ' '                     ! Load constant(t)
        loda    2 -228                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldci    1                       ! Load constant(t)
        csp     wrc                     ! Call system procedure/function: Write character to text file
l pmach.49
:98
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l pmach.47              ! True jump
        lodi    2 -160                  ! Load local value(t)
        inci    1                       ! Increment(t)
        stri    2 -160                  ! Store local(t)
        ujp     l pmach.46              ! Unconditional jump
l pmach.47
:98
        lda     2 -160                  ! Load local address
        inv                             ! Invalidate address
!      f := digmax 
:99
!    end;
        ldci    32                      ! Load constant(t)
        stri    2 -40                   ! Store local(t)
:100
l pmach.45
:100
!    { print result }
!    for i := f downto 1 do write(tf, digits[i])
:101
:102
        lodi    2 -40                   ! Load local value(t)
        stri    2 -209                  ! Store local(t)
        ldci    1                       ! Load constant(t)
        stri    2 -217                  ! Store local(t)
        lodi    2 -209                  ! Load local value(t)
        stri    2 -160                  ! Store local(t)
l pmach.50
:102
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        geqi                            ! Greater than or equal(t)
        fjp     l pmach.51              ! False jump
        loda    2 -64                   ! Load local value(t)
        stra    2 -228                  ! Store local(t)
        lda     2 -201                  ! Load local address
        lodi    2 -160                  ! Load local value(t)
        chki    1 32                    ! Bounds check(t)
        deci    1                       ! Decrement(t)
        ixa     1                       ! Scale array access
        indc    0                       ! Load indirect(t)
        loda    2 -228                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldci    1                       ! Load constant(t)
        csp     wrc                     ! Call system procedure/function: Write character to text file
! end;
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -217                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l pmach.51              ! True jump
        lodi    2 -160                  ! Load local value(t)
        deci    1                       ! Decrement(t)
        stri    2 -160                  ! Store local(t)
        ujp     l pmach.50              ! Unconditional jump
l pmach.51
:103
:103
        lda     2 -160                  ! Load local address
        inv                             ! Invalidate address
        retp    0                       ! Return from procedure/function(t)
l pmach.16=224
l pmach.17=24
!
! { load code file }
!
! procedure xlate;
e r
:104
:105
:106
:107
!
!    var  ad, ad2: integer;
b r xlate@p
:108
:109
s       ad2 l -128 i
s       ad l -136 i
!         i, l, cs, csc, b: integer;
:110
s       b l -144 i
s       csc l -152 i
s       cs l -160 i
s       l l -168 i
s       i l -176 i
!         c: char;
:111
s       c l -177 c
!
!    procedure errorl; (*error in loading*)
:112
:113
!    begin writeln;
b r errorl@p
l pmach.53
:114
:114
        mst     2 l pmach.54 l pmach.55 ! Mark(frame) stack
        lao     2                       ! Load global address
        stra    3 -136                  ! Store local(t)
        loda    3 -136                  ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!       writeln('*** Invalid code deck');
:115
t       l pmach.57 1 1
        lao     2                       ! Load global address
        stra    3 -136                  ! Store local(t)
        lca     21 '*** Invalid code deck' ! Load constant string address
        ldci    21                      ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    3 -136                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        loda    3 -136                  ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!       goto 99
:116
        ipj     1 l pmach.7              ! Interprocedure jump
!    end; (*errorl*)
:117
        retp    0                       ! Return from procedure/function(t)
l pmach.54=112
l pmach.55=32
!
!    procedure readhex(var v: integer; d: integer);
e r
:118
:119
!    var i: integer; c: char;
b r readhex@p_i_i
s       v p -72 i
s       d p -64 i
:120
s       i l -136 i
s       c l -137 c
!    begin v:= 0;
l pmach.58
:121
:121
        mst     2 l pmach.59 l pmach.60 ! Mark(frame) stack
        loda    3 -72                   ! Load local value(t)
        ldci    0                       ! Load constant(t)
        stoi                            ! Store to address(t)
!      for i := 1 to d do begin
:122
        ldci    1                       ! Load constant(t)
        stri    3 -145                  ! Store local(t)
        lodi    3 -64                   ! Load local value(t)
        stri    3 -153                  ! Store local(t)
        lodi    3 -145                  ! Load local value(t)
        stri    3 -136                  ! Store local(t)
l pmach.62
:122
        lodi    3 -136                  ! Load local value(t)
        lodi    3 -153                  ! Load local value(t)
        leqi                            ! Less than or equal(t)
        fjp     l pmach.63              ! False jump
!        if eof(prd) or eoln(prd) then errorl;
:123
        lao     91                      ! Load global address
        csp     eof                     ! Call system procedure/function: Find eof of text file
        lao     91                      ! Load global address
        csp     eln                     ! Call system procedure/function: Find eoln of text file
        ior                             ! Inclusive or booleans
         fjp l pmach.64
        sfr     l pmach.65              ! Set function result
l pmach.65=0
        cup     l pmach.53 0            ! Call user procedure
:123
l pmach.64
:123
!        read(prd, c); if not (c in ['0'..'9', 'A'..'F']) then errorl;
:124
        lao     91                      ! Load global address
        stra    3 -164                  ! Store local(t)
        lda     3 -137                  ! Load local address
        loda    3 -164                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldcc    0                                           ! Load constant(t)
        ldcc    255                                         ! Load constant(t)
        csp     rcb                     ! Call system procedure/function: Read character from text file with range check
        lodc    3 -137                  ! Load local value(t)
        ordc                            ! Ordinal(t)
        ldcs    (  48  49  50  51  52  53  54  55  56  57  65  66  67  68  69  70) ! Load constant(t)
        inn                             ! Set inclusion
        notb                            ! Not(t)
         fjp l pmach.66
        sfr     l pmach.67              ! Set function result
l pmach.67=0
        cup     l pmach.53 0            ! Call user procedure
:124
l pmach.66
:124
!        if c in ['0'..'9'] then v:= v*16+ord(c)-ord('0')
:125
        lodc    3 -137                  ! Load local value(t)
        ordc                            ! Ordinal(t)
        ldcs    (  48  49  50  51  52  53  54  55  56  57) ! Load constant(t)
        inn                             ! Set inclusion
         fjp l pmach.68
        loda    3 -72                   ! Load local value(t)
        loda    3 -72                   ! Load local value(t)
        indi    0                       ! Load indirect(t)
        ldci    16                      ! Load constant(t)
        mpi                             ! Multiply integers
        lodc    3 -137                  ! Load local value(t)
        ordc                            ! Ordinal(t)
        adi                             ! Add integers
        ldcc    '0'                     ! Load constant(t)
        ordc                            ! Ordinal(t)
!        else v := v*16+ord(c)-ord('A')+10
        sbi                             ! Subtract integer
        stoi                            ! Store to address(t)
        ujp     l pmach.69              ! Unconditional jump
l pmach.68
:126
:126
        loda    3 -72                   ! Load local value(t)
        loda    3 -72                   ! Load local value(t)
        indi    0                       ! Load indirect(t)
        ldci    16                      ! Load constant(t)
        mpi                             ! Multiply integers
        lodc    3 -137                  ! Load local value(t)
        ordc                            ! Ordinal(t)
        adi                             ! Add integers
        ldcc    'A'                     ! Load constant(t)
        ordc                            ! Ordinal(t)
        sbi                             ! Subtract integer
!      end
        ldci    10                      ! Load constant(t)
        adi                             ! Add integers
        stoi                            ! Store to address(t)
l pmach.69
:127
:127
!    end;
        lodi    3 -136                  ! Load local value(t)
        lodi    3 -153                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l pmach.63              ! True jump
        lodi    3 -136                  ! Load local value(t)
        inci    1                       ! Increment(t)
        stri    3 -136                  ! Store local(t)
        ujp     l pmach.62              ! Unconditional jump
l pmach.63
:128
:128
        lda     3 -136                  ! Load local address
        inv                             ! Invalidate address
        retp    0                       ! Return from procedure/function(t)
l pmach.59=144
l pmach.60=32
!        
! begin (*xlate*)
e r
l pmach.52
:129
:130
:130
        mst     1 l pmach.70 l pmach.71 ! Mark(frame) stack
!   writeln(prr, 'unsigned char program_code[] = {');
:131
        lao     89                      ! Load global address
        stra    2 -185                  ! Store local(t)
t       l pmach.73 1 1
        lca     32 'unsigned char program_code[] = {' ! Load constant string address
        ldci    32                      ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -185                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        loda    2 -185                  ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!   ad := 0; l := 1;
:132
        ldci    0                       ! Load constant(t)
        stri    2 -136                  ! Store local(t)
        ldci    1                       ! Load constant(t)
        stri    2 -168                  ! Store local(t)
!   while not eof(prd) and (l > 0) do begin
:133
l pmach.74
:133
        lao     91                      ! Load global address
        csp     eof                     ! Call system procedure/function: Find eof of text file
        notb                            ! Not(t)
        lodi    2 -168                  ! Load local value(t)
        ldci    0                       ! Load constant(t)
        grti                            ! Greater than(t)
        and                             ! And booleans
         fjp l pmach.75
!     read(prd, c); if c <> ':' then errorl;
:134
        lao     91                      ! Load global address
        stra    2 -185                  ! Store local(t)
        lda     2 -177                  ! Load local address
        loda    2 -185                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldcc    0                                           ! Load constant(t)
        ldcc    255                                         ! Load constant(t)
        csp     rcb                     ! Call system procedure/function: Read character from text file with range check
        lodc    2 -177                  ! Load local value(t)
        ldcc    ':'                     ! Load constant(t)
        neqc                            ! Not equal(t)
         fjp l pmach.76
        sfr     l pmach.77              ! Set function result
l pmach.77=0
        cup     l pmach.53 0            ! Call user procedure
:134
l pmach.76
:134
!     readhex(l, 2); readhex(i, 16); ad2 := i; 
:135
        sfr     l pmach.78              ! Set function result
        lda     2 -168                  ! Load local address
        ldci    2                       ! Load constant(t)
l pmach.78=0
        cup     l pmach.58 2            ! Call user procedure
:135
        sfr     l pmach.79              ! Set function result
        lda     2 -176                  ! Load local address
        ldci    16                      ! Load constant(t)
l pmach.79=0
        cup     l pmach.58 2            ! Call user procedure
:135
        lodi    2 -176                  ! Load local value(t)
        stri    2 -128                  ! Store local(t)
!     if (ad <> ad2) and (l > 0) then errorl;
:136
        lodi    2 -136                  ! Load local value(t)
        lodi    2 -128                  ! Load local value(t)
        neqi                            ! Not equal(t)
        lodi    2 -168                  ! Load local value(t)
        ldci    0                       ! Load constant(t)
        grti                            ! Greater than(t)
        and                             ! And booleans
         fjp l pmach.80
        sfr     l pmach.81              ! Set function result
l pmach.81=0
        cup     l pmach.53 0            ! Call user procedure
:136
l pmach.80
:136
!     cs := 0; 
:137
        ldci    0                       ! Load constant(t)
        stri    2 -160                  ! Store local(t)
!     for i := 1 to l do 
:138
        ldci    1                       ! Load constant(t)
        stri    2 -185                  ! Store local(t)
        lodi    2 -168                  ! Load local value(t)
        stri    2 -193                  ! Store local(t)
        lodi    2 -185                  ! Load local value(t)
        stri    2 -176                  ! Store local(t)
l pmach.82
:138
        lodi    2 -176                  ! Load local value(t)
        lodi    2 -193                  ! Load local value(t)
        leqi                            ! Less than or equal(t)
        fjp     l pmach.83              ! False jump
!       begin 
:139
!         readhex(b, 2); write(prr, '0x'); wrtnum(prr, b, 16, 2, true); 
:140
        sfr     l pmach.84              ! Set function result
        lda     2 -144                  ! Load local address
        ldci    2                       ! Load constant(t)
l pmach.84=0
        cup     l pmach.58 2            ! Call user procedure
:140
        lao     89                      ! Load global address
        stra    2 -204                  ! Store local(t)
t       l pmach.85 1 1
        lca     2 '0x'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -204                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        sfr     l pmach.86              ! Set function result
        lao     89                      ! Load global address
        lodi    2 -144                  ! Load local value(t)
        ldci    16                      ! Load constant(t)
        ldci    2                       ! Load constant(t)
        ldcb    1                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
l pmach.86=0
        cup     l pmach.8 5             ! Call user procedure
:140
!         write(prr, ', '); cs := (cs+b) mod 256; ad := ad+1 
:141
        lao     89                      ! Load global address
        stra    2 -204                  ! Store local(t)
t       l pmach.87 1 1
        lca     2 ','                   ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -204                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -144                  ! Load local value(t)
        adi                             ! Add integers
        ldci    256                     ! Load constant(t)
        mod                             ! Modulo integers
        stri    2 -160                  ! Store local(t)
        lodi    2 -136                  ! Load local value(t)
!       end;
        ldci    1                       ! Load constant(t)
        adi                             ! Add integers
        stri    2 -136                  ! Store local(t)
:142
        lodi    2 -176                  ! Load local value(t)
        lodi    2 -193                  ! Load local value(t)
        equi                            ! Equal(t)
        tjp     l pmach.83              ! True jump
        lodi    2 -176                  ! Load local value(t)
        inci    1                       ! Increment(t)
        stri    2 -176                  ! Store local(t)
        ujp     l pmach.82              ! Unconditional jump
l pmach.83
:142
        lda     2 -176                  ! Load local address
        inv                             ! Invalidate address
!     readhex(csc, 2); if cs <> csc then errorl;
:143
        sfr     l pmach.88              ! Set function result
        lda     2 -152                  ! Load local address
        ldci    2                       ! Load constant(t)
l pmach.88=0
        cup     l pmach.58 2            ! Call user procedure
:143
        lodi    2 -160                  ! Load local value(t)
        lodi    2 -152                  ! Load local value(t)
        neqi                            ! Not equal(t)
         fjp l pmach.89
        sfr     l pmach.90              ! Set function result
l pmach.90=0
        cup     l pmach.53 0            ! Call user procedure
:143
l pmach.89
:143
!     writeln(prr);
:144
        lao     89                      ! Load global address
        stra    2 -185                  ! Store local(t)
        loda    2 -185                  ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!     readln(prd)
:145
        lao     91                      ! Load global address
        stra    2 -185                  ! Store local(t)
!   end;
        loda    2 -185                  ! Load local value(t)
        csp     rln                     ! Call system procedure/function: Read next line from text file
:146
        ujp     l pmach.74              ! Unconditional jump
l pmach.75
:146
!   writeln(prr, '};');
:147
        lao     89                      ! Load global address
        stra    2 -185                  ! Store local(t)
t       l pmach.91 1 1
        lca     2 '};'                  ! Load constant string address
        ldci    2                       ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -185                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        loda    2 -185                  ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!   write(prr, 'long program_code_len = 0x'); wrtnum(prr, ad, 16, 8, true);
:148
        lao     89                      ! Load global address
        stra    2 -185                  ! Store local(t)
t       l pmach.92 1 1
        lca     26 'long program_code_len = 0x' ! Load constant string address
        ldci    26                      ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    2 -185                  ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        sfr     l pmach.93              ! Set function result
        lao     89                      ! Load global address
        lodi    2 -136                  ! Load local value(t)
        ldci    16                      ! Load constant(t)
        ldci    8                       ! Load constant(t)
        ldcb    1                       ! Load constant(t)
        chkb    0 1                     ! Bounds check(t)
l pmach.93=0
        cup     l pmach.8 5             ! Call user procedure
:148
!   writeln(prr, ';');
:149
        lao     89                      ! Load global address
        stra    2 -185                  ! Store local(t)
        ldcc    ';'                     ! Load constant(t)
        loda    2 -185                  ! Load local value(t)
        swp     8                       ! Swap tos with sos
        ldci    1                       ! Load constant(t)
        csp     wrc                     ! Call system procedure/function: Write character to text file
        loda    2 -185                  ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
! end;
:150
        retp    0                       ! Return from procedure/function(t)
l pmach.70=192
l pmach.71=40
!
! begin { main }
e r
l pmach.3
:151
:152
:152
        mst     0 l pmach.94 l pmach.95 ! Mark(frame) stack
        lao     91                      ! Load global address
        lca     3 'prd'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        csp     aeft                    ! Call system procedure/function: Assign external filename to text file
        lao     89                      ! Load global address
        lca     3 'prr'                 ! Load constant string address
        ldci    3                       ! Load constant(t)
        csp     aeft                    ! Call system procedure/function: Assign external filename to text file
!
!   writeln('Mach program object deck to C constant table converter');
:153
:154
t       l pmach.97 1 1
        lao     2                       ! Load global address
        stra    1 -16                   ! Store local(t)
        lca     54 'Mach program object deck to C constant table converter' ! Load constant string address
        ldci    54                      ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    1 -16                   ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        loda    1 -16                   ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!   reset(prd);
:155
        lao     91                      ! Load global address
        csp     rsf                     ! Call system procedure/function: Reset file text
!   rewrite(prr);
:156
        lao     89                      ! Load global address
        csp     rwf                     ! Call system procedure/function: Rewrite file text
!   xlate;
:157
        sfr     l pmach.98              ! Set function result
l pmach.98=0
        cup     l pmach.52 0            ! Call user procedure
:157
!   writeln('Program complete');
:158
t       l pmach.99 1 1
        lao     2                       ! Load global address
        stra    1 -16                   ! Store local(t)
        lca     16 'Program complete'   ! Load constant string address
        ldci    16                      ! Load constant(t)
        swp     8                       ! Swap tos with sos
        mpc     0 0                     ! Make fat pointer from components
        loda    1 -16                   ! Load local value(t)
        swp     16                      ! Swap tos with sos
        cpl                             ! Copy length from complex pointer
        csp     wrs                     ! Call system procedure/function: Write string to text file
        loda    1 -16                   ! Load local value(t)
        csp     wln                     ! Call system procedure/function: Write next line to text file
!   99:;
:159
l pmach.7
:159
!
! end.
:160
:161
        retp    0                       ! Return from procedure/function(t)
l pmach.94=16
l pmach.95=32
g       93
e       p
f       0
q
